"""Curated review questions for the Balkan pilot: groups raw conflicts, adds suggested answers and evidence."""
import json

EV = {
 'vienna1815': ('Congress of Vienna, Final Act', '1815-06-09', 'Treaty', 'https://en.wikipedia.org/wiki/Congress_of_Vienna'),
 'paris1815': ('Treaty of Paris (Nov 1815): Ionian protectorate', '1815-11', 'Treaty', 'https://en.wikipedia.org/wiki/United_States_of_the_Ionian_Islands'),
 'adrianople1829': ('Treaty of Adrianople', '1829-09-14', 'Treaty', 'https://en.wikipedia.org/wiki/Treaty_of_Adrianople_(1829)'),
 'london1830': ('London Protocol: Greek independence', '1830-02-03', 'Treaty', 'https://en.wikipedia.org/wiki/London_Protocol_(1830)'),
 'serbia1830': ('Ottoman decrees of 1830 and 1833 on Serbian self-rule', '1830 / 1833', 'Decree', 'https://en.wikipedia.org/wiki/Principality_of_Serbia'),
 'london1832': ('London Conference of 1832', '1832-05-07', 'Treaty', 'https://en.wikipedia.org/wiki/London_Conference_of_1832'),
 'constantinople1832': ('Treaty of Constantinople (1832)', '1832-07-21', 'Treaty', 'https://en.wikipedia.org/wiki/Treaty_of_Constantinople_(1832)'),
 'london1840': ('Convention of London (1840)', '1840-07-15', 'Treaty', 'https://en.wikipedia.org/wiki/Convention_of_London_(1840)'),
 'hungary1849': ('End of the Hungarian revolution (surrender at Világos)', '1849-08-13', 'Event', 'https://en.wikipedia.org/wiki/Hungarian_Revolution_of_1848'),
 'baltaliman1849': ('Convention of Balta Liman', '1849-05-01', 'Treaty', 'https://en.wikipedia.org/wiki/Convention_of_Balta_Liman'),
 'principalities': ('Danubian Principalities: occupations and self-rule', '1828–1857', 'Reference', 'https://en.wikipedia.org/wiki/Danubian_Principalities'),
 'paris1856': ('Treaty of Paris (1856)', '1856-03-30', 'Treaty', 'https://en.wikipedia.org/wiki/Treaty_of_Paris_(1856)'),
 'union1859': ('Union of Wallachia and Moldavia', '1859-01/02', 'Event', 'https://en.wikipedia.org/wiki/United_Principalities'),
 'london1864': ('Treaty of London (1864): Ionian Islands to Greece', '1864-03-29', 'Treaty', 'https://en.wikipedia.org/wiki/Treaty_of_London_(1864)'),
 'montenegro': ('Principality of Montenegro', '1852–1910', 'Reference', 'https://en.wikipedia.org/wiki/Principality_of_Montenegro'),
 'russianadmin': ('Russian provisional administration in Bulgaria', '1877–1879', 'Reference', 'https://en.wikipedia.org/wiki/Provisional_Russian_Administration_in_Bulgaria'),
 'berlin1878': ('Treaty of Berlin', '1878-07-13', 'Treaty', 'https://en.wikipedia.org/wiki/Treaty_of_Berlin_(1878)'),
 'bosnia1878': ('Austro-Hungarian occupation of Bosnia and Herzegovina', '1878-07/10', 'Event', 'https://en.wikipedia.org/wiki/Austro-Hungarian_campaign_in_Bosnia_and_Herzegovina_in_1878'),
 'kolasin1878': ('Kolašin joins Montenegro', '1878-10-04', 'Event', 'https://en.wikipedia.org/wiki/Upper_Kola%C5%A1in'),
 'ulcinj1880': ('Ulcinj handed over to Montenegro', '1880-11-23', 'Event', 'https://en.wikipedia.org/wiki/Battle_of_Ulcinj_(1880)'),
 'constantinople1881': ('Convention of Constantinople (1881): Thessaly and Arta to Greece', '1881-05-24', 'Treaty', 'https://en.wikipedia.org/wiki/Convention_of_Constantinople_(1881)'),
 'tyrnavos': ('Tyrnavos annexed with the rest of Thessaly', '1881', 'Reference', 'https://en.wikipedia.org/wiki/Tyrnavos'),
 'unification1885': ('Bulgarian unification with Eastern Rumelia', '1885-09-18', 'Event', 'https://en.wikipedia.org/wiki/Bulgarian_unification'),
 'rumelia': ('Eastern Rumelia (self-governing Ottoman province)', '1878–1885', 'Reference', 'https://en.wikipedia.org/wiki/Eastern_Rumelia'),
 'tophane1886': ('Tophane Agreement', '1886-04-05', 'Treaty', 'https://en.wikipedia.org/wiki/Tophane_Agreement'),
 'constantinople1897': ('Treaty of Constantinople (1897)', '1897-12-04', 'Treaty', 'https://en.wikipedia.org/wiki/Treaty_of_Constantinople_(1897)'),
 'cretanstate': ('Cretan State', '1898-12', 'Reference', 'https://en.wikipedia.org/wiki/Cretan_State'),
 'novipazar': ('Sanjak of Novi Pazar', '1878–1908', 'Reference', 'https://en.wikipedia.org/wiki/Sanjak_of_Novi_Pazar'),
 'bukovina': ('Duchy of Bukovina (Austrian since 1775)', '1775–1918', 'Reference', 'https://en.wikipedia.org/wiki/Duchy_of_Bukovina'),
 'dalmatia': ('Kingdom of Dalmatia (Austrian, incl. Bay of Kotor)', '1815–1918', 'Reference', 'https://en.wikipedia.org/wiki/Kingdom_of_Dalmatia'),
 'frontier': ('Military Frontier (Habsburg border zone incl. Zemun)', 'to 1881', 'Reference', 'https://en.wikipedia.org/wiki/Military_Frontier'),
 'serbwar1878': ('Serbian–Ottoman War: Niš taken', '1878-01', 'Event', 'https://en.wikipedia.org/wiki/Serbian%E2%80%93Ottoman_War_(1876%E2%80%931878)'),
 'greekwar': ('Greek War of Independence', '1821–1830', 'Reference', 'https://en.wikipedia.org/wiki/Greek_War_of_Independence'),
}

def seg(holder, frm, to, note='', ev=()):
    return {'holder': holder, 'from': frm, 'to': to, 'note': note, 'ev': list(ev)}

Q = [
 dict(id='danube', status='rule', rule='vassal', title='Wallachia and Moldavia before 1878',
      question='Should Wallachia, Moldavia and the United Principalities show as their own states before 1878?',
      raw=['c001','c005','c007','c010','c013','c038','c039','c036','c047'],
      problem='OHM and Cliopatria show self-governing principalities. CShapes counts only fully independent states, so it shows the Ottoman Empire until 1878.',
      legal=[seg('OTT','1815','1878-07-13','Overlord of self-governing principalities',['adrianople1829','paris1856']), seg('ROM','1878-07-13','1900','Independent',['berlin1878'])],
      actual=[seg('WAL','1815','1859-02-05','Wallachia and Moldavia, each self-governing',['adrianople1829']), seg('ROM','1859-02-05','1900','United Principalities, Romania from 1881',['union1859','berlin1878'])],
      confidence='high', conf_note='The facts are not in doubt; which map to show is a rule decision.',
      why=['CShapes records only fully independent states.', 'Brăila was an Ottoman fortress until the Treaty of Adrianople (1829) returned it to Wallachia; CShapes and Cliopatria draw it coarsely.'],
      evidence=['adrianople1829','paris1856','union1859','berlin1878']),
 dict(id='occupations', status='rule', rule='control', title='Russian and Austrian occupations of the principalities',
      question='Should the "actual control" map show the foreign occupations of Wallachia and Moldavia?',
      raw=['c011','c014','c025','c027','c054','c073','c063','c101'],
      problem='CShapes and Cliopatria show Russia (1828–34, 1848–55) and Austria (1856) as holders; OHM keeps the principalities throughout.',
      legal=[seg('WAL','1828','1859-02-05','Self-governing, under Ottoman overlordship throughout',['adrianople1829','baltaliman1849','paris1856'])],
      actual=[seg('RUS','1828','1834','Russian occupation after the 1828–29 war',['adrianople1829']), seg('WAL','1834','1848','',[]), seg('RUS','1848','1851','Russian and Ottoman troops after the 1848 revolutions',['baltaliman1849']), seg('WAL','1851','1853-07','',[]), seg('RUS','1853-07','1854-08','Russian occupation at the start of the Crimean War',['principalities']), seg('AUT','1854-08','1857-03','Austrian occupation',['principalities']), seg('WAL','1857-03','1859-02-05','',[])],
      confidence='medium', conf_note='The occupations are well documented, but the month each began and ended needs checking by someone who knows the period.',
      why=['OHM records legal title only.', 'Cliopatria and CShapes mix legal title and military occupation, and use whole years.'],
      evidence=['adrianople1829','baltaliman1849','principalities','paris1856']),
 dict(id='serbia', status='rule', rule='vassal', title='Serbia 1833–1878',
      question='Should self-governing Serbia show as its own state before its independence in 1878?',
      raw=['c002'],
      problem='OHM and Cliopatria show Serbia as its own state; CShapes shows the Ottoman Empire until 1878.',
      legal=[seg('OTT','1833','1878-07-13','Overlord of self-governing Serbia',['serbia1830']), seg('SRB','1878-07-13','1900','Independent',['berlin1878'])],
      actual=[seg('SRB','1833','1900','Self-governing, independent from 1878',['serbia1830','berlin1878'])],
      confidence='high', conf_note='Only the rule decides this one.',
      why=['CShapes records only fully independent states.'],
      evidence=['serbia1830','berlin1878']),
 dict(id='serbia-early', status='expert', title='When does self-governing Serbia begin?',
      question='Did Serbia govern itself from 1815, from 1830, or only from 1833 as OHM has it?',
      raw=['c003'], towns=['Belgrade','Kragujevac','Kruševac','Negotin','Smederevo','Užice','Zaječar','Čačak','Šabac'],
      problem='OHM starts self-governing Serbia in 1833, Cliopatria before 1816, and CShapes only at independence in 1878.',
      legal=[seg('OTT','1815','1878-07-13','Ottoman sovereignty throughout; Serbian self-rule recognized in 1830',['serbia1830'])],
      actual=[seg('SRB','1815','1900','Core districts around Belgrade: self-governing after the Second Serbian Uprising (1815)',['serbia1830']), seg('OTT','1815','1833','Negotin, Zaječar and Kruševac: added to Serbia only in 1833',['serbia1830'])],
      confidence='medium', conf_note='Historians date Serbian self-rule differently (1815, 1817, 1830). An expert should pick the date and check which districts it covered.',
      why=['OHM uses the 1833 borders for the whole period.', 'Cliopatria extends early Serbia too far south (see the Niš question).'],
      evidence=['serbia1830','berlin1878']),
 dict(id='nis', status='ready', title='Niš, Prokuplje and Kuršumlija before 1878',
      question='Were Niš, Prokuplje and Kuršumlija Serbian before 1878?',
      raw=['c003'], towns=['Niš','Prokuplje','Kuršumlija'],
      problem='Cliopatria places these towns in Serbia from 1816. OHM and CShapes keep them Ottoman until 1878.',
      legal=[seg('OTT','1815','1878-07-13','',[]), seg('SRB','1878-07-13','1900','Taken by Serbia in January 1878, confirmed at Berlin',['serbwar1878','berlin1878'])],
      actual=None, confidence='high', conf_note='Both change dates come from the war record and the Treaty of Berlin.',
      why=['Cliopatria draws early Serbia too large.'], evidence=['serbwar1878','berlin1878']),
 dict(id='bulgaria-1885', status='ready', rule='vassal', title='Bulgaria after 1885 is missing from OHM',
      question='Who held Bulgaria from the 1885 unification to 1900?',
      raw=['c004','c021','c046'],
      problem='OHM ends its Bulgaria record in September 1885 and shows plain Ottoman territory afterward. CShapes and Cliopatria show Bulgaria.',
      legal=[seg('OTT','1885-09-18','1900','Overlord until Bulgarian independence in 1908',['berlin1878','tophane1886'])],
      actual=[seg('BUL','1885-09-18','1900','United Principality of Bulgaria (with Eastern Rumelia)',['unification1885','tophane1886'])],
      confidence='high', conf_note='Well documented. OHM is simply missing the record.',
      why=['OHM has no Bulgaria record between September 1885 and 1908.'],
      evidence=['berlin1878','unification1885','tophane1886']),
 dict(id='rumelia', status='rule', rule='vassal', title='Eastern Rumelia 1878–1885',
      question='Should self-governing Eastern Rumelia show as its own unit?',
      raw=['c040'],
      problem='OHM shows Eastern Rumelia as a self-governing province. CShapes and Cliopatria show the Ottoman Empire.',
      legal=[seg('OTT','1878-07-13','1885-09-18','Overlord',['berlin1878'])],
      actual=[seg('ERU','1878-07-13','1885-09-18','Self-governing Ottoman province',['berlin1878','rumelia']), seg('BUL','1885-09-18','1900','United with Bulgaria',['unification1885'])],
      confidence='high', conf_note='Only the rule decides this one.', why=['CShapes and Cliopatria do not record self-governing provinces.'],
      evidence=['berlin1878','rumelia','unification1885']),
 dict(id='kardzhali', status='expert', title='Kyustendil, Kardzhali and Smolyan',
      question='Which side of the Bulgarian–Ottoman line were these three towns on after 1878?',
      raw=['c032','c071','c096','c080'],
      problem='CShapes puts Kyustendil in the Ottoman Empire. Cliopatria puts Kardzhali and Smolyan in Bulgaria.',
      legal=[seg('BUL','1878-07-13','1900','Kyustendil: Bulgaria from the Treaty of Berlin',['berlin1878']), seg('OTT','1886-04-05','1900','Kardzhali: Ottoman under the Tophane Agreement',['tophane1886']), seg('OTT','1815','1900','Smolyan: Ottoman until 1912',[])],
      actual=None, confidence='medium', conf_note='Kyustendil and Smolyan are clear. Who held Kardzhali between 1878 and 1886 needs an expert.',
      why=['CShapes and Cliopatria draw this border coarsely.'], evidence=['berlin1878','tophane1886']),
 dict(id='ionian', status='rule', rule='vassal', title='Ionian Islands 1815–1864',
      question='Show the Ionian Islands as their own state, or as British?',
      raw=['c006','c050','c088','c067','c087'],
      problem='OHM shows the United States of the Ionian Islands. CShapes and Cliopatria show the United Kingdom. Cliopatria also keeps the UK after the 1864 union with Greece.',
      legal=[seg('ION','1815-11','1864-05-28','British protectorate',['paris1815']), seg('GRE','1864-05-28','1900','United with Greece',['london1864'])],
      actual=[seg('UK','1815','1864-05-28','British administration',['paris1815']), seg('GRE','1864-05-28','1900','',['london1864'])],
      confidence='high', conf_note='Facts are clear. The rule decides how to show a protectorate.',
      why=['OHM has no record for the islands before November 1815.', 'Cliopatria keeps a British claim on some islands until 1869.'],
      evidence=['paris1815','london1864']),
 dict(id='bosnia', status='rule', rule='control', title='Bosnia and Herzegovina 1878–1900',
      question='Ottoman (legal title) or Austro-Hungarian (actual control)?',
      raw=['c009','c019','c034','c066'],
      problem='OHM keeps Bosnia Ottoman. CShapes and Cliopatria show Austria-Hungary from 1878.',
      legal=[seg('OTT','1878','1900','Ottoman sovereignty until the 1908 annexation',['berlin1878'])],
      actual=[seg('AUT','1878-07','1900','Occupied and run by Austria-Hungary',['berlin1878','bosnia1878'])],
      confidence='high', conf_note='Both views are correct; the rule decides which map shows which.',
      why=['Sources pick different kinds of control.'], evidence=['berlin1878','bosnia1878']),
 dict(id='kotor', status='ready', title='Bay of Kotor 1815–1900',
      question='Who held Kotor and Herceg Novi?',
      raw=['c008','c026','c092'],
      problem='CShapes shows the Ottoman Empire until 1878 and Montenegro after. Cliopatria shows France until 1819. OHM shows Austria.',
      legal=[seg('AUT','1815-06-09','1900','Part of Austrian Dalmatia',['vienna1815','dalmatia'])],
      actual=None, confidence='high', conf_note='Austrian from the Congress of Vienna to 1918.',
      why=['CShapes and Cliopatria draw the coast coarsely.'], evidence=['vienna1815','dalmatia']),
 dict(id='spizza', status='ready', title='Spič (Sutomore) after 1878',
      question='Who held the Spič coast after 1878?',
      raw=['c051','c082','c124'],
      problem='OHM shows Austria-Hungary. CShapes shows Montenegro. Cliopatria shows the Ottoman Empire, then Montenegro.',
      legal=[seg('OTT','1815','1878-07-13','',[]), seg('AUT','1878-07-13','1900','Given to Austria-Hungary (Dalmatia) by the Treaty of Berlin',['berlin1878'])],
      actual=None, confidence='high', conf_note='The Treaty of Berlin names Spizza explicitly.',
      why=['A small strip that coarse sources miss.'], evidence=['berlin1878','dalmatia']),
 dict(id='zemun', status='ready', title='Zemun 1815–1900',
      question='Was Zemun Serbian or Habsburg?',
      raw=['c018','c043'],
      problem='CShapes shows the Ottoman Empire, then Serbia. Cliopatria shows Serbia. OHM shows Austria.',
      legal=[seg('AUT','1815','1900','Habsburg border town across the river from Belgrade',['frontier'])],
      actual=None, confidence='high', conf_note='Habsburg until 1918.',
      why=['Zemun sits across the river from Belgrade; coarse borders put it on the wrong side.'], evidence=['frontier']),
 dict(id='severin', status='ready', title='Turnu Severin 1815–1900',
      question='Was Turnu Severin in Wallachia or Serbia?',
      raw=['c042','c044','c045','c058','c074','c102'],
      problem='Cliopatria places it in Serbia. OHM and CShapes place it on the Wallachian (Romanian) side.',
      legal=[seg('WAL','1815','1859-02-05','',['adrianople1829']), seg('ROM','1859-02-05','1900','',['union1859'])],
      actual=None, confidence='high', conf_note='The town is on the north bank of the Danube, in Wallachia.',
      why=['Cliopatria draws the Danube border coarsely.'], evidence=['adrianople1829','union1859']),
 dict(id='suceava', status='ready', title='Suceava (Bukovina) 1815–1900',
      question='Was Suceava Austrian or Moldavian?',
      raw=['c028','c052','c059','c075','c076','c103'],
      problem='Cliopatria places it in Moldavia, Russia or Romania at different times. OHM and CShapes show Austria.',
      legal=[seg('AUT','1815','1900','Part of Austrian Bukovina',['bukovina'])],
      actual=None, confidence='high', conf_note='Austrian from 1775 to 1918.',
      why=['Cliopatria draws the Bukovina border coarsely.'], evidence=['bukovina']),
 dict(id='montenegro', status='rule', rule='control', title='Montenegro before 1878',
      question='Show Montenegro as independent before the powers recognized it in 1878?',
      raw=['c015','c024','c109'],
      problem='OHM shows Montenegro throughout. CShapes shows the Ottoman Empire until 1878. Cliopatria shows the Ottoman Empire until 1852.',
      legal=[seg('OTT','1815','1878-07-13','Claimed by the Ottoman Empire',[]), seg('MNE','1878-07-13','1900','Independence recognized',['berlin1878'])],
      actual=[seg('MNE','1815','1900','Self-ruling under its prince-bishops, a principality from 1852',['montenegro'])],
      confidence='high', conf_note='Facts are clear; the rule decides which map shows which.',
      why=['Sources pick different kinds of control.'], evidence=['montenegro','berlin1878']),
 dict(id='montenegro-towns', status='expert', title='When did Nikšić, Podgorica, Bar, Kolašin and Ulcinj become Montenegrin?',
      question='When did each of these towns become Montenegrin?',
      raw=['c022','c031','c091'],
      problem='OHM puts Ulcinj in Montenegro in 1878, two years early. Cliopatria shows Nikšić and Kolašin as Montenegrin from 1853 and keeps Podgorica, Bar, Ulcinj and Andrijevica Ottoman until 1885.',
      legal=[seg('OTT','1815','1878-07-13','',[]), seg('MNE','1878-07-13','1900','Nikšić, Podgorica, Bar, Andrijevica (Treaty of Berlin)',['berlin1878']), seg('MNE','1878-10-04','1900','Kolašin',['kolasin1878']), seg('MNE','1880-11-23','1900','Ulcinj',['ulcinj1880'])],
      actual=None, confidence='medium', conf_note='Ulcinj, Podgorica and Kolašin are documented. Andrijevica needs checking.',
      why=['OHM gives Ulcinj the 1878 date of the other towns.', 'Cliopatria uses the wrong decades.'],
      evidence=['berlin1878','kolasin1878','ulcinj1880']),
 dict(id='greece-start', status='expert', title='When does Greece begin?',
      question='From which date should the Greek state show: 1822, 1830 or 1832?',
      raw=['c017','c037','c061','c112'],
      problem='OHM starts Greece in May 1832 (with an Ottoman overlap until August). CShapes starts in 1829–31. Cliopatria starts some towns in 1822 and wrongly includes Crete in 1828–29.',
      legal=[seg('OTT','1815','1830-02-03','',[]), seg('GRE','1830-02-03','1900','Independence recognized by the London Protocol; borders fixed in 1832',['london1830','london1832','constantinople1832'])],
      actual=[seg('GRE','1822','1900','Greek provisional government in much of the Peloponnese from 1822, with reconquests in 1825–27',['greekwar'])],
      confidence='medium', conf_note='The legal dates are clear. Actual control in the 1820s changed town by town and needs an expert.',
      why=['OHM uses the final 1832 borders only.', 'Cliopatria extends Greece to Crete for 1828–29, which is wrong.'],
      evidence=['greekwar','london1830','london1832','constantinople1832']),
 dict(id='crete-egypt', status='rule', rule='vassal', title='Crete under Egypt 1830–1840',
      question='Show Egyptian rule over Crete (1830–1840) as its own holder?',
      raw=['c048','c069'],
      problem='OHM and CShapes show Egypt. Cliopatria shows the Ottoman Empire, and Greece for 1831–33.',
      legal=[seg('OTT','1830','1840','Overlord',[])],
      actual=[seg('EGY','1830','1840-07-15','Governed by Muhammad Ali of Egypt',['london1840'])],
      confidence='high', conf_note='Cliopatria\'s Greek period is an error; the rest is the rule.',
      why=['Cliopatria gives Crete to Greece for 1831–33 by mistake.'], evidence=['london1840']),
 dict(id='cretan-state', status='rule', rule='vassal', title='Cretan State from 1898',
      question='Show the self-governing Cretan State as its own unit?',
      raw=['c070'],
      problem='OHM and Cliopatria show the Cretan State. CShapes shows the Ottoman Empire.',
      legal=[seg('OTT','1898','1900','Overlord',[])],
      actual=[seg('CRT','1898-12','1900','Self-governing under a high commissioner',['cretanstate'])],
      confidence='high', conf_note='OHM gives only the year (1898); the new state began in December.',
      why=['CShapes records only fully independent states.'], evidence=['cretanstate']),
 dict(id='thessaly', status='ready', title='Thessaly, Arta and Tyrnavos after 1881',
      question='When did Thessaly, Arta and Tyrnavos become Greek?',
      raw=['c053','c060','c093','c098','c125'], towns=['Kalabaka','Karditsa','Larissa','Trikala','Volos','Arta','Tyrnavos'],
      problem='OHM leaves Arta and Tyrnavos Ottoman. CShapes keeps Tyrnavos Ottoman. Cliopatria keeps Larissa, Volos and Trikala Ottoman until 1885.',
      legal=[seg('OTT','1815','1881-07','',[]), seg('GRE','1881-07','1900','Handed over after the Convention of Constantinople',['constantinople1881','tyrnavos'])],
      actual=None, confidence='high', conf_note='The 1881 convention names these districts.',
      why=['OHM\'s 1881 border is drawn wrong at Arta and Tyrnavos.', 'Cliopatria moves the change to 1885.'],
      evidence=['constantinople1881','tyrnavos']),
 dict(id='elassona', status='ready', title='Elassona and Preveza',
      question='Were Elassona and Preveza Greek before 1900?',
      raw=['c012','c068','c099'], towns=['Elassona','Preveza'],
      problem='Cliopatria puts both towns in Greece from 1834. OHM and CShapes keep them Ottoman.',
      legal=[seg('OTT','1815','1900','Both stayed Ottoman until 1912',[])],
      actual=None, confidence='high', conf_note='The 1881 border left both towns outside Greece.',
      why=['Cliopatria draws the Greek border too far north.'], evidence=['constantinople1881']),
 dict(id='gap1897', status='ready', title='No country anywhere in the Ottoman lands in 1897',
      question='Who held the Ottoman lands in 1897?',
      raw=['c020','c046','c066','c096','c110','c121','c127'],
      problem='OHM ends one Ottoman record in "1897" and starts the next in "1898", leaving the whole year empty.',
      legal=[seg('OTT','1897','1898','Ottoman Empire continuously; the Dec 1897 treaty moved only small border strips',['constantinople1897'])],
      actual=None, confidence='high', conf_note='A data gap in OHM, not a historical question.',
      why=['Year-only dates in OHM leave a gap.'], evidence=['constantinople1897']),
 dict(id='bessarabia', status='ready', title='Southern Bessarabia 1849–1856',
      question='Russian or Ottoman before the 1856 transfer?',
      raw=['c030'],
      problem='CShapes shows Russia and the Ottoman Empire at the same time. OHM and Cliopatria show Russia.',
      legal=[seg('RUS','1815','1856-03-30','',[]), seg('MOL','1856-03-30','1859-02-05','Transferred to Moldavia by the Treaty of Paris',['paris1856'])],
      actual=None, confidence='high', conf_note='The Treaty of Paris dates the change.',
      why=['CShapes has overlapping records here.'], evidence=['paris1856']),
 dict(id='ruse-silistra', status='ready', title='Ruse and Silistra',
      question='Were Ruse and Silistra on the Ottoman or the Wallachian side?',
      raw=['c029','c035','c041','c089','c055','c064','c106'],
      problem='Cliopatria places both towns in Wallachia or Romania, and in some years Russia or Austria. OHM and CShapes keep them Ottoman until 1878.',
      legal=[seg('OTT','1815','1878-07-13','',[]), seg('BUL','1878-07-13','1900','',['berlin1878'])],
      actual=None, confidence='high', conf_note='Both towns are on the south bank of the Danube. Russian troops held Silistra for a time after 1829; that belongs to the actual-control map.',
      why=['Cliopatria draws the Danube border on the wrong side.'], evidence=['adrianople1829','berlin1878']),
 dict(id='novipazar', status='ready', title='Novi Pazar, Pljevlja and Bijelo Polje after 1878',
      question='Who held the Sanjak of Novi Pazar after 1878?',
      raw=['c049','c097','c121','c033','c081','c110'],
      problem='CShapes puts Novi Pazar in Serbia. Cliopatria puts Pljevlja and Bijelo Polje in Austria-Hungary.',
      legal=[seg('OTT','1815','1900','Ottoman, with Austro-Hungarian garrisons allowed from 1879',['berlin1878','novipazar'])],
      actual=None, confidence='high', conf_note='The garrisons did not change who ruled the area.',
      why=['CShapes and Cliopatria confuse garrisons with rule.'], evidence=['berlin1878','novipazar']),
 dict(id='hungary', status='ready', title='Transylvania and Banat 1849–1852',
      question='Did the Hungarian revolutionaries hold the area until 1852?',
      raw=['c016'],
      problem='Cliopatria shows Hungarian revolutionaries until 1852. OHM and CShapes show Austria.',
      legal=[seg('AUT','1849','1900','',[])],
      actual=[seg('AUT','1849-08-13','1900','Revolution defeated in August 1849',['hungary1849'])],
      confidence='high', conf_note='The revolution ended in August 1849.',
      why=['Cliopatria carries the revolution on for three years too long.'], evidence=['hungary1849']),
 dict(id='bulgaria-1877', status='rule', rule='control', title='Russian administration of Bulgaria 1877–1879',
      question='Show the Russian provisional administration on the actual-control map?',
      raw=['c023'],
      problem='Cliopatria shows Russia for 1877–79. OHM and CShapes show the Ottoman Empire, then Bulgaria.',
      legal=[seg('OTT','1877','1878-07-13','',[]), seg('BUL','1878-07-13','1900','',['berlin1878'])],
      actual=[seg('RUS','1877','1879-06','Russian provisional administration',['russianadmin']), seg('BUL','1879-06','1900','',[])],
      confidence='medium', conf_note='The end date differs between Bulgaria proper and Eastern Rumelia.',
      why=['Sources pick different kinds of control.'], evidence=['russianadmin','berlin1878']),
]

RULES = [
 {'id': 'vassal', 'q': 'How should self-governing states under an overlord be shown?', 'why': 'Serbia, Wallachia, Moldavia, Bulgaria, Eastern Rumelia, the Ionian Islands and Crete governed themselves but were not fully independent.', 'options': ['As their own states, marked self-governing', 'As part of the overlord'], 'default': 0},
 {'id': 'control', 'q': 'Which kind of control does the main map show?', 'why': 'Bosnia, Montenegro, the occupied principalities and 1877–79 Bulgaria were held legally by one state and actually by another.', 'options': ['Legal title', 'Actual control', 'Both, as two maps'], 'default': 2},
 {'id': 'timing', 'q': 'When sources agree who, but differ by a year on when, what counts?', 'why': 'Sources use whole years differently; OHM usually has the exact day.', 'options': ['Use the most precise date (usually OHM) automatically', 'Review each one'], 'default': 0},
 {'id': 'approve', 'q': 'Who can approve an answer?', 'why': 'Reviewers do not need to be historians if the evidence is strong enough.', 'options': ['Anyone, when every change date links to a treaty or event', 'Experts only'], 'default': 0},
]

json.dump({'questions': Q, 'evidence': {k: {'title': v[0], 'date': v[1], 'kind': v[2], 'url': v[3]} for k, v in EV.items()}, 'rules': RULES},
          open('questions.json', 'w'), ensure_ascii=False, indent=1)
raw = json.load(open('conflicts_raw.json'))
used = {r for q in Q for r in q['raw']}
left = [c for c in raw if c['category'] != 'timing' and c['id'] not in used]
print(len(Q), 'questions;', 'unassigned non-timing conflicts:', [(c['id'], c['town_years']) for c in left])
for q in Q:
    for s in (q['legal'] or []) + (q['actual'] or []):
        for e in s['ev']: assert e in EV, e
    for e in q['evidence']: assert e in EV, e
