"""Which Wikipedia article (and so which Wikidata item and flag) goes with each description on the map.

Keys are description titles (descriptions15.py, descriptions.py, descriptions20.py). By default a title is looked up
with any "(...)" at the end removed; ARTICLE gives the article where that does not work. A value can be a list of
(article, first year, last year) where one description spans two flags. (unit, title) keys pick between two
descriptions with the same title. Occupied and annexed territories (crosshatched on the map) get no flag, and neither
do the titles in NO_FLAG, which have no flag of their own."""

NO_FLAG = {'Gaelic Irish kingdoms and lordships', 'Peoples of the North Caucasus', 'County of Sovana (Pitigliano)',
           'Garibaldi’s dictatorship in Sicily and Naples', 'Schleswig-Holstein under joint Austrian and Prussian rule',
           'Duchies of Jülich-Berg and Cleves-Mark', 'Duchy of Saxony (Ernestine)'}

ARTICLE = {
    # ---------- 1500-1799 ----------
    'Archduchy of Austria and the Habsburg lands': 'Archduchy of Austria',
    'Margraviates of Baden-Durlach and Baden-Baden': 'Margraviate of Baden',
    'Duchies of Bavaria': 'Duchy of Bavaria',
    ('DEN', 'Kingdom of Denmark'): 'Denmark',
    'Kingdom of Spain (Castile and Aragon)': 'Spanish Empire',
    'Georgian kingdoms of Kartli and Kakheti': 'Kingdom of Kartli',
    'Massa and Carrara': 'Duchy of Massa and Carrara',
    'Morocco (Wattasid and Saadi sultanates)': 'Saadi Sultanate',
    'Roman Republic': 'Roman Republic (1798–1799)',
    'County of Schwarzburg (Rudolstadt)': 'Schwarzburg-Rudolstadt',
    'Sweden (in the Kalmar Union)': 'Kalmar Union',
    ('SWE', 'Kingdom of Sweden'): 'Sweden',
    'Republic of the Seven Tithings (Valais)': 'Republic of the Seven Zenden',
    'Free State of the Three Leagues (Grisons)': 'Three Leagues',
    'Mantua (duchy from 1530)': 'Duchy of Mantua',
    'Mirandola': 'Duchy of Mirandola',
    'Guastalla (duchy from 1621)': 'Duchy of Guastalla',
    'County of Novellara and Bagnolo': 'County of Novellara',
    'Knights of St John (Knights Hospitaller)': 'Hospitaller Malta',
    'East Frisia (principality from 1654)': 'County of East Frisia',
    ('HUK', 'Kingdom of Hungary'): 'Kingdom of Hungary (1301–1526)',
    'Eastern Hungarian Kingdom and Principality of Transylvania': 'Principality of Transylvania (1570–1711)',
    ('PLK', 'Kingdom of Poland'): 'Crown of the Kingdom of Poland',
    'Principality of Ryazan': 'Grand Duchy of Ryazan',
    'Khanate of Astrakhan': 'Astrakhan Khanate',
    'Kingdom of Shirvan': 'Shirvanshah',
    'Hafsid Sultanate of Tunis': 'Hafsid dynasty',
    'Duchy of Bouillon': 'Duchy of Bouillon',
    # ---------- 1800-1899 ----------
    'Principality of Andorra': 'Andorra',
    'Principality of Anhalt-Dessau': 'Anhalt-Dessau', 'Duchy of Anhalt-Dessau': 'Anhalt-Dessau',
    'Bosnia and Herzegovina under Austro-Hungarian rule': 'Condominium of Bosnia and Herzegovina',
    'Baden (margraviate, electorate from 1803, grand duchy from 1806)': 'Grand Duchy of Baden',
    ('DEN', 'Kingdom of Denmark'): 'Denmark',
    ('ESP', 'Kingdom of Spain'): 'Spain',
    'Kingdom of France (Restoration and July Monarchy)': [('Bourbon Restoration in France', 1814, 1829), ('July Monarchy', 1830, 1848)],
    'Grand Duchy of Hesse (Hesse-Darmstadt)': 'Grand Duchy of Hesse',
    'Electorate of Hesse (Hesse-Kassel)': 'Electorate of Hesse',
    'Principality of Hohenzollern-Hechingen': 'Hohenzollern-Hechingen',
    'Principality of Hohenzollern-Sigmaringen': 'Hohenzollern-Sigmaringen',
    'Principality of Liechtenstein': 'Liechtenstein',
    'Grand Duchy of Luxembourg': 'Luxembourg',
    'Principality of Moldavia': 'Moldavia',
    'Sultanate of Morocco (Alawi dynasty)': 'Alawi Sultanate',
    'Principality of Nassau-Weilburg': 'Nassau-Weilburg',
    ('NIT', 'Italian Republic'): 'Italian Republic (Napoleonic)',
    'Duchy of Oldenburg (grand duchy from 1815)': 'Grand Duchy of Oldenburg',
    'Archbishopric of Salzburg (electorate from 1803)': 'Prince-Archbishopric of Salzburg',
    'Principality of Schaumburg-Lippe': 'Schaumburg-Lippe',
    'Kingdom of Sicily (revolution of 1848–49)': 'Kingdom of Sicily (1848–1849)',
    'Republic of San Marino': 'San Marino',
    'Swiss Confederation (Act of Mediation)': 'Act of Mediation',
    'Principality of Schwarzburg-Rudolstadt': 'Schwarzburg-Rudolstadt',
    'Principality of Wallachia': 'Wallachia',
    'Principality of Waldeck (and Pyrmont)': 'Waldeck and Pyrmont',
    'Duchy of Arenberg-Meppen': 'Duchy of Arenberg',
    'Republic of Valais': 'Rhodanic Republic',
    'Württemberg (duchy, electorate from 1803, kingdom from 1806)': 'Kingdom of Württemberg',
    'Principality of Reuss (younger line)': 'Reuss Junior Line',
    ('DAN', 'Free City of Danzig', 1808): 'Free City of Danzig (Napoleonic)',
    'Free City of Hamburg': 'Free and Hanseatic City of Hamburg',
    'Principality of Monaco': 'Monaco',
    'Landgraviate of Hesse-Homburg': 'Hesse-Homburg',
    'Kingdom of Poland (Congress Poland)': 'Congress Poland',
    'Saxe-Gotha-Altenburg and Saxe-Hildburghausen': 'Saxe-Gotha-Altenburg',
    'Greece (before the kingdom)': 'First Hellenic Republic',
    'Kingdom of Belgium': 'Belgium',
    'United Principalities of Moldavia and Wallachia': 'United Principalities',
    'United Principalities of Romania': 'United Principalities',
    'Cyprus under British administration': 'British Cyprus',
    # ---------- 1900-2026 ----------
    'Vichy France (French State)': 'Vichy France',
    'Liberated France and the Fourth Republic': 'French Fourth Republic',
    'Military dictatorship and Estado Novo': 'Estado Novo (Portugal)',
    'Portuguese Republic': 'Portugal',
    ('NOR', 'Kingdom of Norway'): 'Norway', 'Kingdom of Norway (in union with Sweden)': 'Norway',
    ('ITA', 'Italian Republic'): 'Italy',
    'Republic of Iceland': 'Iceland',
    'Memel Territory': 'Klaipėda Region',
    'Weimar Republic (German Reich)': 'Weimar Republic',
    'Germany (Federal Republic)': 'Germany',
    'West Germany (Federal Republic of Germany)': 'West Germany',
    'East Germany (German Democratic Republic)': 'East Germany',
    'Republic of Austria (First Republic)': 'First Austrian Republic',
    'Republic of Austria': 'Austria',
    'Slovak Republic (1939-45)': 'Slovak Republic (1939–1945)',
    'Regency Kingdom of Poland': 'Kingdom of Poland (1917–1918)',
    'Autonomous Province of Korçë': 'Autonomous Albanian Republic of Korçë',
    'Communist Poland (People\'s Republic)': 'Polish People\'s Republic',
    'Republic of Poland': 'Poland',
    'Czechoslovakia (First Republic)': 'First Czechoslovak Republic',
    'Czechoslovakia (restored, then communist)': [('Third Czechoslovak Republic', 1945, 1947), ('Czechoslovak Socialist Republic', 1948, 1989)],
    'Czech Republic (Czechia)': 'Czech Republic',
    ('SVK', 'Slovak Republic'): 'Slovakia',
    'Hungary after the Habsburgs': 'First Hungarian Republic',
    ('HUN', 'Kingdom of Hungary'): 'Kingdom of Hungary (1920–1946)',
    'Communist Hungary': 'Hungarian People\'s Republic',
    'Republic of Hungary': 'Hungary',
    'Bosnia and Herzegovina, annexed by Austria-Hungary': 'Condominium of Bosnia and Herzegovina',
    'Republic of Bulgaria': 'Bulgaria',
    'Communist Romania': 'Socialist Republic of Romania',
    'Hellenic Republic': 'Greece',
    'Italian Dodecanese (Italian Islands of the Aegean)': 'Italian Islands of the Aegean',
    'Republic of Serbia': 'Serbia',
    'Kingdom of Serbs, Croats and Slovenes': 'Kingdom of Yugoslavia',
    'Socialist Yugoslavia': 'Socialist Federal Republic of Yugoslavia',
    'Republic of Croatia': 'Croatia', 'Republic of Slovenia': 'Slovenia', 'Republic of Kosovo': 'Kosovo',
    ('ALB', 'Albania'): 'Principality of Albania',
    'Communist Albania': 'People\'s Socialist Republic of Albania',
    'Republic of Albania': 'Albania',
    'Republic of Estonia': 'Estonia', 'Republic of Latvia': 'Latvia', 'Republic of Lithuania': 'Lithuania',
    'Soviet Russia (RSFSR)': 'Russian Soviet Federative Socialist Republic',
    'Russian Federation': 'Russia',
    'Republic of Finland': 'Finland',
    'Ukrainian People’s Republic': 'Ukrainian People\'s Republic',
    'Soviet Ukraine': 'Ukrainian Soviet Socialist Republic',
    'Belarusian People’s Republic': 'Belarusian People\'s Republic',
    'Republic of Belarus': 'Belarus',
    'Soviet Belarus': 'Byelorussian Soviet Socialist Republic',
    'Republic of Moldova': 'Moldova',
    ('GEO', 'Georgia'): 'Georgia (country)',
    'Soviet Georgia': 'Georgian Soviet Socialist Republic',
    'Republic of Armenia': 'Armenia',
    'Republic of Azerbaijan': 'Azerbaijan',
    'Soviet Azerbaijan': 'Azerbaijan Soviet Socialist Republic',
    'Transcaucasian Soviet Federation': 'Transcaucasian Socialist Federative Soviet Republic',
    'Republic of Turkey': 'Turkey',
    'Republic of Cyprus': 'Cyprus',
    'French protectorate of Morocco': 'French protectorate in Morocco',
    'Spanish protectorate of Morocco': 'Spanish protectorate in Morocco',
    'Kingdom of Morocco': 'Morocco',
    'Tangier (special status)': 'Tangier International Zone',
    'Republic of Tunisia': 'Tunisia',
    'French mandate for Syria': 'Mandate for Syria and the Lebanon',
    'Lebanon under French mandate': 'Greater Lebanon',
    'British mandate of Iraq': 'Mandatory Iraq',
    'Iran': [('Pahlavi Iran', 1926, 1978), ('Iran', 1979, 2026)],
}
