# A picture and a Wikipedia article for each sample event. (city, year): (Wikipedia article, Commons file, maker,
# date of the picture, what it shows, license). File None: no suitable picture; the city's view stays.
EI = {
 ('cologne', 1164): ('Shrine of the Three Kings', 'Cologne Cathedral Shrine of Magi.jpg', 'Arminia', '2004', 'The Shrine of the Three Kings in Cologne Cathedral, photograph', 'CC BY-SA 3.0'),
 ('cologne', 1248): ('Cologne Cathedral', 'Fassadenplan F vom Kölner Dom.jpg', 'unknown artist', 'about 1370', 'Plan F, the medieval design for the cathedral’s west front, drawing', 'PD'),
 ('cologne', 1288): ('Battle of Worringen', 'Battle of Worringen 1288.PNG', 'unknown artist', '1440s', 'The Battle of Worringen, from a Brabant chronicle', 'PD'),
 ('cologne', 1349): ('Persecution of Jews during the Black Death', 'Doutielt1.jpg', 'Pierart dou Tielt', 'about 1353', 'Miniature from the chronicle of Gilles Li Muisis, Tournai', 'PD'),
 ('cologne', 1388): ('University of Cologne', 'Laurentius de Voltolina 001.jpg', 'Laurentius de Voltolina', 'later 1300s', 'A university lecture in Bologna, miniature', 'PD'),
 ('cologne', 1475): ('Free imperial city', None, '', '', '', ''),
 ('cologne', 1794): ('Roer (department)', None, '', '', '', ''),
 ('cologne', 1815): ('Rhine Province', None, '', '', '', ''),
 ('cologne', 1880): ('Cologne Cathedral', 'Kölner Dom, Historischer Festzug bei Gelegenheit der Dombau-Vollendung am 16. Oktober 1880.jpg', 'unknown artist', 'about 1911', 'The parade for the cathedral’s completion, October 16, 1880, postcard', 'PD'),
 ('cologne', 1918): ('Occupation of the Rhineland', 'The British Army of the Rhine, 1919-1929 Q7211.jpg', 'John Warwick Brooke', '1918', 'British cavalry on duty in Cologne, December 6, 1918, photograph (Imperial War Museums)', 'PD'),
 ('cologne', 1942): ('Bombing of Cologne in World War II', 'Köln-Mülheim, Royal Air Force Bomber Command, 1942-1945 C4748.jpg', 'Royal Air Force', '1942–45', 'Köln-Mülheim from the air after a raid, photograph (Imperial War Museums)', 'PD'),
 ('cologne', 1945): ('Battle of Cologne (1945)', 'Warning sign in cologne.jpg', 'US Army', '1945', 'An American soldier reads a warning sign in Cologne, April 4, 1945, photograph', 'PD'),
 ('cologne', 2009): ('Historial Archive with Rhenish Picture Archive', 'Einsturz historisches Archiv Köln-1.jpg', 'Superbass', '2009', 'A cracked house beside the collapsed archive, March 14, 2009, photograph', 'CC BY-SA 3.0'),
 ('vienna', 1221): ('Leopold VI of Austria', 'Leopold VI, Duke of Austria.jpg', 'unknown artist', '1891', 'Duke Leopold VI, from an illustrated history', 'PD'),
 ('vienna', 1278): ('Battle on the Marchfeld', 'IV László és Rudolf.jpg', 'Mór Than', '1873', 'Ladislaus IV of Hungary and Rudolf of Habsburg meet on the battlefield, painting', 'PD'),
 ('vienna', 1349): ('Black Death', 'Burying Plague Victims of Tournai.jpg', 'unknown artist', '1350s', 'Burying plague victims in Tournai, from the chronicle of Gilles Li Muisis', 'PD'),
 ('vienna', 1365): ('University of Vienna', 'Universität Wien Stiftbrief 1365.jpg', 'Duke Rudolf IV', '1365', 'The university’s founding charter of March 12, 1365 (University Library, Vienna)', 'PD'),
 ('vienna', 1485): ('Siege of Vienna (1485)', 'Matthias Corvinus from a Corvina Codex.jpg', 'Ambrogio de Predis', '1486–90', 'King Matthias Corvinus, from a manuscript of his library', 'PD'),
 ('vienna', 1529): ('Siege of Vienna (1529)', 'Siegeofvienna1529.jpg', 'Bartel Beham', '1529', 'The siege of Vienna, engraving', 'PD'),
 ('vienna', 1679): ('Great Plague of Vienna', 'Plague hospital in Vienna 1679.jpg', 'unknown artist', '1679', 'A plague hospital in Vienna, engraving', 'PD'),
 ('vienna', 1683): ('Battle of Vienna', 'Anonym Entsatz Wien 1683.jpg', 'unknown artist', '1683', 'The siege and relief of Vienna, September 1683, painting (Wien Museum)', 'PD'),
 ('vienna', 1805): ('War of the Third Coalition', 'Napoleon en de sleutels van wenen.jpg', 'Anne-Louis Girodet', '1808', 'Napoleon receives the keys of Vienna, painting', 'PD'),
 ('vienna', 1814): ('Congress of Vienna', 'CongressVienna.jpg', 'Jean-Baptiste Isabey', '1815', 'The Congress of Vienna', 'PD'),
 ('vienna', 1848): ('Revolutions of 1848 in the Austrian Empire', 'Die Barrikade auf dem Michaelerplatz - Anton Ziegler.jpg', 'Anton Ziegler', '1848', 'The barricade on the Michaelerplatz, May 26–27, 1848, painting (Wien Museum; photograph by Yelkrokoyade)', 'CC BY-SA 3.0'),
 ('vienna', 1857): ('Ringstrasse', 'Wien 01 Burgring b.jpg', 'Gugerell', '2013', 'The Burgring, part of the Ringstrasse built in place of the walls, photograph', 'CC0'),
 ('vienna', 1938): ('Anschluss', 'Anschluss Heldenplatz1.jpg', 'Heinrich Hoffmann', '1938', 'Crowds on the Heldenplatz, March 15, 1938, photograph', 'PD'),
 ('vienna', 1945): ('Vienna offensive', 'Brand des Stephansdoms.jpg', 'unknown photographer', '1945', 'St. Stephen’s Cathedral on fire, April 12, 1945, photograph', 'PD'),
 ('vienna', 1955): ('Austrian State Treaty', 'Austria Occupation Zones 1945-55 en.svg', 'Master Uegly and others', '2020', 'The four occupation zones that the treaty ended, map', 'CC BY-SA 4.0'),
 ('paris', 1163): ('Notre-Dame de Paris', 'Notre Dame (La Descente du Saint-Esprit).jpg', 'Jean Fouquet', 'about 1452–60', 'Notre-Dame in a miniature from the Hours of Étienne Chevalier', 'PD'),
 ('paris', 1200): ('University of Paris', 'Meeting of doctors at the university of Paris.jpg', 'Étienne Colaud', '1500s', 'A meeting of doctors at the University of Paris, from the Chants royaux manuscript', 'PD'),
 ('paris', 1348): ('Black Death', 'Burying Plague Victims of Tournai.jpg', 'unknown artist', '1350s', 'Burying plague victims in Tournai, from the chronicle of Gilles Li Muisis', 'PD'),
 ('paris', 1358): ('Étienne Marcel', 'Assassinat marechaux.jpg', 'unknown artist', '1300s', 'The marshals murdered by the Parisians in 1358, from a chronicle', 'PD'),
 ('paris', 1420): ('Treaty of Troyes', 'Ratification du Traité de Troyes 1 - Archives Nationales - AE-III-254.jpg', 'royal chancery', '1420', 'Ratification of the Treaty of Troyes, May 21, 1420 (Archives nationales)', 'PD'),
 ('paris', 1572): ("St. Bartholomew's Day massacre", 'La masacre de San Bartolomé, por François Dubois.jpg', 'François Dubois', 'about 1572–84', 'The St. Bartholomew’s Day massacre, painting', 'PD'),
 ('paris', 1682): ('Palace of Versailles', 'Chateau de Versailles 1668 Pierre Patel.jpg', 'Pierre Patel', '1668', 'The Château de Versailles, painting', 'PD'),
 ('paris', 1789): ('Storming of the Bastille', 'Anonymous - Prise de la Bastille.jpg', 'unknown artist', '1789', 'The storming of the Bastille, painting', 'PD'),
 ('paris', 1832): ('1826–1837 cholera pandemic', 'Le choléra à Paris (5036894480).jpg', 'J. Roze', '1832', 'Cholera in Paris, engraving (National Library of Medicine)', 'PD'),
 ('paris', 1853): ("Haussmann's renovation of Paris", "PISSARRO Camille L'Avenue de l'Opéra Huile sur toile.jpg", 'Camille Pissarro', '1898', 'The Avenue de l’Opéra, one of Haussmann’s new streets, painting', 'PD'),
 ('paris', 1870): ('Siege of Paris (1870–1871)', 'Braun, Adolphe (1811-1877) - Paris, 1871 - St Cloud, La place.jpg', 'Adolphe Braun', '1871', 'Saint-Cloud in ruins after the siege, photograph', 'PD'),
 ('paris', 1871): ('Paris Commune', 'Barricade18March1871 (cropped).jpg', 'unknown photographer', '1871', 'A barricade, March 18, 1871, photograph', 'PD'),
 ('paris', 1889): ('Eiffel Tower', 'Tour Eiffel exposition universelle 1889.jpg', 'Atelier Goupil (?)', '1889', 'The World’s Fair seen from under the Eiffel Tower, photograph', 'PD'),
 ('paris', 1940): ('Paris in World War II', 'Bundesarchiv Bild 101I-129-0480-05A, Paris, Notre Dame, deutsche Soldaten beim Einkauf.jpg', 'Heinz Boesig', '1940', 'German soldiers by Notre-Dame, June 21, 1940, photograph (Bundesarchiv)', 'CC BY-SA 3.0 de'),
 ('paris', 1944): ('Liberation of Paris', 'Crowds of French patriots line the Champs Elysees-edit2.jpg', 'Jack Downey', '1944', 'Crowds on the Champs-Élysées, August 26, 1944, photograph', 'PD'),
 ('paris', 1968): ('May 68', None, '', '', '', ''),
 ('paris', 2019): ('Notre-Dame fire', 'Incendie Notre Dame de Paris.jpg', 'LeLaisserPasserA38', '2019', 'Fire in the roof of Notre-Dame, April 15, 2019, photograph', 'CC BY-SA 4.0'),
 ('istanbul', 1054): ('East–West Schism', 'Great Schism with former borders (1054).png', 'Barrikader', '2010', 'Eastern and western churches after the split, map', 'CC BY-SA 3.0'),
 ('istanbul', 1204): ('Sack of Constantinople', 'Eugène Delacroix - The Entry of the Crusaders into Constantinople - WGA6202.jpg', 'Eugène Delacroix', '1840', 'The Crusaders enter Constantinople, painting (Louvre)', 'PD'),
 ('istanbul', 1261): ('Reconquest of Constantinople', 'Michael VIII Palaiologos.jpg', 'unknown artist', '1300s', 'Emperor Michael VIII, from a manuscript of Pachymeres’s history', 'PD'),
 ('istanbul', 1347): ('Black Death', 'Burying Plague Victims of Tournai.jpg', 'unknown artist', '1350s', 'Burying plague victims in Tournai, from the chronicle of Gilles Li Muisis', 'PD'),
 ('istanbul', 1453): ('Fall of Constantinople', 'Siege of Constantinople fresco, Moldovița monastery, Vatra Moldoviței, 2017.jpg', 'DimiTalen', '2017', 'The siege of Constantinople, fresco of 1537 at Moldovița Monastery, photograph', 'CC0'),
 ('istanbul', 1509): ('1509 Constantinople earthquake', 'Marmara earthquake 1509.jpg', 'unknown artist', '1500s', 'Damage from the 1509 earthquake, woodcut', 'PD'),
 ('istanbul', 1557): ('Süleymaniye Mosque', 'SüleymaniyeMosqueIstanbul (cropped).jpg', 'Hunanuk', '2022', 'The Süleymaniye Mosque, photograph', 'CC0'),
 ('istanbul', 1660): ('Great Fire of 1660', None, '', '', '', ''),
 ('istanbul', 1730): ('Patrona Halil', 'Patrona khalil calkoen.jpeg', 'Jean Baptiste Vanmour', '1730s', 'Patrona Halil, leader of the revolt, painting (Rijksmuseum)', 'PD'),
 ('istanbul', 1826): ('Auspicious Incident', 'Welt-Galleria T085.jpg', 'Christoph Weigel the Elder', '1703', 'A Janissary, engraving', 'PD'),
 ('istanbul', 1894): ('1894 Istanbul earthquake', None, '', '', '', ''),
 ('istanbul', 1908): ('Young Turk Revolution', 'Declaration of the 1908 Revolution in Ottoman Empire.png', 'unknown photographer', '1908', 'Armenian, Greek Orthodox and Muslim leaders celebrate the revolution, photograph, published in Charles Roden Buxton’s Turkey in Revolution (1909)', 'PD'),
 ('istanbul', 1918): ('Occupation of Constantinople', 'Occupation of Constantinople 2.jpg', 'unknown photographer', '1919', 'General Franchet d’Espèrey marching in Beyoğlu, February 8, 1919, photograph', 'PD'),
 ('istanbul', 1923): ('Proclamation of the Republic of Turkey', '1923 11 03 Resimli Gazete Cumhuriyetin Ilani.jpg', 'Resimli Gazete', '1923', 'A newspaper announces the republic, November 3, 1923', 'PD'),
 ('istanbul', 1973): ('Bosphorus Bridge', 'Bosphorus Bridge (1973) in Istanbul.jpg', 'Huseyinakbas63', '2024', 'The Bosphorus Bridge, photograph', 'CC BY 4.0'),
 ('istanbul', 1999): ('1999 İzmit earthquake', 'Izmit eart6.jpg', 'unknown photographer', '1999', 'Damage from the 1999 earthquake, photograph', 'PD'),
}
