"""Descriptions for 1500-1799 (same format as descriptions.py). They come first in the list. Entries for
countries that also exist after 1799 carry year bounds that end by 1799, so they never apply to the later map.
Checked against the introductions of the English, German and Italian Wikipedia articles on each state."""

E = 1799
D15 = [
    # ---------- countries that continue after 1799: their early periods ----------
    ('AUT', None, 1500, 1525, 'Archduchy of Austria and the Habsburg lands', '', '1526',
     'The Alpine lands of the Habsburg family, whose heads were usually elected Holy Roman Emperor. Emperor Maximilian I’s marriage deals brought the family the Netherlands, Spain and, in 1526, the crowns of Bohemia and Hungary.'),
    ('BAD', None, 1500, 1770, 'Margraviates of Baden-Durlach and Baden-Baden', '1535', '1771',
     'Baden was split in 1535 between two lines of its margraves: Protestant Baden-Durlach and Catholic Baden-Baden. When the Baden-Baden line died out in 1771, the two were reunited under Charles Frederick of Baden-Durlach.'),
    ('BAV', None, 1500, 1505, 'Duchies of Bavaria', '1392', '1505',
     'Bavaria was split among branches of the Wittelsbach family, ruling from Munich and Landshut. When the Landshut line died out in 1503, a war of succession followed; it ended in 1505 with Bavaria reunited under Duke Albert IV of Munich.'),
    ('BAV', None, 1506, 1622, 'Duchy of Bavaria', '1506', '1623',
     'Bavaria reunited under the Wittelsbach dukes in Munich, who decreed in 1506 that it would pass undivided to the eldest son. It became a leading Catholic power; Duke Maximilian I led the Catholic League in the Thirty Years’ War.'),
    ('BAV', None, 1623, 1777, 'Electorate of Bavaria', '1623', 'December 30, 1777',
     'Duke Maximilian I was made a prince-elector in 1623, as a reward for helping the emperor crush the Bohemian revolt. The Bavarian line of the Wittelsbachs died out at the end of 1777.'),
    ('BAV', None, 1778, E, 'Electorate of Bavaria (joined with the Palatinate)', 'December 30, 1777', 'January 1, 1806',
     'Charles Theodore, Elector Palatine, inherited Bavaria in 1777, joining the two Wittelsbach lands under one ruler. Austria’s attempt to take part of Bavaria led to the short War of the Bavarian Succession in 1778–79.'),
    ('DEN', None, 1500, 1536, 'Kingdom of Denmark', '', '',
     'The Danish kingdom, which also ruled Norway, Schleswig and Holstein and headed the Kalmar Union with Sweden until Sweden broke away in 1523. After a civil war, the Count’s Feud, Norway was made part of the Danish realm in 1537.'),
    ('ESP', None, 1500, E, 'Kingdom of Spain (Castile and Aragon)', '1479', '',
     'The union of Castile and Aragon under Ferdinand and Isabella, who completed the conquest of Granada in 1492. Under the Habsburg kings (1516–1700) Spain was Europe’s leading power; the War of the Spanish Succession brought the Bourbons to the throne and cost Spain its lands in Italy and the Netherlands.'),
    ('FRA', None, 1500, 1792, 'Kingdom of France', '987', 'September 21, 1792',
     'The French monarchy under the Valois and, from 1589, the Bourbon kings. Under Louis XIV it became Europe’s leading power; the Revolution that began in 1789 brought down the monarchy in 1792.'),
    ('FRA', None, 1793, E, 'French First Republic', 'September 21, 1792', 'May 18, 1804',
     'France became a republic during the Revolution and executed King Louis XVI in 1793. Its armies took Belgium, the left bank of the Rhine and much of Italy; in November 1799 Napoleon Bonaparte seized power.'),
    ('GEN', None, 1500, 1796, 'Republic of Genoa', '1099', 'June 14, 1797',
     'A merchant and banking republic on the Ligurian coast that also ruled Corsica. Admiral Andrea Doria made it an ally of Spain in 1528; it sold its claim to Corsica to France in 1768, and in 1797 French pressure turned it into the Ligurian Republic.'),
    ('GEO', None, 1500, 1761, 'Georgian kingdoms of Kartli and Kakheti', '1460s', '1762',
     'Eastern Georgia, split into the kingdoms of Kartli, around Tbilisi, and Kakheti after the Kingdom of Georgia broke apart in the late 1400s. Both were mostly vassals of Iran; they were united under Heraclius II in 1762.'),
    ('HAN', None, 1500, E, 'Electorate of Hanover (Brunswick-Lüneburg)', '1692', '1806',
     'A north German state of the Welf family, raised to an electorate in 1692. Its elector became King George I of Great Britain in 1714, and the two were ruled by the same king from then on.'),
    ('HDA', None, 1500, E, 'Landgraviate of Hesse-Darmstadt', '1567', '1806',
     'A German state around Darmstadt, formed in 1567 when Landgrave Philip of Hesse’s lands were divided among his four sons. It became the Grand Duchy of Hesse in 1806.'),
    ('LIP', None, 1500, 1788, 'County of Lippe', '', '1789',
     'A small county in Westphalia between the Weser and the Teutoburg Forest, ruled by the House of Lippe from Detmold. It was raised to a principality in 1789.'),
    ('LUX', None, 1500, E, 'Duchy of Luxembourg', '1354', '1795',
     'A duchy of the Habsburg Netherlands with one of Europe’s strongest fortresses. French revolutionary troops took the fortress in June 1795 after a long siege, and France annexed the duchy that October.'),
    ('MAS', None, 1500, E, 'Massa and Carrara', '1473', '1829',
     'A small state on the Tuscan coast, known for its marble quarries, ruled by the Malaspina and then the Cybo-Malaspina families. Its heiress married into the Este family of Modena in 1741.'),
    ('MOD', None, 1500, E, 'Duchy of Modena and Reggio (with Ferrara until 1598)', '1452', '1859',
     'A duchy in the Po valley ruled by the Este family. The pope took Ferrara from them in 1598, and they moved their court to Modena; Napoleon’s army drove out the duke in 1796.'),
    ('MON', None, 1500, E, 'Monaco', '1297', '',
     'A small state on the Riviera ruled by the Grimaldi family, who took the title of prince in 1612. It was under Spanish protection from 1524 and French protection from 1641; France annexed it in 1793.'),
    ('MOR', None, 1500, 1665, 'Morocco (Wattasid and Saadi sultanates)', '1472', '1666',
     'Morocco under the Wattasid sultans of Fez and then the Saadi dynasty, which rose in the south fighting the Portuguese and took Fez in the mid-1500s. The Saadis crushed a Portuguese invasion at the Battle of the Three Kings in 1578; after civil wars, the Alawis took power in the 1660s.'),
    ('NAP', None, 1500, 1503, 'Kingdom of Naples', '1282', '1504',
     'Southern Italy under a branch of the Aragonese royal family. France and Spain agreed in 1500 to divide it, then fought over it; Spain won the whole kingdom in 1503–04.'),
    ('NAS', 'County of Nassau-Saarbrücken', 1500, E, 'Nassau-Saarbrücken', '1381', '1801',
     'A county on the Saar ruled by a branch of the House of Nassau; its count became a prince in 1735. France occupied it in 1793 and annexed it soon after.'),
    ('NEU', None, 1500, 1707, 'Principality of Neuchâtel', '', '1707',
     'A principality allied with the Swiss cantons, ruled by the French Orléans-Longueville family. When that family died out in 1707, Neuchâtel chose King Frederick I of Prussia as its prince.'),
    ('NEU', None, 1708, E, 'Principality of Neuchâtel (under Prussia)', '1707', '1806',
     'From 1707 the King of Prussia was prince of Neuchâtel, ruling through a governor, while the principality kept its alliance with the Swiss cantons. Prussia gave it up to Napoleon in 1806.'),
    ('NLD', None, 1500, 1794, 'Dutch Republic (United Provinces)', 'January 23, 1579', 'January 19, 1795',
     'The seven northern provinces of the Netherlands, which rebelled against Spain and declared independence in 1581; Spain recognized it in 1648. In the 1600s it was a leading sea and trading power; French troops and Dutch Patriots overthrew it in 1795.'),
    ('OLD', None, 1500, E, 'County of Oldenburg (duchy from 1774)', '', '',
     'A county in northwest Germany, home of the House of Oldenburg, which also gave Denmark its kings. Denmark ruled it from 1667 to 1773, when it passed to the Holstein-Gottorp family; it became a duchy in 1774.'),
    ('OTT', None, 1500, E, 'Ottoman Empire', '1299', '1922',
     'The Turkish Muslim empire ruled from Istanbul, which under Selim I and Suleiman the Magnificent conquered Egypt, Syria, most of Hungary and North Africa. Its advance was stopped at Vienna in 1529 and 1683; afterwards it lost Hungary to Austria and the Black Sea coast to Russia.'),
    ('PAP', 'Roman Republic', 1500, E, 'Roman Republic', 'February 15, 1798', 'October 1799',
     'A French sister republic proclaimed in Rome in 1798, after French troops occupied the city and took Pope Pius VI prisoner. Neapolitan troops ended it in 1799.'),
    ('PAP', None, 1500, E, 'Papal States', '756', '1870',
     'Lands in central Italy ruled by the pope, from Rome to Bologna and the Romagna. Pope Julius II brought the Romagna back under papal control in the early 1500s; the papacy added Ferrara in 1598 and Urbino in 1631.'),
    ('PER', 'Persia', 1500, E, 'Safavid Iran', '1501', '1736',
     'Iran under the Safavid dynasty, founded by Shah Ismail I, who made Shia Islam the state religion. It fought long wars with the Ottomans over the Caucasus and Iraq; after an Afghan invasion in 1722, Nader Shah removed the dynasty in 1736.'),
    ('PER', 'Afsharid Empire', 1500, E, 'Afsharid Iran', '1736', '1796',
     'Nader Shah took the throne from the Safavids in 1736 and made Iran a great power again, raiding as far as Delhi. After his murder in 1747 the empire fell apart; the Zand dynasty ruled most of Iran while Nader’s heirs kept only Khorasan.'),
    ('POR', None, 1500, E, 'Kingdom of Portugal', '1139', '1910',
     'An Atlantic kingdom that built a seaborne empire in Africa, Asia and Brazil. From 1580 to 1640 the kings of Spain also held its crown; the Braganza dynasty restored its independence in 1640.'),
    ('RUS', None, 1500, 1546, 'Grand Principality of Moscow (Muscovy)', '', 'January 16, 1547',
     'The Russian state ruled from Moscow, which under Ivan III threw off Tatar overlordship and absorbed Novgorod, Tver and other Russian principalities. In 1547 Ivan IV was crowned the first tsar.'),
    ('RUS', None, 1547, 1720, 'Tsardom of Russia', 'January 16, 1547', 'November 2, 1721',
     'Russia under the tsars, from Ivan the Terrible, who conquered Kazan and Astrakhan, to Peter the Great. The Romanov dynasty came to power in 1613 after the Time of Troubles; Russia spread across Siberia and gained eastern Ukraine in the 1600s.'),
    ('RUS', None, 1721, E, 'Russian Empire', 'November 2, 1721', '1917',
     'Peter the Great proclaimed Russia an empire in 1721 after defeating Sweden, and made St Petersburg its capital. Under Catherine the Great it took the Crimea, the Black Sea coast and much of Poland-Lithuania.'),
    ('SAX', None, 1500, E, 'Electorate of Saxony', '1356', 'December 20, 1806',
     'A major German state ruled by the Wettin family. The elector’s title belonged to the Ernestine branch at Wittenberg, Luther’s protectors, until 1547, when Emperor Charles V gave it to the Albertine branch at Dresden; Elector Augustus the Strong was also King of Poland from 1697.'),
    ('SXO', 'Duchy of Saxony', 1500, E, 'Duchy of Saxony (Ernestine)', '1547', '1572',
     'After losing the Schmalkaldic War in 1547, the Ernestine branch of the Wettins kept only its lands in Thuringia, ruled from Weimar and Gotha. They were later divided into many small Saxon duchies.'),
    ('SUI', None, 1500, 1797, 'Old Swiss Confederacy', '1291', 'April 12, 1798',
     'A loose alliance of self-governing cantons in the Alps, thirteen from 1513, with allies such as the Three Leagues, Valais and Geneva. It broke away from the Holy Roman Empire in practice in 1499 and formally in 1648; the French invasion of 1798 ended it.'),
    ('SWB', None, 1500, 1709, 'County of Schwarzburg (Rudolstadt)', '', '1710',
     'A small county in Thuringia ruled by the counts of Schwarzburg from Rudolstadt; the family’s lands were divided between the Rudolstadt and Sondershausen lines in 1599. Its count was made a prince in 1710.'),
    ('SWE', None, 1500, 1522, 'Sweden (in the Kalmar Union)', '1397', '1523',
     'Sweden, which included Finland, shared a king with Denmark and Norway in the Kalmar Union but was mostly run by its own regents. Gustav Vasa’s revolt ended the union in 1523.'),
    ('SWE', None, 1523, 1610, 'Kingdom of Sweden', 'June 6, 1523', '',
     'Sweden became fully independent under Gustav Vasa, who made it a Lutheran kingdom. It took Estonia in the Livonian War and fought Denmark and Russia for control of the Baltic.'),
    ('SWE', None, 1611, 1721, 'Swedish Empire', '1611', '1721',
     'Sweden’s era as a great power, begun under Gustavus Adolphus, who led the Protestant side in the Thirty Years’ War. It ruled Finland, the eastern Baltic coast and parts of northern Germany until its defeat by Russia in the Great Northern War (1700–21).'),
    ('SWE', None, 1722, E, 'Kingdom of Sweden', '', '',
     'After the Great Northern War Sweden lost its Baltic provinces to Russia but kept Finland and part of Pomerania. Its parliament ruled in the Age of Liberty (1719–72) until Gustav III restored royal power.'),
    ('TUS', None, 1500, 1531, 'Republic of Florence', '1115', '1532',
     'The Florentine city-republic, which ruled most of northern Tuscany, including Pisa. The Medici family, driven out in 1494 and again in 1527, returned with the emperor’s army in 1530, and in 1532 Alessandro de’ Medici was made hereditary duke.'),
    ('TUS', None, 1532, 1568, 'Duchy of Florence', '1532', '1569',
     'Florence became a hereditary Medici duchy in 1532. Duke Cosimo I added Siena in 1557, and the pope made him Grand Duke of Tuscany in 1569.'),
    ('TUS', None, 1569, E, 'Grand Duchy of Tuscany', '1569', '1859',
     'The Medici state in Tuscany, made a grand duchy in 1569. When the Medici died out in 1737, it passed to Francis Stephen of Lorraine, husband of the Habsburg heiress Maria Theresa.'),
    ('VAL', None, 1500, 1797, 'Republic of the Seven Tithings (Valais)', '', '1798',
     'A republic of seven districts in the upper Rhône valley, allied with the Swiss Confederacy, which ruled the French-speaking lower Valais as a subject land. It became part of the Helvetic Republic in 1798.'),
    ('WALD', None, 1500, 1711, 'County of Waldeck', '', '1712',
     'A small county in northern Hesse ruled by its own counts since the 1100s; it gained the County of Pyrmont in 1625. It was raised to a principality in 1712.'),
    ('WRZ', None, 1500, E, 'Prince-Bishopric of Würzburg', '', '1803',
     'A church state in Lower Franconia ruled by the bishops of Würzburg, who also used the title Duke of Franconia. It was dissolved and given to Bavaria in 1803.'),

    # ---------- western Europe ----------
    ('ENG', None, 1500, E, 'Kingdom of England', '927', 'May 1, 1707',
     'The English kingdom, which included Wales and ruled Ireland. From 1603 its kings also ruled Scotland; the two kingdoms were merged into Great Britain in 1707.'),
    ('SCO', None, 1500, E, 'Kingdom of Scotland', '843', 'May 1, 1707',
     'The Scottish kingdom under the Stewart dynasty. King James VI inherited the English crown in 1603, and the Acts of Union merged the two kingdoms into Great Britain in 1707.'),
    ('CMW', 'Isle of Man', 1500, E, 'Isle of Man', '', '',
     'An island in the Irish Sea held by the Stanley family, Earls of Derby, as Lords of Mann under the English crown. It held out for the king until 1651, when Parliament’s forces took it.'),
    ('CMW', None, 1500, E, 'Commonwealth of England (from 1653, of England, Scotland and Ireland)', 'May 19, 1649', 'May 1660',
     'The republic that replaced the monarchy after the execution of Charles I in 1649. Oliver Cromwell conquered Ireland and Scotland and ruled as Lord Protector from 1653; the monarchy was restored under Charles II in 1660.'),
    ('GAE', None, 1500, E, 'Gaelic Irish kingdoms and lordships', '', '1603',
     'Irish kingdoms and lordships such as Desmond, Thomond and Tyrone, ruled by Gaelic families outside the control of the English crown. The Tudor conquest brought them under English rule; the last held out until the end of the Nine Years’ War in 1603.'),
    ('ICC', None, 1500, E, 'Confederate Ireland (Irish Catholic Confederation)', '1642', '1652',
     'A Catholic government based at Kilkenny that controlled most of Ireland after the rebellion of 1641, while declaring loyalty to Charles I. Oliver Cromwell’s conquest of Ireland (1649–53) destroyed it.'),
    ('BRI', None, 1500, E, 'Duchy of Brittany', '939', '1532',
     'A duchy in northwest France with its own dukes and institutions. Its duchess Anne married two French kings in turn, and in 1532 Brittany was formally united with the Kingdom of France.'),
    ('NAV', None, 1500, E, 'Kingdom of Navarre', '824', '1512',
     'A small kingdom in the western Pyrenees ruled by the French house of Albret. Ferdinand of Aragon conquered the part south of the Pyrenees in 1512; the Albret kings kept the northern part, and their heir became King Henry IV of France in 1589.'),
    ('HNL', None, 1500, E, 'Habsburg Netherlands', '1482', '1556',
     'The Low Countries under the Habsburgs, inherited from the dukes of Burgundy in 1482. Emperor Charles V, born in Ghent, bound the Seventeen Provinces together in 1549 and in 1555–56 handed them to his son Philip II of Spain.'),
    ('SNL', None, 1500, E, 'Spanish Netherlands', '1556', '1714',
     'The Low Countries under the Spanish Habsburgs. The northern provinces broke away in the Dutch Revolt; the south, roughly today’s Belgium and Luxembourg, stayed Spanish and lost land to France until it passed to Austria in 1714.'),
    ('ANL', None, 1500, E, 'Austrian Netherlands', '1714', '1795',
     'The southern Netherlands, roughly today’s Belgium and Luxembourg, under the Austrian Habsburgs, who received them from Spain at the end of the War of the Spanish Succession. Revolutionary France conquered them in 1794 and annexed them in 1795.'),
    ('FCO', None, 1500, E, 'Free County of Burgundy (Franche-Comté)', '982', '1678',
     'A Habsburg province between France and Switzerland, ruled from Spain after 1556. Louis XIV conquered it in 1674, and the Treaty of Nijmegen gave it to France in 1678.'),
    ('GEL', None, 1500, E, 'Duchy of Guelders', '1339', '1543',
     'A duchy on the lower Rhine in today’s Netherlands, which long resisted Habsburg rule under Duke Charles of Egmond. Emperor Charles V took it in 1543 and added it to the Habsburg Netherlands.'),
    ('LGE', None, 1500, E, 'Prince-Bishopric of Liège', '980', '1795',
     'A church state in today’s eastern Belgium ruled by the bishops of Liège, separate from the Habsburg Netherlands around it. Its prince-bishop was overthrown in the Liège Revolution of 1789, and France annexed it in 1795.'),
    ('BOU', None, 1500, E, 'Duchy of Bouillon', '1678', '1795',
     'A small duchy in the Ardennes, long disputed between the prince-bishops of Liège and the La Marck and La Tour d’Auvergne families. From 1678 it was a sovereign duchy of the La Tour family under French protection; France annexed it in 1795.'),
    ('ORA', None, 1500, E, 'Principality of Orange', '1163', '1713',
     'A small principality in Provence, surrounded by France and the papal lands around Avignon. From 1544 it belonged to the House of Orange-Nassau, the leading family of the Dutch Republic; France annexed it by the Treaty of Utrecht in 1713.'),
    ('LOR', None, 1500, E, 'Duchy of Lorraine', '959', '1766',
     'A duchy between France and the Holy Roman Empire with its capital at Nancy; France occupied it for long periods in the 1600s. In 1737 it went to Stanisław Leszczyński, the former King of Poland, and at his death in 1766 it passed to France.'),
    ('GVA', None, 1500, E, 'Republic of Geneva', '1534', '1798',
     'A Protestant city-republic that broke free of its bishop and the Duke of Savoy in the 1530s and became John Calvin’s center of the Reformation. An ally of the Swiss cantons, it was annexed by France in 1798.'),
    ('MUL', None, 1500, E, 'Republic of Mulhouse', '1347', '1798',
     'A small Protestant city-republic in southern Alsace, allied with the Swiss Confederacy from 1515 and surrounded by France after 1648. It voted to join France in 1798.'),
    ('GRI', None, 1500, E, 'Free State of the Three Leagues (Grisons)', '1471', '1799',
     'An alliance of three leagues in the Alps of today’s eastern Switzerland, allied with the Swiss Confederacy. From 1512 it ruled the Valtellina; it joined the Helvetic Republic in 1799 and became the Swiss canton of Graubünden in 1803.'),

    # ---------- Italy ----------
    ('VEN', None, 1500, E, 'Republic of Venice', '697', 'May 12, 1797',
     'A merchant republic ruled by a doge and its nobility, holding northeastern Italy, Istria, Dalmatia and islands in the Ionian and Aegean seas. It lost Cyprus (1571) and Crete (1669) to the Ottomans; Napoleon ended it in 1797 and handed Venice to Austria.'),
    ('MLS', None, 1500, E, 'Duchy of Milan (Sforza)', '1450', '1535',
     'The Sforza family ruled Milan from 1450. In the Italian Wars they lost it to France, won it back twice with Swiss and imperial help, and died out in 1535.'),
    ('MIL_F', None, 1500, E, 'Duchy of Milan (under France)', '1499', '1521',
     'King Louis XII of France, who claimed Milan through his Visconti grandmother, drove out Duke Ludovico Sforza in 1499–1500. France held Milan, with a break from 1512 to 1515, until Emperor Charles V’s forces took it in 1521.'),
    ('MIL_S', None, 1500, E, 'Duchy of Milan (under Spain)', '1535', '1706',
     'When the last Sforza duke died in 1535, Emperor Charles V took Milan and gave it to his son, the future Philip II of Spain. It stayed under Spanish rule until Austria took it in 1706.'),
    ('MIL_A', None, 1500, E, 'Duchy of Milan (under Austria)', '1706', '1796',
     'Austria took Milan from Spain in 1706, during the War of the Spanish Succession, and ruled it from Vienna. Napoleon’s army took it in 1796, and it became part of the Cisalpine Republic.'),
    ('NAP_S', None, 1500, E, 'Kingdom of Naples (under Spain)', '1504', '1707',
     'Spain won Naples from France in 1503–04, and for two centuries it was ruled by Spanish viceroys. A revolt led by Masaniello briefly threw off Spanish rule in 1647.'),
    ('NAP_A', None, 1500, E, 'Kingdom of Naples (under Austria)', '1707', '1734',
     'Austrian troops took Naples from Spain in 1707, during the War of the Spanish Succession. In 1734 the Spanish prince Charles of Bourbon conquered it, and it became a separate kingdom under him.'),
    ('SIC_S', None, 1500, E, 'Kingdom of Sicily (under Spain)', '', '1713',
     'The island kingdom under the kings of Aragon and then of Spain, governed by viceroys at Palermo. The Treaty of Utrecht gave it to the Duke of Savoy in 1713.'),
    ('SIC_V', None, 1500, E, 'Kingdom of Sicily (under Savoy)', '1713', '1720',
     'The Treaty of Utrecht gave Sicily to Victor Amadeus II, Duke of Savoy, with the title of king. Spain invaded in 1718, and in 1720 he exchanged Sicily for Sardinia.'),
    ('SIC_A', None, 1500, E, 'Kingdom of Sicily (under Austria)', '1720', '1735',
     'Austria received Sicily from the Duke of Savoy in 1720, in exchange for Sardinia. Charles of Bourbon, the new King of Naples, conquered it in 1734–35.'),
    ('SDA', None, 1500, E, 'Kingdom of Sardinia (under Austria)', '1714', '1720',
     'The island of Sardinia, taken from Spain by Austria in the War of the Spanish Succession. Spain seized it back briefly in 1717; in 1720 it was given to the Duke of Savoy in exchange for Sicily.'),
    ('SAV', None, 1500, E, 'Duchy of Savoy', '1416', '1720',
     'The Alpine state of the House of Savoy, covering Savoy, Piedmont and Nice, with its capital at Turin from 1563. France occupied most of it from 1536 to 1559; in 1713 its duke became King of Sicily, which he exchanged for Sardinia in 1720.'),
    ('SIE', None, 1500, E, 'Republic of Siena', '1125', '1555',
     'A city-republic ruling southern Tuscany, long the rival of Florence. It surrendered in 1555 after a long siege by Spanish and Florentine troops, and in 1557 Spain gave it to Cosimo de’ Medici, except for a strip of coastal forts.'),
    ('MAN', None, 1500, E, 'Mantua (duchy from 1530)', '1328', '1708',
     'A state in Lombardy ruled by the Gonzaga family, whose court was a center of Renaissance art and music; it became a duchy in 1530 and gained Montferrat in the 1530s. The last Gonzaga duke sided with France in the War of the Spanish Succession, and Austria took Mantua in 1708.'),
    ('MIR', None, 1500, E, 'Mirandola', '1310', '1711',
     'A small state near Modena ruled by the Pico family, known for the Renaissance thinker Giovanni Pico della Mirandola. Its last duke sided with France in the War of the Spanish Succession; the emperor took the duchy from him and sold it to Modena in 1711.'),
    ('GUA', None, 1500, E, 'Guastalla (duchy from 1621)', '1428', '1748',
     'A small state on the Po in northern Italy, held from 1539 by a branch of the Gonzaga family and made a duchy in 1621. After its last duke died in 1746, it passed to the Duchy of Parma in 1748.'),
    ('NOV', None, 1500, E, 'County of Novellara and Bagnolo', '1501', '1737',
     'A small imperial fief in Emilia ruled by a branch of the Gonzaga family. When that line died out in 1728, it passed to the Duchy of Modena, which took possession in 1737.'),
    ('SLZ', None, 1500, E, 'Marquisate of Saluzzo', '', '1548',
     'A small Alpine marquisate in Piedmont, long under French protection. France annexed it in 1548; Savoy seized it in 1588 and kept it under the Treaty of Lyon in 1601.'),
    ('ITM', None, 1500, E, 'County of Sovana (Pitigliano)', '1274', '',
     'A small fief of the Orsini family in southern Tuscany, centered on Pitigliano and Sorano and outside the rule of Siena and Florence. It passed to the Medici grand dukes of Tuscany in the first half of the 1600s.'),
    ('NOL', None, 1500, E, 'Republic of Noli', '1192', '1797',
     'A tiny seafaring republic on the Ligurian coast, allied with and protected by Genoa. It ended in 1797, when Genoa became the French-backed Ligurian Republic.'),
    ('COR', None, 1500, E, 'Corsican Republic', '1755', '1769',
     'An independent state proclaimed by Pasquale Paoli during Corsica’s revolt against Genoese rule. Genoa sold its claim to the island to France in 1768, and French troops conquered it in 1769.'),
    ('MLT', None, 1500, E, 'Knights of St John (Knights Hospitaller)', '1310', '1798',
     'A crusading order of knights that ruled Rhodes from 1310 until the Ottomans took it in 1522. Emperor Charles V gave them Malta in 1530, where they held off a great Ottoman siege in 1565; Napoleon took the island in 1798.'),
    ('ARC', None, 1500, E, 'Duchy of the Archipelago (Naxos)', '1207', '1579',
     'A duchy in the Cyclades islands centered on Naxos, founded by Venetian nobles after the Fourth Crusade. It paid tribute to the Ottomans from 1537; the sultan removed its last duke in 1566 and annexed it outright in 1579.'),

    # ---------- Holy Roman Empire ----------
    ('BOK', None, 1500, E, 'Kingdom of Bohemia', '1198', '1526',
     'A kingdom of the Holy Roman Empire whose king was a prince-elector; it included Moravia, Silesia and Lusatia. It was ruled by the Jagiellonian dynasty until 1526, when King Louis II was killed fighting the Ottomans at Mohács and the crown passed to Ferdinand of Habsburg.'),
    ('BRA', None, 1500, E, 'Margraviate of Brandenburg', '1157', '1806',
     'The Hohenzollern electorate around Berlin, whose margrave was one of the prince-electors. It inherited the Duchy of Prussia in 1618; from 1701 its elector was also King in Prussia, and Brandenburg became the core of the Prussian kingdom.'),
    ('PAL', None, 1500, E, 'Electoral Palatinate', '', '1803',
     'A Rhineland state around Heidelberg and Mannheim ruled by a branch of the Wittelsbach family, whose head, the Elector Palatine, led the Protestant princes in the 1500s and 1600s. Elector Frederick V’s acceptance of the Bohemian crown in 1619 helped start the Thirty Years’ War; in 1777 the Palatinate was joined with Bavaria.'),
    ('JUL', None, 1500, 1520, 'Duchies of Jülich-Berg and Cleves-Mark', '', '1521',
     'Two pairs of duchies on the lower Rhine: Jülich and Berg, and Cleves and Mark. They were joined in 1521 through the marriage of John III of Cleves to the heiress of Jülich-Berg.'),
    ('JUL', None, 1521, E, 'United Duchies of Jülich-Cleves-Berg', '1521', '1614',
     'A union of the duchies of Jülich, Cleves and Berg and the counties of Mark and Ravensberg on the lower Rhine. When its last duke died in 1609 a succession dispute followed, and in 1614 the lands were split between Brandenburg and Palatinate-Neuburg.'),
    ('POM', None, 1500, E, 'Duchy of Pomerania', '1121', '1637',
     'A duchy on the Baltic coast ruled by the Griffin dynasty, united under Bogislaw X from 1478. It was split in 1532 into Pomerania-Wolgast and Pomerania-Stettin; after the last duke died in 1637, Sweden and Brandenburg divided it.'),
    ('KOL', None, 1500, E, 'Electorate of Cologne', '', '1803',
     'A church state on the Rhine ruled by the Archbishop of Cologne, one of the three church prince-electors; its capital was Bonn, since the city of Cologne governed itself. France occupied its lands west of the Rhine in 1794, and it was dissolved in 1803.'),
    ('MAI', None, 1500, E, 'Electorate of Mainz', '', '1803',
     'A church state ruled by the Archbishop of Mainz, the highest-ranking of the seven prince-electors and chancellor of the empire. France took its lands west of the Rhine in the 1790s, and it was dissolved in 1803.'),
    ('TRR', None, 1500, E, 'Electorate of Trier', '', '1803',
     'A church state on the Moselle ruled by the Archbishop of Trier, one of the three church prince-electors; from the 1500s the electors lived mostly at Koblenz. France took it in 1794, and it was dissolved in 1803.'),
    ('MUN', None, 1500, E, 'Prince-Bishopric of Münster', '', '1802',
     'The largest church state in northwest Germany, ruled by the bishops of Münster. Part of the Peace of Westphalia that ended the Thirty Years’ War was signed in its capital in 1648; it was dissolved in 1802–03.'),
    ('BAM', None, 1500, E, 'Prince-Bishopric of Bamberg', '1245', '1802',
     'A church state in Franconia ruled by the bishops of Bamberg, whose diocese dated from 1007. It was dissolved and given to Bavaria in 1802.'),
    ('ANH', 'Principality of Anhalt-Zerbst', 1500, E, 'Principality of Anhalt-Zerbst', '1603', '1796',
     'A small principality in central Germany ruled from Zerbst by a branch of the House of Ascania; Catherine the Great of Russia was born into this family. When its line died out in 1793, its lands were divided among the other Anhalt states.'),
    ('HGE', None, 1500, E, 'County of Hohengeroldseck', '', '1819',
     'A tiny county in the Black Forest, held from the early 1700s by the von der Leyen family. Napoleon made it the Principality of von der Leyen in 1806; it passed to Baden in 1819.'),
    ('HGO', None, 1500, E, 'Duchy of Schleswig-Holstein-Gottorp', '1544', '1773',
     'The share of Schleswig and Holstein held by the dukes of Gottorp, a younger branch of the Danish royal family. Denmark took the duke’s part of Schleswig in 1713, and in 1773 the family’s heir, Grand Duke Paul of Russia, traded Holstein for Oldenburg.'),
    ('DIT', None, 1500, E, 'Peasant Republic of Dithmarschen', '', '1559',
     'A self-governing farmers’ republic on the North Sea coast of Holstein, which defeated a Danish army at Hemmingstedt in 1500. Denmark and the dukes of Holstein finally conquered it in 1559.'),
    ('EFR', None, 1500, E, 'East Frisia (principality from 1654)', '1464', '1744',
     'A state on the North Sea coast ruled by the Cirksena family, first from Emden and later from Aurich; it became a principality in 1654. When the Cirksena line died out in 1744, Prussia took it over.'),

    # ---------- eastern Europe ----------
    ('HUK', None, 1500, E, 'Kingdom of Hungary', '1000', '1526',
     'A large kingdom in the Carpathian Basin that also ruled Croatia, under the Jagiellonian kings from 1490. The Ottomans crushed its army at Mohács in August 1526, where King Louis II was killed.'),
    ('TRS', None, 1500, E, 'Eastern Hungarian Kingdom and Principality of Transylvania', '1526', '1711',
     'After Mohács, John Zápolya and his son ruled eastern Hungary as Ottoman vassals and rivals to the Habsburg kings; from 1570 it was the Principality of Transylvania, ruled by elected Hungarian princes. The Habsburgs took control in 1687–91.'),
    ('UHU', None, 1500, E, 'Principality of Upper Hungary', '1682', '1685',
     'A short-lived Ottoman vassal state in today’s Slovakia and northeastern Hungary, led by Imre Thököly, who had rebelled against the Habsburgs. It collapsed when the Ottoman war went badly after the failed siege of Vienna in 1683.'),
    ('PLK', None, 1500, E, 'Kingdom of Poland', '1025', '1569',
     'The Polish kingdom under the Jagiellonian dynasty, whose kings were also grand dukes of Lithuania. In 1569 the Union of Lublin turned the two into a single commonwealth.'),
    ('LIT', None, 1500, E, 'Grand Duchy of Lithuania', '', '1569',
     'A vast state covering today’s Lithuania, Belarus and much of Ukraine, ruled by the Jagiellonian dynasty together with Poland. In 1569 the Union of Lublin merged it with Poland into the Polish–Lithuanian Commonwealth, and its Ukrainian lands passed to the Polish crown.'),
    ('PLC', None, 1500, E, 'Polish–Lithuanian Commonwealth', 'July 1, 1569', '1795',
     'A union of the Kingdom of Poland and the Grand Duchy of Lithuania with an elected king and a powerful parliament of nobles, created by the Union of Lublin in 1569. One of Europe’s largest states in the 1600s, it was divided among Russia, Prussia and Austria in three partitions (1772, 1793, 1795).'),
    ('DPR', None, 1500, E, 'Duchy of Prussia', '1525', '1701',
     'The Prussian lands of the Teutonic Order, turned into a Lutheran duchy in 1525 by the last grand master, Albert of Hohenzollern, under Polish overlordship. Brandenburg’s electors inherited it in 1618 and won full sovereignty in 1657; it became the Kingdom of Prussia in 1701.'),
    ('TEU', None, 1500, E, 'State of the Teutonic Order', '1230', '1561',
     'A crusader state of German knights on the Baltic coast. Its Prussian lands became a Lutheran duchy in 1525; its Livonian branch, the Livonian Order, lasted until the Livonian War of 1558–61.'),
    ('LIV', 'Archbishopric of Riga', 1500, E, 'Archbishopric of Riga', '1186', '1561',
     'A church state in today’s Latvia ruled by the Archbishop of Riga, a member of the Livonian Confederation. It was dissolved during the Livonian War, and its lands passed to Poland-Lithuania.'),
    ('LIV', 'Bishopric of Courland', 1500, E, 'Bishopric of Courland', '1234', '1585',
     'A small church state in western Courland. Its bishop sold it to Denmark in 1559, and the Danish king’s brother Magnus ruled it; Denmark sold it to Poland-Lithuania in 1585.'),
    ('LIV', None, 1500, E, 'Livonian Confederation', '1435', '1561',
     'A loose union of the Livonian Order and the church states of Livonia, covering today’s Estonia and Latvia. It broke apart in the Livonian War after Russia invaded in 1558; its lands were divided among Sweden, Poland-Lithuania and Denmark.'),
    ('CRL', None, 1500, E, 'Duchy of Courland and Semigallia', '1561', '1795',
     'A duchy in today’s western Latvia, created in 1561 when the Livonian Order was dissolved; its last master, Gotthard Kettler, became duke under Lithuanian and later Polish-Lithuanian overlordship. Russia annexed it in 1795.'),
    ('PSK', None, 1500, E, 'Pskov Republic', '1348', '1510',
     'A self-governing merchant city-state in northwest Russia, under the protection of Moscow from 1399. Grand Prince Vasily III annexed it in 1510.'),
    ('RYA', None, 1500, E, 'Principality of Ryazan', '1129', '1521',
     'A Russian principality southeast of Moscow, the last to keep its formal independence. Vasily III of Moscow annexed it in 1521.'),
    ('QAS', None, 1500, E, 'Qasim Khanate', '1452', '1681',
     'A small Tatar khanate on the Oka River, set up by Moscow in 1452 for a Tatar prince in its service. It depended on Moscow throughout and was abolished in 1681.'),
    ('KZN', None, 1500, E, 'Khanate of Kazan', '1438', '1552',
     'A Tatar khanate on the middle Volga, one of the states that broke away from the Golden Horde. Ivan the Terrible of Russia conquered it in 1552.'),
    ('AST', None, 1500, E, 'Khanate of Astrakhan', '1460s', '1556',
     'A Tatar khanate on the lower Volga and its delta, one of the states that broke away from the Golden Horde. Ivan the Terrible of Russia conquered it in 1556.'),
    ('GHO', None, 1500, E, 'Great Horde', '1460s', '1502',
     'The last remnant of the Golden Horde, centered on the lower Volga. The Crimean Khanate destroyed it in 1502.'),
    ('NOG', None, 1500, E, 'Nogai Horde', '', '',
     'A confederation of Turkic nomads on the steppe north of the Caspian Sea. In the 1600s the Kalmyks pushed it west across the Volga, and many Nogais came under Crimean or Russian rule.'),
    ('KLM', None, 1500, E, 'Kalmyk Khanate', '1630', '1771',
     'A state of the Kalmyks, Mongol herders who moved west from Central Asia to the lower Volga in the early 1600s. It was an ally and later a dependency of Russia; after many Kalmyks left for China in 1771, Catherine the Great abolished the khanate.'),
    ('CRI', None, 1500, E, 'Crimean Khanate', '1441', '1783',
     'A Crimean Tatar state ruled by the Giray dynasty, a vassal of the Ottoman Empire from 1475. Its horsemen raided Poland-Lithuania and Russia for centuries; Russia made it independent of the Ottomans in 1774 and annexed it in 1783.'),
    ('CRI_I', None, 1500, E, 'Crimean Khanate (independent)', 'July 21, 1774', 'April 19, 1783',
     'The Treaty of Küçük Kaynarca, which ended the Russo-Turkish War of 1768–74, made the Crimean Khanate independent of the Ottomans. In practice it fell under Russian control, and Catherine the Great annexed it in 1783.'),
    ('ZAP', None, 1500, E, 'Zaporozhian Host', '1550s', '1775',
     'A self-governing community of Cossacks on the lower Dnieper, centered on a fortified camp called the Sich. Its revolt of 1648 created the Cossack Hetmanate; the Sich later came under Russian rule, and Catherine the Great destroyed it in 1775.'),

    # ---------- Caucasus, Middle East and North Africa ----------
    ('CAU', None, 1500, E, 'Peoples of the North Caucasus', '', '',
     'Circassians, Kabardians, Chechens, the khanates of Dagestan and other mountain peoples of the Caucasus, mostly outside the direct rule of the empires around them. The Russian Empire conquered them in wars that lasted until the 1860s.'),
    ('IME', None, 1500, E, 'Kingdom of Imereti', '1463', '1810',
     'A kingdom in western Georgia, formed when the Kingdom of Georgia broke apart in the 1460s. It was often under Ottoman overlordship; Russia annexed it in 1810.'),
    ('SHI', None, 1500, E, 'Kingdom of Shirvan', '861', '1538',
     'A kingdom in today’s Azerbaijan, around Shamakhi and Baku, ruled by the Shirvanshahs for more than six centuries. It was often a vassal of Iran, which annexed it in 1538.'),
    ('AQQ', None, 1500, E, 'Aq Qoyunlu (White Sheep Turkomans)', '1378', '1508',
     'A Turkoman tribal confederation that ruled eastern Anatolia, Armenia, Azerbaijan and much of Iran. Weakened by civil war, it was destroyed by the rising Safavids of Iran between 1501 and 1508.'),
    ('MAM', None, 1500, E, 'Mamluk Sultanate', '1250', '1517',
     'A state ruled from Cairo by a class of soldiers who had been bought as slaves, covering Egypt, Syria and western Arabia. The Ottomans conquered it in 1516–17.'),
    ('HAF', None, 1500, E, 'Hafsid Sultanate of Tunis', '1229', '1574',
     'A Berber dynasty that ruled Tunisia and eastern Algeria from Tunis. By the 1500s it was caught between Spain and the Ottomans, who took Tunis for good in 1574.'),
    ('TLM', None, 1500, E, 'Kingdom of Tlemcen', '1236', '1554',
     'A Berber kingdom in western Algeria, squeezed in the 1500s between Spain, which held Oran, and the Ottomans of Algiers. The Ottomans annexed it in 1554.'),
]
