"""Descriptions for 1000-1499 (same format as descriptions.py: unit, record name or None, first year, last year, title,
from, to, text). They come first in the list. Entries for countries that also exist after 1499 end by 1499, so they
never apply to the later maps. Written from the standard histories and the introductions of the Wikipedia articles on
each state; dates are given as years where the day is uncertain or the change was gradual."""

E = 1499
D10 = [
    # ---------- the British Isles ----------
    ('ENG', None, 1000, 1015, 'Kingdom of England', '927', 'May 1, 1707',
     'The Anglo-Saxon kingdom united under the house of Wessex in the 10th century. Under Æthelred the Unready it faced renewed Danish invasions, and the Danish king Sweyn Forkbeard briefly took the throne in 1013.'),
    ('ENG', None, 1016, 1065, 'Kingdom of England', '927', 'May 1, 1707',
     'Cnut the Great of Denmark ruled England from 1016; after his sons died, the house of Wessex returned under Edward the Confessor (1042–66). Edward died without an heir in January 1066, which led to the Norman Conquest.'),
    ('ENG', None, 1066, 1153, 'Kingdom of England', '927', 'May 1, 1707',
     'William, Duke of Normandy, conquered England after the Battle of Hastings in October 1066 and replaced the Anglo-Saxon nobility with a Norman one. After Henry I died in 1135, a civil war over the succession, the Anarchy, lasted until 1153.'),
    ('ENG', None, 1154, 1336, 'Kingdom of England', '927', 'May 1, 1707',
     'Henry II, the first Plantagenet king, ruled England together with half of France, which he held as the French king’s vassal. His son John lost Normandy and Anjou in 1204; Edward I (1272–1307) conquered Wales and fought to subdue Scotland.'),
    ('ENG', None, 1337, E, 'Kingdom of England', '927', 'May 1, 1707',
     'Edward III claimed the French crown in 1337, starting the Hundred Years’ War; English kings held Gascony, Calais and, after Henry V’s victories, much of northern France until 1453. A civil war between the houses of Lancaster and York, the Wars of the Roses, ended with the Tudor Henry VII in 1485.'),
    ('NSE', None, None, None, 'North Sea Empire of Cnut', '1016', '1042',
     'The personal union of England, Denmark and, from 1028, Norway under the Danish king Cnut the Great, who conquered England in 1016. It broke up after his death in 1035; his son Harthacnut held England and Denmark until 1042.'),
    ('SCO', None, 1000, E, 'Kingdom of Scotland', '843', 'May 1, 1707',
     'The kingdom of Alba, formed from the union of the Picts and the Scots, which took Lothian and Strathclyde in the 11th century. It fought off English conquest in the Wars of Independence (1296–1357), winning under Robert the Bruce at Bannockburn in 1314.'),
    ('STR', None, None, None, 'Kingdom of Strathclyde', '870s', '1030s',
     'A Brittonic kingdom around the River Clyde, successor to the kingdom of Dumbarton. It was absorbed into the Kingdom of Scotland in the early 11th century.'),
    ('GLW', None, None, None, 'Lordship of Galloway', '10th century', '1234',
     'A Gaelic-Norse lordship in southwest Scotland whose rulers were at times called kings. Its last lord, Alan, died in 1234, and it was absorbed into the Kingdom of Scotland.'),
    ('KIS', None, None, None, 'Kingdom of the Isles', '9th century', '1266',
     'A Norse-Gaelic kingdom of the Hebrides and the Isle of Man, under the nominal overlordship of Norway. By the Treaty of Perth (1266), Norway ceded the islands to Scotland.'),
    ('ORK', None, None, None, 'Earldom of Orkney', '9th century', '1472',
     'A Norse earldom of the Orkney and, until 1195, Shetland Islands, held from the Norwegian crown. The Danish-Norwegian king pledged the islands to Scotland in 1468–69 as security for his daughter’s dowry, and Scotland annexed them in 1472.'),
    ('DUB', None, None, None, 'Norse Kingdom of Dublin', '853', '1170',
     'A Norse-Gaelic kingdom around the Viking town of Dublin, often subject to Irish high kings. Anglo-Norman invaders took Dublin in 1170, and Henry II made it the center of his Lordship of Ireland.'),
    ('GAE', None, 1000, 1170, 'Gaelic Irish kingdoms', '', '',
     'Ireland was divided among Gaelic kingdoms, such as Munster, Leinster, Connacht, Ulster and Meath, whose kings competed for the title of High King. Brian Boru, king of Munster, came closest to ruling all of Ireland before his death at Clontarf in 1014.'),
    ('GAE', None, 1171, E, 'Gaelic Irish kingdoms', '', '',
     'After the Anglo-Norman invasion of 1169–71, Gaelic kings and lords kept much of the north and west of Ireland. By the 15th century English rule had shrunk to the Pale around Dublin, and Gaelic lordships held most of the island again.'),
    ('LIR', None, None, None, 'Lordship of Ireland', '1171', '1542',
     'The part of Ireland under the English crown after Henry II’s expedition of 1171, governed from Dublin. English control was widest in the 13th century and had shrunk to the Pale by 1500; Henry VIII made it the Kingdom of Ireland in 1542.'),
    ('GWY', None, None, None, 'Kingdom of Gwynedd', '5th century', '1283',
     'A Welsh kingdom in the northwest, centered on Snowdonia and Anglesey. Its princes Llywelyn the Great and Llywelyn ap Gruffudd led most of Wales in the 13th century, until Edward I of England conquered it in 1282–83.'),
    ('POW', None, None, None, 'Kingdom of Powys', '5th century', '1283',
     'A Welsh kingdom in the east of Wales, bordering England. It split in 1160 into northern Powys Fadog and southern Powys Wenwynwyn, which came under English rule by 1283.'),
    ('DEH', None, None, None, 'Kingdom of Deheubarth', '920s', '1197',
     'A kingdom of southwest Wales formed by Hywel Dda. Its last great ruler, the Lord Rhys, died in 1197; it then broke up among his sons and fell to Gwynedd and the Anglo-Norman lords.'),
    ('MRG', None, None, None, 'Kingdom of Morgannwg', '10th century', '1090s',
     'A kingdom in southeast Wales (Glamorgan), also called Glywysing. Norman lords conquered it in the 1090s.'),
    ('BRY', None, None, None, 'Kingdom of Brycheiniog', '5th century', '1093',
     'A small kingdom in south Wales, around Brecon. It came under Deheubarth in the 11th century and fell to the Norman lord Bernard de Neufmarché in 1093.'),
    ('WLS', None, None, None, 'Welsh kingdoms', '', '',
     'Smaller Welsh kingdoms and border districts, such as the land between the Wye and the Severn. The Normans conquered most of them by 1100.'),
    # ---------- Scandinavia ----------
    ('DEN', None, 1000, 1396, 'Kingdom of Denmark', '', '',
     'The Danish kingdom, which included Scania in today’s southern Sweden. Its kings ruled England under Cnut (1016–35) and conquered northern Estonia in 1219; under Margaret I, Norway (1380) and Sweden (1397) were joined to it.'),
    ('DEN', None, 1397, E, 'Denmark–Norway (Kalmar Union)', '1397', '1523',
     'The union of Denmark, Norway and Sweden under one king, agreed at Kalmar in 1397 under Queen Margaret I. Denmark led it, and Norway was ruled from Copenhagen; Sweden often had its own regents and left the union for good in 1523.'),
    ('NOR', None, 1000, 1396, 'Kingdom of Norway', '872', '1397',
     'The kingdom united by Harald Fairhair and converted to Christianity by Olaf II (died 1030). It ruled Iceland, Greenland, the Faroes, Orkney and Shetland, and joined Denmark in a personal union in 1380.'),
    ('SWE', None, 1000, 1396, 'Kingdom of Sweden', '', '',
     'The kingdom of the Swedes and the Götar, Christian from the 11th and 12th centuries, which conquered Finland from the 12th century on. It was often torn by struggles between rival royal families.'),
    ('SWE', None, 1397, E, 'Sweden (in the Kalmar Union)', '1397', '1523',
     'Sweden joined Denmark and Norway in the Kalmar Union in 1397 but resented Danish rule; in the 15th century it was mostly governed by its own regents, the Stures. It left the union for good in 1523.'),
    ('ISL', None, 1000, 1261, 'Icelandic Commonwealth', '930', '1262',
     'A free state with no king, run by chieftains who met each year at the Althing. Civil strife in the 13th century ended when the Icelanders submitted to the king of Norway in 1262–64.'),
    ('JAM', None, None, None, 'Jämtland', '', '1178',
     'A peasant community between Norway and Sweden with its own assembly, the Jamtamót. Norway took control of it around 1178.'),
    # ---------- France ----------
    ('FRA', None, 1000, 1327, 'Kingdom of France', '987', 'September 21, 1792',
     'The kingdom of the Capetian kings, who at first ruled directly only a small domain around Paris and Orléans; the great dukes and counts owed them homage but acted on their own. Philip II Augustus (1180–1223) took Normandy and Anjou from the English king, and royal power grew steadily after him.'),
    ('FRA', None, 1328, E, 'Kingdom of France', '987', 'September 21, 1792',
     'Under the Valois kings, from 1328, France fought the Hundred Years’ War with England, which held large parts of the country until Charles VII drove it out by 1453. Louis XI (1461–83) took Burgundy, Anjou and Provence, and Charles VIII married the heiress of Brittany in 1491.'),
    ('NMD', None, None, None, 'Duchy of Normandy', '911', '1204',
     'A duchy founded in 911, when the French king granted land at the mouth of the Seine to the Viking leader Rollo. Its dukes owed homage to the French king but were powerful in their own right; Duke William conquered England in 1066.'),
    ('NMD_E', None, None, None, 'Duchy of Normandy (held by the kings of England)', '911', '1204',
     'From 1066 the dukes of Normandy were also kings of England, but they held Normandy as vassals of the French king. Philip II of France confiscated it from King John and conquered it in 1204.'),
    ('AQU', None, None, None, 'Duchy of Aquitaine', '9th century', '1453',
     'A large duchy in southwest France held by the counts of Poitou, who also gained Gascony in the 1050s. Its heiress Eleanor married Louis VII of France and then, in 1152, Henry Plantagenet, the future Henry II of England.'),
    ('AQU_E', None, None, None, 'Duchy of Aquitaine (held by the kings of England)', '9th century', '1453',
     'The kings of England held Aquitaine as dukes, owing homage to the French king, from Henry II’s marriage to Eleanor in 1152. After French conquests, by the 13th century only Gascony, around Bordeaux, was left.'),
    ('ANJ', None, None, None, 'County of Anjou', '10th century', '1480',
     'A county on the lower Loire whose counts, the Angevins, took Maine and Touraine; Count Geoffrey conquered Normandy in 1144. Later Anjou went to younger sons of the French royal house, the Angevin kings of Naples and, from 1360, the Valois dukes of Anjou, until Louis XI took it in 1480.'),
    ('ANJ_E', None, None, None, 'Angevin lands in France', '1152', '1204',
     'Anjou, Maine and Touraine, the home counties of the Plantagenet (Angevin) kings of England. With Normandy and Aquitaine they made up half of France, held from the French king; Philip II conquered them from King John in 1203–05.'),
    ('MAE', None, None, None, 'County of Maine', '10th century', '1110',
     'A county between Normandy and Anjou, fought over by both; its counts owed homage to the French king. It passed to the counts of Anjou in 1110.'),
    ('BUR', None, None, None, 'Duchy of Burgundy', '918', '1363',
     'A duchy in eastern France ruled by a branch of the Capetian royal family from 1032. When its last duke died in 1361 the French king took it, and in 1363 gave it to his son Philip the Bold.'),
    ('BGS', None, None, None, 'Burgundian State', '1363', '1482',
     'The lands of the Valois dukes of Burgundy, who from 1363 gathered Burgundy, Flanders, Artois, Brabant, Holland and more, partly in France and partly in the Empire. After Duke Charles the Bold fell in battle in 1477, France took the Duchy of Burgundy, and the Low Countries passed to the Habsburgs through his daughter Mary.'),
    ('FLA', None, None, None, 'County of Flanders', '862', '1384',
     'A wealthy county of cloth-making towns such as Bruges, Ghent and Ypres, held from the French king. It passed to the dukes of Burgundy in 1384.'),
    ('CHA', None, None, None, 'County of Champagne', '10th century', '1284',
     'A county east of Paris, famous for its trade fairs, held by the counts of Blois-Champagne. It came to the French crown through Philip IV’s marriage to its heiress in 1284 and was formally annexed in 1314.'),
    ('BLO', None, None, None, 'County of Blois', '10th century', '1397',
     'A county on the Loire whose counts also held Champagne and Chartres in the 11th and 12th centuries. It was sold to Louis of Orléans, the French king’s brother, in 1391 and passed to him in 1397.'),
    ('TOU', None, None, None, 'County of Toulouse', '9th century', '1271',
     'A large county in southern France. After the Albigensian Crusade it passed to the French royal house through the marriage of its heiress, and it was annexed in 1271.'),
    ('VRM', None, None, None, 'County of Vermandois', '9th century', '1213',
     'A county in northern France around Saint-Quentin, held by a branch of the Carolingians and then of the Capetians. It passed to the French crown in 1213.'),
    ('ARG', None, None, None, 'County of Armagnac', '960', '1473',
     'A county in Gascony whose counts led the Armagnac faction in the French civil war of the early 15th century. Louis XI crushed the last count in 1473.'),
    ('FOX', None, None, None, 'Foix and Béarn', '1010', '1607',
     'The Pyrenean County of Foix, joined with the viscountcy of Béarn in 1290; Béarn’s rulers claimed it as sovereign, owing homage to no one. From 1484 both belonged to the Albret family, kings of Navarre.'),
    ('BOB', None, None, None, 'Duchy of Bourbon', '1327', '1527',
     'A duchy in central France created in 1327 for a branch of the royal family, which gathered the Bourbonnais, Auvergne, Forez and Beaujolais. The French crown confiscated it from Constable Charles of Bourbon in 1527.'),
    ('BRI', None, 1000, E, 'Duchy of Brittany', '939', '1532',
     'A Breton duchy in the northwest of France which owed homage to the French king but kept its own laws and was often allied with England. Its heiress Anne married two French kings, Charles VIII (1491) and Louis XII (1499), and Brittany was joined to France in 1532.'),
    # ---------- the Kingdom of Arles and the western Empire ----------
    ('ARL', None, None, None, 'Kingdom of Arles (Burgundy)', '933', '1378',
     'The Kingdom of Burgundy, formed in 933, passed to the Holy Roman Emperors in 1032. Its lands, from Provence to Franche-Comté, came to be ruled by local counts and the title faded; Emperor Charles IV was the last to be crowned its king, in 1365.'),
    ('PRV', None, None, None, 'County of Provence', '10th century', '1481',
     'A county of the Empire between the Rhône and the Alps, held from 1246 by Charles of Anjou, brother of the French king, and his heirs, the Angevin kings of Naples. On the death of its last count in 1481 it passed to the French crown.'),
    ('DAU', None, None, None, 'Dauphiné of Viennois', '12th century', '1349',
     'A land of the Empire around Grenoble whose rulers took the title of dauphin. The last dauphin, Humbert II, sold it to the French king in 1349, and the title passed to the heir to the French throne.'),
    ('FCM', None, None, None, 'Free County of Burgundy', '982', '1678',
     'Franche-Comté, the part of Burgundy that belonged to the Empire, around Besançon and Dole. It passed to the dukes of Burgundy in 1384.'),
    ('LLO', None, None, None, 'Duchy of Lower Lotharingia', '959', '1190',
     'The northern half of the old Duchy of Lotharingia, between the Rhine and the Scheldt, in the Empire. It dissolved into Brabant, Limburg, Hainaut and other lordships, and its ducal title passed to the dukes of Brabant.'),
    ('HLD', None, None, None, 'County of Holland', '10th century', '1433',
     'A county of the Empire on the North Sea coast, which grew by taking Zeeland and draining marshland. It passed to the house of Hainaut in 1299 and to the dukes of Burgundy in 1433.'),
    ('HAI', None, None, None, 'County of Hainaut', '9th century', '1433',
     'A county of the Empire around Mons and Valenciennes, ruled together with Holland from 1299. Philip the Good of Burgundy took it in 1433.'),
    ('BRB', None, None, None, 'Duchy of Brabant', '1183', '1430',
     'A duchy of the Empire around Brussels, Leuven and Antwerp that grew out of Lower Lotharingia. It passed to a younger branch of the Burgundian dukes in 1406 and to Philip the Good of Burgundy in 1430.'),
    ('FRI', None, None, None, 'Frisia', '', '1498',
     'The Frisian lands along the North Sea coast, where free peasants governed themselves without a count (the “Frisian freedom”). In 1498 the emperor made Duke Albert of Saxony hereditary governor of Friesland.'),
    ('LUX', None, 1000, E, 'Luxembourg', '963', '1443',
     'A county of the Empire whose counts became kings of Bohemia and emperors (Henry VII, Charles IV); it was made a duchy in 1354. Philip the Good of Burgundy took it in 1443.'),
    ('LOR', None, 1000, E, 'Duchy of Lorraine', '959', '1766',
     'The upper half of the old Duchy of Lotharingia, between France and the Rhine, held by the house of Lorraine from 1048 and part of the Empire. René of Anjou joined it with Bar in 1431, and Duke René II defeated Charles the Bold of Burgundy at Nancy in 1477.'),
    ('GEL', None, 1000, E, 'Duchy of Guelders', '1096', '1543',
     'A county of the Empire on the lower Rhine and Meuse, made a duchy in 1339. It resisted the dukes of Burgundy and the Habsburgs, who held it only briefly in the late 15th century, until 1543.'),
    ('LGE', None, 1000, E, 'Prince-Bishopric of Liège', '980', '1795',
     'A state of the Empire ruled by its bishops, around Liège on the Meuse. Its towns rose against Burgundian control, and Charles the Bold sacked Liège in 1468.'),
    ('JUL', None, 1000, E, 'Cleves and Jülich-Berg', '', '1521',
     'The duchies of the lower Rhine: Cleves with the County of Mark, and Jülich with Berg and Ravensberg, ruled by two families. A marriage united them in 1521 as Jülich-Cleves-Berg.'),
    ('KOL', None, 1000, E, 'Electorate of Cologne', '953', '1803',
     'The state of the archbishops of Cologne, prince-electors of the Empire, along the Rhine and in Westphalia. The city of Cologne itself freed itself from them in 1288.'),
    ('TRR', None, 1000, E, 'Electorate of Trier', '902', '1803',
     'The state of the archbishops of Trier on the Moselle, one of the seven prince-electors of the Empire.'),
    ('BAM', None, 1000, E, 'Prince-Bishopric of Bamberg', '1007', '1802',
     'A state of the Empire in Franconia ruled by the bishops of Bamberg, a see founded by Emperor Henry II in 1007.'),
    ('WRZ', None, 1000, E, 'Prince-Bishopric of Würzburg', '1168', '1803',
     'A state of the Empire in Franconia ruled by the bishops of Würzburg, who held the title of dukes of Franconia from 1168.'),
    ('MUL', None, 1000, E, 'Republic of Mulhouse', '1347', '1798',
     'A free city of the Empire in Alsace that governed itself as a republic and allied itself with the Swiss from 1466.'),
    ('EFR', None, 1000, E, 'County of East Frisia', '1464', '1744',
     'A county on the North Sea coast, formed in 1464 when the emperor made the chieftain Ulrich Cirksena count and united the East Frisian lands.'),
    ('DIT', None, 1000, E, 'Dithmarschen', '13th century', '1559',
     'A peasant republic on the North Sea coast of Holstein, nominally under the archbishops of Bremen. Its farmers defeated a Danish and Holstein army at Hemmingstedt in 1500.'),
    ('SUI', None, 1000, E, 'Old Swiss Confederacy', '1291', 'April 12, 1798',
     'A league of rural cantons (Uri, Schwyz, Unterwalden) and cities (Lucerne, Zürich, Bern and others) in the Alps, formed against Habsburg rule from 1291. It beat the Habsburgs at Morgarten (1315) and Sempach (1386) and Charles the Bold in 1476–77, and in 1499 won near-independence from the Empire.'),
    ('SAV', None, 1000, E, 'Savoy', '1003', '1720',
     'A state of the Empire on both sides of the western Alps, ruled by the house of Savoy from Chambéry; it gained Piedmont around Turin and, in 1388, Nice. Emperor Sigismund made its count a duke in 1416.'),
    ('SLZ', None, 1000, E, 'Marquisate of Saluzzo', '1142', '1548',
     'A small marquisate in the Piedmontese Alps, squeezed between Savoy and the Dauphiné.'),
    ('ORA', None, 1000, E, 'Principality of Orange', '1163', '1713',
     'A small sovereign principality around Orange in the Rhône valley. It passed to the house of Chalon in 1393.'),
    # ---------- the Empire ----------
    ('HRE', None, 1000, E, 'Holy Roman Empire', '962', 'August 6, 1806',
     'The realm of the German kings, crowned emperor in Rome, which took in Germany, the Kingdom of Italy and, from 1032, Burgundy. Strong under the Salian and Staufer emperors, it broke up after 1250 into hundreds of principalities, free cities and church lands under an elected emperor.'),
    ('SXD', None, None, None, 'Duchy of Saxony', '9th century', '1180',
     'The stem duchy of the Saxons in northern Germany, ruled by the Billung and then the Welf dukes. When Duke Henry the Lion was deposed in 1180, the emperor broke it up.'),
    ('SWA', None, None, None, 'Duchy of Swabia', '915', '1268',
     'The stem duchy of the Alemanni in southwest Germany, held from 1079 by the Hohenstaufen, who became emperors. It broke up after the last Hohenstaufen, Conradin, was executed in 1268.'),
    ('FRC', None, None, None, 'Duchy of Franconia', '906', '1168',
     'The stem duchy of the Franks along the Main River. After 939 the German kings kept it under their direct control; its title passed to the bishops of Würzburg in 1168.'),
    ('THU', None, None, None, 'Thuringia', '', '',
     'Thuringia in central Germany, part of the Saxon lands, ruled by margraves and, from about 1130, by landgraves.'),
    ('CAR', None, None, None, 'Duchy of Carinthia', '976', '1335',
     'A duchy in the eastern Alps split off from Bavaria in 976, which at first also included the marches of Carniola, Istria and Verona. It passed to the Habsburgs in 1335.'),
    ('BAV', None, 1000, E, 'Duchy of Bavaria', '', '',
     'The stem duchy of the Bavarians in southeast Germany, from which Austria (1156) and Styria (1180) were split off. The Wittelsbach family held it from 1180, but divided it among several branches from 1255.'),
    ('AUT', None, 1000, E, 'Austria', '976', '1526',
     'A march of Bavaria on the Danube ruled by the Babenberg family, made a separate duchy in 1156. The Habsburgs took it in 1278 and added Styria, Carinthia, Carniola and Tyrol; it was raised to an archduchy in 1453.'),
    ('SAX', None, 1000, E, 'Saxony (Meissen and Wittenberg)', '', '',
     'The lands of the Wettin margraves of Meissen, on the Elbe, and of the Ascanian dukes of Saxe-Wittenberg. Saxe-Wittenberg became an electorate in 1356 and passed to the Wettins in 1423; they divided their lands in 1485.'),
    ('BRA', None, 1000, E, 'Margraviate of Brandenburg', '1157', '1806',
     'A march founded on conquered Slavic land east of the Elbe by the Ascanian Albert the Bear in 1157, whose margraves became prince-electors. It passed to the Wittelsbachs in 1323, the Luxembourgs in 1373 and the Hohenzollerns in 1415.'),
    ('POM', None, 1000, E, 'Duchy of Pomerania', '1121', '1637',
     'A Slavic duchy on the Baltic coast around Stettin, ruled by the Griffin dynasty, which accepted the overlordship of the Empire. It was often divided among branches of the family and was reunited under Bogislaw X in 1478.'),
    ('BRU', None, 1000, E, 'Duchy of Brunswick-Lüneburg', '1235', '1269',
     'The lands of the Welf family around Brunswick and Lüneburg, made a duchy of the Empire in 1235 for Henry the Lion’s grandson. It was divided among his sons in 1269.'),
    ('BOK', None, 1000, 1197, 'Duchy of Bohemia', '870s', '1198',
     'The Czech state of the Přemyslid dukes, with Moravia, part of the Empire. Some of its dukes were given a royal title for life before it became hereditary in 1198.'),
    ('BOK', None, 1198, E, 'Kingdom of Bohemia', '1198', '1526',
     'The Czech kingdom, part of the Empire, whose kings were prince-electors. Under the Luxembourg kings (1310–1437) Prague was the imperial capital; the burning of Jan Hus in 1415 led to the Hussite Wars (1419–34).'),
    ('AQL', None, None, None, 'Patriarchate of Aquileia', '1077', '1445',
     'A state ruled by the patriarchs of Aquileia in Friuli, granted to them by the emperor in 1077. Venice conquered Friuli in 1420; the patriarchs kept a few towns until 1445.'),
    ('TEU', None, 1000, E, 'State of the Teutonic Order', '1230', '1561',
     'The state of a German crusading order that conquered the pagan Prussians from 1230 and took Pomerelia, with Danzig, in 1308. After its defeat by Poland and Lithuania at Grunwald (1410) and the Thirteen Years’ War, it lost western Prussia to Poland in 1466 and held the rest as a Polish fief.'),
    ('LIV', None, 1000, E, 'Livonia', '1202', '1561',
     'The crusader states of Livonia (today’s Latvia and Estonia): the lands of the Livonian Order, a branch of the Teutonic Order, and of the archbishop of Riga and the bishops of Dorpat, Ösel-Wiek and Courland. From 1419 they formed the Livonian Confederation.'),
    ('ITM', None, 1000, E, 'Imperial fiefs in Tuscany', '', '',
     'Small lordships in the Tuscan hills held directly from the emperor, such as the counties of Sovana, Santa Fiora and Vernio.'),
    ('HNL', None, 1000, E, 'Habsburg Netherlands', '1482', '1556',
     'The Burgundian Low Countries, inherited in 1482 by Philip the Handsome, son of Mary of Burgundy and Maximilian of Habsburg.'),
    # ---------- Italy ----------
    ('VEN', None, 1000, E, 'Republic of Venice', '697', 'May 12, 1797',
     'The lagoon republic under its elected doges, a trading power that ruled the Dalmatian coast and, after the Fourth Crusade (1204), Crete and other Greek islands. In the 15th century it conquered a mainland state, the Terraferma, from Friuli to Bergamo.'),
    ('GEN', None, 1000, E, 'Republic of Genoa', '1005', 'June 14, 1797',
     'A trading republic on the Ligurian coast, Venice’s great rival, with colonies around the Black Sea and in the Aegean. It won Corsica from Pisa after defeating it at Meloria in 1284.'),
    ('PIS', None, None, None, 'Republic of Pisa', '11th century', '1406',
     'A maritime republic at the mouth of the Arno that ruled Sardinia and Corsica for a time. After its fleet was destroyed by Genoa at Meloria (1284) it declined, and Florence conquered it in 1406.'),
    ('TUS', None, 1000, E, 'Republic of Florence', '1115', '1532',
     'The city republic of Florence, grown rich on banking and cloth, which conquered most of Tuscany, including Pisa in 1406. From 1434 the Medici family ruled it behind republican forms.'),
    ('TSC', None, None, None, 'March of Tuscany', '9th century', '1115',
     'A march of the Kingdom of Italy, within the Empire, ruled from Lucca and Florence. Its last ruler, Matilda of Canossa (died 1115), backed the popes against the emperor; after her the Tuscan cities governed themselves.'),
    ('SIE', None, 1000, E, 'Republic of Siena', '1125', '1555',
     'A Tuscan city republic and rival of Florence, which it defeated at Montaperti in 1260.'),
    ('LUC', None, 1000, E, 'Republic of Lucca', '1160', 'June 23, 1805',
     'A Tuscan city republic that kept its independence from Florence; the lord Paolo Guinigi ruled it in 1400–30.'),
    ('MLS', None, 1000, E, 'Milan', '1277', '1535',
     'The state of the Visconti family, lords of Milan from 1277, which conquered most of Lombardy; Gian Galeazzo Visconti bought the title of duke from the emperor in 1395. After the short Ambrosian Republic (1447–50), the condottiere Francesco Sforza took power.'),
    ('VRN', None, 1000, 1151, 'March of Verona', '952', '12th century',
     'A march of the Kingdom of Italy held by the dukes of Bavaria and then Carinthia, reaching from the Alps to the Adriatic. The cities in it later governed themselves as communes.'),
    ('VRN', None, 1152, E, 'Lordship of Verona', '1262', '1387',
     'The state of the della Scala family (the Scaligers), who ruled Verona from 1262 and, under Cangrande (died 1329), much of the Veneto. The Visconti of Milan took it in 1387, and Venice in 1405.'),
    ('SPO', None, None, None, 'Duchy of Spoleto', '570s', '1198',
     'A Lombard duchy in central Italy which later belonged to the Kingdom of Italy. Pope Innocent III took it into the Papal States in 1198.'),
    ('PAP', None, 1000, E, 'Papal States', '756', 'September 20, 1870',
     'The lands ruled by the popes around Rome and, nominally, across central Italy to Ravenna; many towns were in practice held by their own lords. The popes lived in Avignon from 1309 to 1377, and only in the 15th century did they regain firm control.'),
    ('MOD', None, 1000, E, 'Este lands (Ferrara, Modena and Reggio)', '1264', '1597',
     'The lands of the Este family, lords of Ferrara from 1264 and of Modena and Reggio. The emperor made Borso d’Este duke of Modena and Reggio in 1452, and the pope made him duke of Ferrara in 1471.'),
    ('MAN', None, 1000, E, 'Mantua', '1328', '1708',
     'The state of the Gonzaga family, lords of Mantua from 1328, made margraves by the emperor in 1433.'),
    ('MIR', None, 1000, E, 'Lordship of Mirandola', '1310', '1710',
     'A small lordship in the Po valley held by the Pico family, part of the Empire.'),
    ('GUA', None, 1000, E, 'County of Guastalla', '1406', '1746',
     'A small county on the Po, held by the Torelli family from 1406 and made a county in 1428.'),
    ('NOV', None, 1000, E, 'Novellara', '1371', '1728',
     'A small lordship in the Po valley held by a branch of the Gonzaga family.'),
    ('NOL', None, 1000, E, 'Republic of Noli', '1192', '1797',
     'A small maritime republic on the Ligurian coast, allied with Genoa.'),
    ('PIO', None, 1000, E, 'Lordship of Piombino', '1399', '1805',
     'A small coastal lordship in Tuscany, with the island of Elba, held by the Appiani family from 1399.'),
    ('SMR', None, 1000, E, 'San Marino', '301', '',
     'A tiny republic on Monte Titano, which traces its founding to 301 and kept its independence amid the Papal States.'),
    ('COS', None, 1000, E, 'Republic of Cospaia', '1440', '1826',
     'A tiny village republic between Florence and the Papal States, left out of a border treaty in 1440.'),
    ('AND', None, 1000, E, 'Andorra', '1278', '',
     'A Pyrenean valley ruled jointly by the bishop of Urgell and the count of Foix under agreements of 1278.'),
    ('BEN_L', None, None, None, 'Principality of Benevento', '774', '1077',
     'A Lombard principality in southern Italy, the remnant of the old Duchy of Benevento. The city submitted to the pope in 1051, and the Normans took the surrounding land.'),
    ('BEN', None, 1000, E, 'Benevento', '1051', '1860',
     'A town in southern Italy that belonged to the popes from 1051 (formally from 1077), an enclave in Norman and later Neapolitan land.'),
    ('SLR', None, None, None, 'Principality of Salerno', '851', '1077',
     'A Lombard principality in southern Italy. The Norman Robert Guiscard, who had married the prince’s sister, took it in 1077.'),
    ('CPU', None, None, None, 'Principality of Capua', '900', '1058',
     'A Lombard principality north of Naples. The Norman Richard of Aversa conquered it in 1058.'),
    ('NPD', None, None, None, 'Duchy of Naples', '661', '1137',
     'A self-governing duchy around Naples, nominally under Byzantium. It was the last part of southern Italy to fall to the Normans, in 1137–39.'),
    ('AMA', None, None, None, 'Duchy of Amalfi', '839', '1131',
     'A small maritime republic on the Amalfi coast and a trading power in the Mediterranean. The Normans took it in 1073 and ended its self-government in 1131.'),
    ('GTA', None, None, None, 'Duchy of Gaeta', '839', '1140',
     'A small self-governing duchy on the coast between Rome and Naples, taken over by the Normans in the 12th century.'),
    ('NRM', None, None, None, 'Norman Italy', '1030s', '1130',
     'The lands of Norman adventurers who conquered southern Italy and Sicily: the Duchy of Apulia and Calabria of Robert Guiscard, and the County of Sicily of his brother Roger I, from 1071. Roger II united them as the Kingdom of Sicily in 1130.'),
    ('ESC', None, None, None, 'Emirate of Sicily', '831', '1091',
     'Muslim Sicily, ruled from Palermo by emirs under the Fatimid caliphs. It broke up into rival emirates in the 1040s and was conquered by the Normans in 1061–91.'),
    ('SIC_M', None, None, None, 'Kingdom of Sicily', '1130', '1282',
     'The Norman kingdom of Roger II, which took in the island and southern Italy and was ruled from Palermo. It passed to the Hohenstaufen emperors in 1194 and to Charles of Anjou in 1266; the Sicilian Vespers revolt of 1282 split off the island.'),
    ('SIC', None, 1000, 1408, 'Kingdom of Sicily', '1282', '1409',
     'The island of Sicily, which rebelled against the Angevin king in 1282 and chose the king of Aragon instead. A branch of the Aragonese royal family ruled it until 1409.'),
    ('SIC_R', None, None, None, 'Kingdom of Sicily (under Aragon)', '1409', '1816',
     'From 1409 Sicily was ruled by the kings of Aragon through viceroys.'),
    ('SIC_S', None, 1000, E, 'Kingdom of Sicily (under Spain)', '1409', '1816',
     'Sicily was ruled by viceroys of Ferdinand II of Aragon, joint ruler of Spain from 1479.'),
    ('NAP', None, 1000, E, 'Kingdom of Naples', '1282', '1504',
     'The mainland south of Italy, ruled from Naples by the Angevin kings after Sicily broke away in 1282; they still called it the Kingdom of Sicily. Alfonso V of Aragon conquered it in 1442, and his son Ferdinand and his heirs held it until the French invasion of 1494–95.'),
    ('ARB', None, None, None, 'Judicate of Arborea', '9th century', '1420',
     'One of the four Sardinian kingdoms, ruled by judges (giudici), in the west of the island. It resisted the Aragonese conquest longest; its last ruler sold his rights to Aragon in 1420.'),
    ('CAG', None, None, None, 'Judicate of Cagliari', '9th century', '1258',
     'One of the four Sardinian kingdoms, in the south of the island. Pisa conquered it in 1258.'),
    ('GLL', None, None, None, 'Judicate of Gallura', '9th century', '1288',
     'One of the four Sardinian kingdoms, in the northeast. It passed to the Pisan Visconti family and then to Pisa in 1288.'),
    ('LGD', None, None, None, 'Judicate of Logudoro', '9th century', '1259',
     'One of the four Sardinian kingdoms, in the northwest. It ended in 1259, when its lands were divided among the Genoese Doria and Malaspina families and Arborea.'),
    ('SDR', None, None, None, 'Kingdom of Sardinia (under Aragon)', '1324', '1720',
     'Sardinia, granted by the pope to the king of Aragon in 1297 and conquered from Pisa from 1323. Arborea held out against Aragon until 1420.'),
    ('KHR', None, None, None, 'Knights Hospitaller (Rhodes)', '1310', '1522',
     'The crusading order of the Knights of St. John, which took Rhodes and nearby islands from Byzantium in 1306–10. It held off Ottoman sieges until 1522, then moved to Malta.'),
    ('ARC', None, 1000, E, 'Duchy of the Archipelago', '1207', '1579',
     'A duchy of the Cyclades founded after the Fourth Crusade by the Venetian Marco Sanudo, with its capital on Naxos.'),
    # ---------- Iberia ----------
    ('CRD', None, None, None, 'Caliphate of Córdoba', '929', '1031',
     'The Umayyad state of al-Andalus, at its height around 1000 under the chief minister al-Mansur, who raided the Christian north. It fell apart in a civil war after 1009 and was abolished in 1031, leaving the taifa kingdoms.'),
    ('TAI', None, None, None, 'Taifa kingdoms', '1009', '1266',
     'The small Muslim kingdoms that succeeded the Caliphate of Córdoba, ruled by Arab, Berber and Slavic dynasties; many paid tribute to Christian kings. The Almoravids took over most of them in the 1090s; new taifas arose when the Almoravids fell in the 1140s and the Almohads in the 1220s, until Castile, Aragon and Granada absorbed them.'),
    ('TOL', None, None, None, 'Taifa of Toledo', '1031', '1085',
     'The taifa kingdom of central Spain, ruled by the Banu Dhi-n-Nun. Alfonso VI of León and Castile took Toledo in 1085.'),
    ('SEV', None, None, None, 'Taifa of Seville', '1023', '1091',
     'The taifa of the Abbadid dynasty, the strongest in the south, which absorbed Córdoba and many smaller taifas. The Almoravids deposed its poet-king al-Mu’tamid in 1091.'),
    ('ZAR', None, None, None, 'Taifa of Zaragoza', '1018', '1110',
     'The taifa of the Ebro valley, ruled from 1039 by the Banu Hud. It fell to the Almoravids in 1110, and Aragon took Zaragoza in 1118.'),
    ('BDJ', None, None, None, 'Taifa of Badajoz', '1009', '1094',
     'The taifa of the western frontier, ruled by the Aftasid dynasty. The Almoravids took it in 1094.'),
    ('VLC', None, None, None, 'Taifa of Valencia', '1010', '1238',
     'The taifa of the east coast around Valencia. El Cid held the city in 1094–1102; after the Almoravids and Almohads, a last taifa there fell to James I of Aragon in 1238.'),
    ('GRT', None, None, None, 'Taifa of Granada', '1013', '1090',
     'The taifa of the Zirid Berber dynasty in the south. The Almoravids took it in 1090.'),
    ('DNI', None, None, None, 'Taifa of Dénia', '1010', '1076',
     'A taifa on the east coast that also held the Balearic Islands and was a naval power. Zaragoza took Dénia in 1076.'),
    ('ALR', None, None, None, 'Taifa of Almería', '1013', '1091',
     'A taifa around the port of Almería, taken by the Almoravids in 1091.'),
    ('MUR', None, None, None, 'Taifa of Murcia', '1011', '1266',
     'A taifa in the southeast; under Ibn Mardanish (1147–72) it was the main Muslim rival of the Almohads. It became a vassal of Castile in 1243 and was annexed in 1266.'),
    ('ALV', None, None, None, 'Almoravid Empire', '1040s', '1203',
     'A Berber movement from the Sahara whose emirs built an empire from the Senegal River to the Ebro, ruled from Marrakesh. They crossed into Spain in 1086 to fight Castile and took over the taifas; the Almohads overthrew them in 1147, though an Almoravid family held the Balearic Islands until 1203.'),
    ('ALH', None, None, None, 'Almohad Caliphate', '1121', '1269',
     'A Berber religious movement from the Atlas Mountains that conquered the Almoravid empire (1147) and Ifriqiya (1160). Its defeat by the Christian kings at Las Navas de Tolosa (1212) began its collapse, and the Marinids took Marrakesh in 1269.'),
    ('GRN', None, None, None, 'Emirate of Granada', '1238', 'January 2, 1492',
     'The last Muslim state in Spain, ruled by the Nasrid dynasty, who built the Alhambra; it paid tribute to Castile for long periods. Ferdinand and Isabella conquered it in 1482–92.'),
    ('LEO', None, None, None, 'Kingdom of León', '910', '1230',
     'The kingdom of northwest Spain, successor of Asturias, which led the Christian advance against al-Andalus; its kings claimed the title of emperor. It was joined with Castile in 1037–1157 and for good in 1230.'),
    ('CAS', None, 1000, 1064, 'County of Castile', '850s', '1065',
     'The eastern county of the Kingdom of León, which grew powerful and passed to the Navarrese royal house in 1029. Its count Ferdinand I became king of León in 1037, and at his death in 1065 Castile became a kingdom for his son Sancho II.'),
    ('CAS', None, 1065, 1229, 'Kingdom of Castile', '1065', '1230',
     'The central kingdom of Christian Spain, often joined with León. Alfonso VI took Toledo in 1085, and Alfonso VIII led the victory over the Almohads at Las Navas de Tolosa in 1212.'),
    ('CAS', None, 1230, E, 'Crown of Castile', '1230', '1479',
     'Castile and León, united for good in 1230 under Ferdinand III, who conquered Córdoba (1236) and Seville (1248). Isabella I’s marriage to Ferdinand of Aragon led to the union of the two crowns in 1479.'),
    ('ARA', None, 1000, 1163, 'Kingdom of Aragon', '1035', '1164',
     'A Pyrenean kingdom that grew from a county of Navarre and took Zaragoza in 1118. The marriage of its heiress Petronilla to the count of Barcelona created the Crown of Aragon.'),
    ('ARA', None, 1164, E, 'Crown of Aragon', '1164', '1479',
     'The union of Aragon and Catalonia, which took Majorca and Valencia under James I (1229–45) and became a Mediterranean power holding Sicily, Sardinia and, from 1442, Naples. Ferdinand II’s marriage to Isabella of Castile joined it to Castile in 1479.'),
    ('ESP', None, 1000, E, 'Spain (Castile and Aragon)', '1479', '',
     'The union of the crowns of Castile and Aragon under Isabella and Ferdinand, the Catholic Monarchs, each kingdom keeping its own laws. They conquered Granada in 1492 and sponsored Columbus’s voyage the same year.'),
    ('NAV', None, 1000, E, 'Kingdom of Navarre', '824', '1512',
     'The Basque kingdom of Pamplona, which under Sancho III (1004–35) dominated Christian Spain. It was joined with Aragon in 1076–1134 and afterward passed to French dynasties: Champagne, Évreux, Foix and Albret.'),
    ('BCN', None, None, None, 'County of Barcelona', '878', '1164',
     'The leading county of Catalonia, whose counts gathered the other Catalan counties. Count Ramon Berenguer IV’s marriage to the heiress of Aragon created the Crown of Aragon.'),
    ('CAT', None, None, None, 'Catalan counties', '', '',
     'Smaller counties of Catalonia and the Pyrenees, such as Cerdanya, Besalú, Empúries and Pallars, ruled by their own counts. Most passed to the counts of Barcelona in the 12th century.'),
    ('URG', None, None, None, 'County of Urgell', '9th century', '1413',
     'A Catalan county in the Pyrenees, which kept its own counts until 1413; the last of them, James, lost a war for the Aragonese throne.'),
    ('RIB', None, None, None, 'County of Ribagorza', '9th century', '1018',
     'A county in the central Pyrenees, taken by Sancho III of Navarre around 1018 and later part of Aragon.'),
    ('POR_C', None, None, None, 'County of Portugal', '868', '1139',
     'A county on the Douro, part of the Kingdom of León. Count Afonso Henriques proclaimed himself king in 1139.'),
    ('POR', None, 1000, E, 'Kingdom of Portugal', '1139', '1910',
     'The kingdom founded by Afonso Henriques, who took Lisbon in 1147 with the help of crusaders; Portugal completed its reconquest with the Algarve in 1249. From 1415 it built a seaborne empire, taking Ceuta and exploring the African coast.'),
    ('GLC', None, None, None, 'Kingdom of Galicia', '', '',
     'Galicia in the northwest, usually part of the Kingdom of León but at times a kingdom of its own, as under García II (1065–71).'),
    ('MAJ', None, None, None, 'Kingdom of Majorca', '1231', '1344',
     'The Balearic Islands, Roussillon and Montpellier, left by James I of Aragon to his younger son in 1276. Peter IV of Aragon took it back in 1344.'),
    # ---------- North Africa and the Near East ----------
    ('ZIR', None, None, None, 'Zirids', '972', '1148',
     'A Berber dynasty that ruled Ifriqiya (today’s Tunisia) from Kairouan and Mahdia, at first for the Fatimid caliphs. After breaking with them in the 1040s it lost most of its land to the Banu Hilal Arab tribes, and the Normans took Mahdia in 1148.'),
    ('HMD', None, None, None, 'Hammadids', '1014', '1152',
     'A Berber dynasty, a branch of the Zirids, that ruled the central Maghreb (today’s Algeria) from Béjaïa. The Almohads conquered it in 1152.'),
    ('FAT', None, None, None, 'Fatimid Caliphate', '909', '1171',
     'A Shia Ismaili caliphate that ruled North Africa, Egypt and Syria from Cairo. It lost North Africa to its Zirid governors and Syria to the Seljuks and the crusaders; Saladin ended it in 1171.'),
    ('BRG', None, None, None, 'Barghawata', '744', '1060s',
     'A Berber confederation on the Atlantic coast of Morocco with its own religion. The Almoravids destroyed it in the 1050s and 1060s.'),
    ('NKR', None, None, None, 'Emirate of Nekor', '710', '1019',
     'A small emirate on the Rif coast of Morocco.'),
    ('HAF', None, 1000, E, 'Hafsid Sultanate of Tunis', '1229', '1574',
     'A Berber dynasty of Almohad governors in Tunis who declared independence in 1229 and ruled Ifriqiya. Trade with the Italian cities made Tunis prosperous.'),
    ('TLM', None, 1000, E, 'Kingdom of Tlemcen', '1236', '1554',
     'A Berber kingdom in western Algeria ruled by the Zayyanid dynasty, squeezed between the Marinids of Morocco and the Hafsids of Tunis.'),
    ('MOR', None, 1000, E, 'Morocco (Marinid and Wattasid sultans)', '1244', '',
     'The Marinid dynasty took Morocco from the Almohads, taking Marrakesh in 1269, and ruled from Fez. Their Wattasid regents took the throne in 1472, while Portugal seized ports on the coast.'),
    ('ABB', None, None, None, 'Abbasid Caliphate', '750', '1258',
     'The caliphate of Baghdad, whose caliphs by 1000 were religious figureheads under the Buyid and then the Seljuk sultans. The Mongols sacked Baghdad and killed the last caliph there in 1258.'),
    ('BUY', None, None, None, 'Buyids', '934', '1062',
     'A Shia Iranian dynasty that ruled Iraq and western Iran and controlled the Abbasid caliphs in Baghdad. The Seljuks overthrew it in 1055–62.'),
    ('JAZ', None, None, None, 'Emirates of Upper Mesopotamia', '', '',
     'Small Arab and Kurdish emirates between the Tigris and the Euphrates, such as the Marwanids of Diyarbakır and the Uqaylids of Mosul, and later the Turkish Artuqids. Cliopatria groups them under the name of their predecessors, the Hamdanids.'),
    ('SEL', None, None, None, 'Great Seljuk Empire', '1037', '1194',
     'A Turkish empire founded by the Seljuk clan, which took Baghdad in 1055 and ruled Iran, Iraq and Syria. Its victory over Byzantium at Manzikert (1071) opened Anatolia to Turkish settlement; after 1092 it split among rival branches.'),
    ('RUM', None, None, None, 'Sultanate of Rum', '1077', '1308',
     'A Seljuk sultanate in Anatolia with its capital at Konya, founded after the Byzantine defeat at Manzikert. It flourished in the early 13th century, became a Mongol vassal after the battle of Köse Dağ (1243) and faded away by 1308.'),
    ('DSH', None, None, None, 'Danishmendids', '1071', '1178',
     'A Turkish dynasty in north-central Anatolia, around Sivas, a rival of the Seljuks of Rum, who absorbed it by 1178.'),
    ('CIL', None, None, None, 'Armenian Kingdom of Cilicia', '1080', '1375',
     'An Armenian state on the south coast of Anatolia, founded by refugees from Armenia and made a kingdom in 1198; it was an ally of the crusaders and later of the Mongols. The Mamluks conquered it in 1375.'),
    ('ANT', None, None, None, 'Principality of Antioch', '1098', '1268',
     'A crusader state founded by Bohemond of Taranto after the siege of Antioch in the First Crusade. The Mamluk sultan Baybars destroyed Antioch in 1268.'),
    ('EDE', None, None, None, 'County of Edessa', '1098', '1150',
     'The first crusader state, on the upper Euphrates, founded by Baldwin of Boulogne. Zengi took Edessa in 1144, which set off the Second Crusade; the rest fell by 1150.'),
    ('TRP', None, None, None, 'County of Tripoli', '1102', '1289',
     'A crusader state on the Lebanese coast. The Mamluks took Tripoli in 1289.'),
    ('JER', None, None, None, 'Kingdom of Jerusalem', '1099', '1291',
     'The crusader kingdom founded after the capture of Jerusalem in 1099. Saladin took Jerusalem in 1187; the kingdom survived on the coast until the fall of Acre in 1291.'),
    ('ZNG', None, None, None, 'Zengids', '1127', '1250',
     'A Turkish dynasty founded by Zengi, governor of Mosul and Aleppo, who took Edessa from the crusaders in 1144. His son Nur ad-Din united Syria; Saladin took over most of its lands after 1174.'),
    ('AYY', None, None, None, 'Ayyubid Sultanate', '1171', '1260',
     'The state founded by Saladin, who ended the Fatimid caliphate, united Egypt and Syria and retook Jerusalem from the crusaders in 1187. It was divided among his relatives; the Mamluks overthrew it in Egypt in 1250 and the Mongols in Syria in 1260.'),
    ('MAM', None, 1000, E, 'Mamluk Sultanate', '1250', '1517',
     'A state ruled from Cairo by sultans drawn from slave soldiers (mamluks), who stopped the Mongols at Ain Jalut (1260) and drove the crusaders from the Levant by 1291. It held Syria and the holy cities of Arabia until the Ottoman conquest of 1516–17.'),
    ('KHW', None, None, None, 'Khwarazmian Empire', '1077', '1231',
     'A Turkish-Persian empire based south of the Aral Sea, which took over Iran in the early 13th century. Genghis Khan destroyed it in 1219–21.'),
    ('MNG', None, None, None, 'Mongol Empire', '1206', '1368',
     'The empire founded by Genghis Khan, whose armies under Batu conquered the Volga region and the Rus’ principalities in 1237–40 and raided Poland and Hungary in 1241. Its western part became the Golden Horde.'),
    ('ILK', None, None, None, 'Ilkhanate', '1256', '1357',
     'The Mongol khanate founded by Hulagu in Iran and Iraq, which sacked Baghdad in 1258 and ruled Anatolia through the Seljuks of Rum. It fell apart after the death of Abu Said in 1335, though puppet khans were set up until 1357.'),
    ('CHB', None, None, None, 'Chobanids', '1335', '1357',
     'A Mongol family of emirs who held Azerbaijan and parts of Iran after the Ilkhanate fell apart, ruling from Tabriz until the Golden Horde invaded in 1357.'),
    ('JAL', None, None, None, 'Jalayirids', '1335', '1432',
     'A Mongol dynasty that ruled Iraq and Azerbaijan from Baghdad and Tabriz after the Ilkhanate, until Timur and then the Qara Qoyunlu took their lands.'),
    ('TIM', None, None, None, 'Timurid Empire', '1370', '1507',
     'The empire of Timur (Tamerlane), who from Samarkand conquered Iran, Iraq and the Caucasus, crushed the Golden Horde (1395) and defeated the Ottomans at Ankara (1402). After his death in 1405 it shrank to Central Asia and eastern Iran.'),
    ('QQY', None, None, None, 'Qara Qoyunlu', '1375', '1468',
     'A Turkmen confederation, the “Black Sheep,” that ruled Azerbaijan, Armenia and Iraq from Tabriz. The rival Aq Qoyunlu destroyed it in 1467–68.'),
    ('AQQ', None, 1000, E, 'Aq Qoyunlu', '1378', '1503',
     'A Turkmen confederation, the “White Sheep,” based at Diyarbakır, which under Uzun Hasan (1453–78) took over Iran from the Qara Qoyunlu. The Safavids destroyed it in 1501–03.'),
    ('ARB_A', None, None, None, 'Bagratid Armenia', '885', '1045',
     'The Armenian kingdom of the Bagratid dynasty, with its capital at Ani. Byzantium annexed it in 1045.'),
    ('VAS', None, None, None, 'Kingdom of Vaspurakan', '908', '1021',
     'An Armenian kingdom around Lake Van, ruled by the Artsruni dynasty. Its king ceded it to Byzantium in 1021.'),
    ('GEO', None, 1000, E, 'Kingdom of Georgia', '1008', '',
     'The Georgian kingdom united by Bagrat III in 1008, which reached its height under David IV the Builder and Queen Tamar (1184–1213). Mongol and Timurid invasions weakened it, and after 1466 it broke up into Kartli, Kakheti, Imereti and smaller principalities.'),
    ('IME', None, 1000, E, 'Kingdom of Imereti', '1455', '1810',
     'A Georgian kingdom in the west of the country, independent after the breakup of the Kingdom of Georgia in the late 15th century.'),
    ('CAU', None, 1000, E, 'Western Georgian principalities', '', '',
     'Principalities of western Georgia, such as Abkhazia, Mingrelia and Guria, which broke away from the Georgian crown in the late 15th century.'),
    ('SHI', None, 1000, E, 'Shirvan', '861', '1538',
     'A Muslim state on the Caspian coast, in today’s Azerbaijan, ruled by the Shirvanshahs, often as vassals of larger powers.'),
    ('KRM', None, None, None, 'Karamanids', '1250s', '1487',
     'A Turkish beylik in south-central Anatolia, centered on Karaman and Konya, the Ottomans’ strongest rival among the beyliks. The Ottomans conquered it in 1468–87.'),
    ('GRM', None, None, None, 'Germiyanids', '1300', '1429',
     'A Turkish beylik in western Anatolia around Kütahya, annexed by the Ottomans in 1429.'),
    ('AYD', None, None, None, 'Aydinids', '1308', '1426',
     'A Turkish beylik on the Aegean coast around Smyrna and Ephesus, known for its sea raids; the Ottomans annexed it in 1426.'),
    ('MEN', None, None, None, 'Menteshe', '1260s', '1424',
     'A Turkish beylik in southwest Anatolia (Caria), annexed by the Ottomans in 1424.'),
    ('SRH', None, None, None, 'Saruhanids', '1313', '1410',
     'A Turkish beylik around Manisa in western Anatolia, annexed by the Ottomans in 1410.'),
    ('KRS', None, None, None, 'Karasids', '1290s', '1340s',
     'A Turkish beylik in northwest Anatolia (Mysia), the first to be taken over by the Ottomans, in the 1340s.'),
    ('HMI', None, None, None, 'Hamidids', '1300', '1374',
     'A Turkish beylik around Isparta in southwest Anatolia, which sold its lands to the Ottomans in 1374.'),
    ('TKE', None, None, None, 'Teke', '1320s', '1423',
     'A Turkish beylik around Antalya, a branch of the Hamidids, annexed by the Ottomans in 1423.'),
    ('CND', None, None, None, 'Candarids', '1290s', '1461',
     'A Turkish beylik in northern Anatolia around Kastamonu and Sinop, also called the Isfendiyarids; the Ottomans annexed it in 1461.'),
    ('DUL', None, None, None, 'Dulkadirids', '1337', '1522',
     'A Turkmen beylik in southeast Anatolia around Elbistan and Maraş, a buffer between the Mamluks and the Ottomans.'),
    ('RMD', None, None, None, 'Ramadanids', '1352', '1608',
     'A Turkmen beylik around Adana in Cilicia, under Mamluk and then Ottoman overlordship.'),
    ('BEY', None, None, None, 'Other Turkish beyliks', '', '',
     'Short-lived Turkish principalities in Anatolia after the Seljuk collapse, such as the Eshrefids of Beyşehir and the Ahi brotherhood of Ankara.'),
    ('OTT', None, 1000, E, 'Ottoman Empire', '1299', '1922',
     'A Turkish beylik in northwest Anatolia founded by Osman I, which crossed into Europe in 1354 and conquered most of the Balkans. Timur crushed it at Ankara in 1402, but it recovered, and Mehmed II took Constantinople in 1453.'),
    # ---------- Byzantium and the Balkans ----------
    ('BYZ', None, None, 1203, 'Byzantine Empire', '330', 'May 29, 1453',
     'The Eastern Roman Empire, ruled from Constantinople, which under Basil II conquered Bulgaria (1018) and reached its widest extent since the 7th century. It lost most of Anatolia to the Seljuk Turks after Manzikert (1071); the Komnenos emperors won part of it back.'),
    ('BYZ', None, 1204, None, 'Byzantine Empire', '330', 'May 29, 1453',
     'Restored by the Nicaean emperor Michael VIII, who retook Constantinople in 1261, the empire lost Anatolia to the Turks and much of the Balkans to Serbia and the Ottomans. By 1400 it held little beyond Constantinople, Thessalonica and the Morea; the Ottomans took Constantinople in 1453 and the Morea in 1460.'),
    ('LAT', None, None, None, 'Latin Empire', '1204', '1261',
     'The empire set up in Constantinople by the Fourth Crusade, which sacked the city in 1204. The Empire of Nicaea retook Constantinople in 1261.'),
    ('NIC', None, None, None, 'Empire of Nicaea', '1204', '1261',
     'The largest of the Byzantine successor states after 1204, in western Anatolia, under the Laskarid emperors. It retook Constantinople in 1261 and restored the Byzantine Empire.'),
    ('THL', None, None, None, 'Kingdom of Thessalonica', '1204', '1224',
     'A crusader kingdom in Macedonia and Thessaly founded by Boniface of Montferrat after the Fourth Crusade. Epirus conquered it in 1224.'),
    ('EPI', None, None, None, 'Despotate of Epirus', '1205', '1479',
     'A Byzantine successor state in western Greece and Albania founded after 1204, which held Thessalonica in 1224–46. It passed to Italian and Albanian rulers in the 14th century, and the Ottomans took the last of it in 1479.'),
    ('TRE', None, None, None, 'Empire of Trebizond', '1204', '1461',
     'A Byzantine successor state on the Black Sea coast of Anatolia, ruled by the Grand Komnenos dynasty and rich from trade. The Ottomans took it in 1461.'),
    ('ACH', None, None, None, 'Principality of Achaea', '1205', '1432',
     'A crusader state in the Peloponnese founded by French knights after the Fourth Crusade. The Byzantines of Mistras won it back piece by piece; the last of it fell to them in 1432.'),
    ('ATH', None, None, None, 'Duchy of Athens', '1205', '1458',
     'A crusader state in Attica and Boeotia founded after the Fourth Crusade and ruled by the de la Roche family, the Catalan Company (1311–88) and the Florentine Acciaioli. The Ottomans took Athens in 1456–58.'),
    ('CYK', None, None, None, 'Kingdom of Cyprus', '1192', '1489',
     'A crusader kingdom on Cyprus ruled by the Lusignan family, who acquired the island after Richard I of England took it in 1191. Genoa held Famagusta from 1373, and Venice took over the island in 1489.'),
    ('THD', None, None, None, 'Principality of Theodoro', '14th century', '1475',
     'A small Orthodox Greek principality in the mountains of southern Crimea, centered on Mangup. The Ottomans took it in 1475.'),
    ('BGE', None, None, 1100, 'First Bulgarian Empire', '681', '1018',
     'The Bulgarian state, which under Tsar Samuel (997–1014) held Macedonia and much of the western Balkans. Basil II of Byzantium conquered it by 1018.'),
    ('BGE', None, 1101, None, 'Second Bulgarian Empire', '1185', '1396',
     'The Bulgarian state restored by a revolt against Byzantium in 1185, with its capital at Tarnovo; it was strongest under Ivan Asen II (1218–41). It split in the 1350s, and the Ottomans conquered it in 1393–96.'),
    ('VID', None, None, None, 'Tsardom of Vidin', '1356', '1396',
     'A part of the Bulgarian Empire in the northwest that became a separate tsardom under Ivan Sratsimir in 1356. The Ottomans took it in 1396.'),
    ('DOB', None, None, None, 'Despotate of Dobruja', '1340s', '1388',
     'A Bulgarian principality on the Black Sea coast (Dobruja), independent in the late 14th century until the Ottomans took it.'),
    ('SRM', None, None, 1216, 'Grand Principality of Serbia', '9th century', '1217',
     'The Serbian state of Raška, ruled by grand župans and often under Byzantine overlordship. Stefan Nemanja (1166–96) made it independent and founded the Nemanjić dynasty.'),
    ('SRM', None, 1217, 1345, 'Kingdom of Serbia', '1217', '1346',
     'The Serbian kingdom of the Nemanjić dynasty, which conquered Macedonia from Byzantium in the early 14th century.'),
    ('SRM', None, 1346, 1371, 'Serbian Empire', '1346', '1371',
     'Stefan Dušan, crowned emperor in 1346, ruled from the Danube to the Gulf of Corinth. After his death in 1355 his empire broke apart among regional lords, and the Ottomans defeated the Serbs on the Maritsa in 1371.'),
    ('SRM', None, 1372, None, 'Serbian Despotate', '1371', '1459',
     'The remnant of Serbia under Prince Lazar and his heirs, an Ottoman vassal after the battle of Kosovo (1389); the despots ruled from Belgrade and then Smederevo. The Ottomans annexed it in 1459.'),
    ('DUK', None, None, None, 'Duklja and Zeta', '1040s', '15th century',
     'A Serbian principality on the Adriatic coast, today’s Montenegro, a kingdom in the late 11th century. It came under Raška in the late 12th century; later, as Zeta, it was ruled by the Balšić and Crnojević families.'),
    ('HRZ', None, None, None, 'Duchy of Saint Sava (Herzegovina)', '1448', '1482',
     'The land of Stjepan Vukčić Kosača, who took the title of duke of Saint Sava in 1448, giving the region the name Herzegovina (“duke’s land”). The Ottomans conquered it by 1482.'),
    ('BOS', None, None, None, 'Bosnia', '1154', '1463',
     'A banate under nominal Hungarian overlordship that became a kingdom under Tvrtko I in 1377. The Ottomans conquered it in 1463.'),
    ('CRO', None, None, None, 'Kingdom of Croatia', '925', '1102',
     'The Croatian kingdom on the Adriatic and in Slavonia. In 1102 it entered a union with Hungary under the Árpád kings, keeping its own nobility and laws.'),
    ('ALP', None, None, None, 'Albanian principalities', '1350s', '1479',
     'Principalities of Albanian noble families, such as the Balsha, Thopia, Dukagjini and Kastrioti, that arose as Serbian power faded. Skanderbeg of the Kastrioti led them against the Ottomans from 1443 until his death in 1468.'),
    ('RAG', None, 1000, E, 'Republic of Ragusa (Dubrovnik)', '1358', 'January 31, 1808',
     'A trading city republic on the Dalmatian coast, independent of Venice from 1358 under Hungarian overlordship; from 1458 it paid tribute to the Ottomans.'),
    ('WAL_I', None, None, None, 'Wallachia', '1310s', 'January 24, 1859',
     'A principality between the Carpathians and the Danube founded by Basarab I, who won independence from Hungary at Posada in 1330. Mircea the Elder (1386–1418) fought the Ottomans but began paying them tribute in 1417.'),
    ('WAL', None, 1000, E, 'Wallachia (paying Ottoman tribute)', '1310s', 'January 24, 1859',
     'Wallachia paid tribute to the Ottomans from 1417 but kept its own princes, among them Vlad III Dracula (1448, 1456–62, 1476).'),
    ('MOL_I', None, None, None, 'Moldavia', '1359', 'January 24, 1859',
     'A principality east of the Carpathians founded around 1359 by Bogdan I, who broke away from Hungary. Under Stephen the Great (1457–1504) it fought off the Ottomans, Hungary and Poland.'),
    ('MOL', None, 1000, E, 'Moldavia (paying Ottoman tribute)', '1359', 'January 24, 1859',
     'Moldavia began paying tribute to the Ottomans in 1456. Stephen the Great defeated them at Vaslui in 1475 but lost the Black Sea ports of Kilia and Akkerman in 1484.'),
    ('HUK', None, 1000, E, 'Kingdom of Hungary', '1000', '1526',
     'The kingdom founded when Stephen I was crowned in 1000, which joined Croatia to it in 1102 and ruled Transylvania. It recovered from the Mongol invasion of 1241, and under Matthias Corvinus (1458–90) it conquered Moravia, Silesia and Vienna.'),
    # ---------- Poland, the Baltic, the Rus', the steppe ----------
    ('PLK', None, 1000, 1137, 'Kingdom of Poland', '966', '1569',
     'The Polish state of the Piast dynasty; Bolesław I was crowned king in 1025. It was divided among Bolesław III’s sons in 1138.'),
    ('PLK', None, 1138, 1319, 'Poland (the divided duchies)', '966', '1569',
     'Poland was split into duchies among the Piast princes from 1138, with a senior prince in Kraków. The duchies were reunited under Władysław I, crowned king in 1320.'),
    ('PLK', None, 1320, E, 'Kingdom of Poland', '1320', '1569',
     'Poland was reunited under Władysław I (1320) and his son Casimir III the Great, and joined Lithuania in a personal union in 1386, when Grand Duke Jogaila married Queen Jadwiga. It defeated the Teutonic Order at Grunwald in 1410 and took western Prussia in 1466.'),
    ('GPL', None, None, None, 'Duchy of Greater Poland', '1138', '1320',
     'One of the Polish duchies after 1138, around Poznań and Gniezno.'),
    ('LPL', None, None, None, 'Duchy of Kraków and Sandomierz (Lesser Poland)', '1138', '1320',
     'The senior Polish duchy around Kraków, whose ruler was meant to lead the other Piast princes, together with the Duchy of Sandomierz to the east.'),
    ('SIL', None, None, None, 'Silesian duchies', '1138', '1335',
     'The duchies of the Silesian Piasts around Wrocław, Opole and Legnica, which split into many smaller ones. They came under the Bohemian crown by 1335.'),
    ('MAZ', None, None, None, 'Duchy of Masovia', '1138', '1526',
     'A Polish duchy around Płock and later Warsaw, ruled by a branch of the Piasts; its duke called in the Teutonic Order against the Prussians in 1226. From 1351 its dukes were vassals of the Polish king.'),
    ('MAZ_P', None, None, None, 'Duchy of Masovia (Polish fief)', '1138', '1526',
     'The Masovian dukes held their duchy as vassals of the Polish king from 1351 until the last of them died in 1526.'),
    ('KUY', None, None, None, 'Duchy of Kuyavia', '1190s', '1364',
     'A small Polish duchy on the Vistula around Inowrocław.'),
    ('LIT', None, 1000, E, 'Grand Duchy of Lithuania', '1230s', '1569',
     'The state of the pagan Lithuanians united by Mindaugas, which conquered much of the former Kievan Rus’ in the 14th century under Gediminas and Algirdas. Grand Duke Jogaila became king of Poland in 1386 and converted Lithuania to Christianity; under Vytautas (1392–1430) it reached the Black Sea.'),
    ('KIE', None, None, None, "Kievan Rus'", '882', '1240',
     'The state of the Rurikid princes, centered on Kiev, which took Christianity from Byzantium in 988. It was strongest under Yaroslav the Wise (1019–54) and broke up into rival principalities in the 12th century.'),
    ('PKV', None, None, None, 'Principality of Kiev', '1054', '1362',
     'The principality around Kiev, which remained the seat of the senior Rus’ prince after Yaroslav the Wise divided his realm among his sons in 1054, and was fought over by the others. The Mongols sacked Kiev in 1240, and it later came under Lithuania.'),
    ('CHN', None, None, None, 'Principality of Chernigov', '1024', '1239',
     'A Rus’ principality on the Desna, east of the Dnieper, ruled by the Olgovichi branch of the Rurikids. The Mongols sacked Chernigov in 1239.'),
    ('PYS', None, None, None, 'Principality of Pereyaslavl', '1054', '1239',
     'A Rus’ principality on the steppe frontier southeast of Kiev, which guarded against the Cumans. The Mongols destroyed Pereyaslavl in 1239.'),
    ('VLS', None, None, None, 'Vladimir-Suzdal', '11th century', '1331',
     'The northeastern Rus’ principality whose princes Andrei Bogolyubsky and Vsevolod the Big Nest made Vladimir the leading city of the Rus’ in the late 12th century. Under the Mongols its grand-princely title passed between Tver and Moscow.'),
    ('NVG', None, None, None, 'Novgorod', '862', '1478',
     'A trading city in northern Russia, ruled by princes sent from Kiev until 1136 and then a city-state run by its archbishop and assembly, whose lands stretched to the White Sea and the Urals. It paid tribute to the Golden Horde but was never occupied; Ivan III of Moscow annexed it in 1478.'),
    ('PSK', None, 1000, E, 'Pskov', '13th century', '1510',
     'A trading city republic in northwest Russia, independent of Novgorod from 1348 and closely tied to Moscow, which annexed it in 1510.'),
    ('PLT', None, None, None, 'Principality of Polotsk', '987', '1307',
     'A Rus’ principality on the Western Dvina, often independent of Kiev, which ruled Minsk and Vitebsk. It came under Lithuania in the 13th and early 14th centuries.'),
    ('SMO', None, None, None, 'Principality of Smolensk', '1054', '1404',
     'A Rus’ principality on the upper Dnieper. Lithuania took it in 1404.'),
    ('HLC', None, None, None, 'Principality of Halych', '11th century', '1199',
     'A Rus’ principality in Galicia, on the upper Dniester, which grew from the lands of Peremyshl and Terebovlia. Roman of Volhynia united it with Volhynia in 1199.'),
    ('VOL', None, None, None, 'Principality of Volhynia', '987', '1199',
     'A Rus’ principality around Volodymyr, joined with Halych in 1199.'),
    ('GVO', None, None, None, 'Galicia-Volhynia', '1199', '1349',
     'The southwestern Rus’ principality united by Roman the Great; his son Daniel was crowned king in 1253 but had to acknowledge the Golden Horde. After its last prince died in 1340, Poland took Galicia (1349) and Lithuania took Volhynia.'),
    ('TPI', None, None, None, 'Turov and Pinsk', '988', '1320s',
     'A Rus’ principality in the Pripet marshes, which came under Lithuania in the early 14th century.'),
    ('TVE', None, None, None, 'Principality of Tver', '1246', '1485',
     'A Rus’ principality on the upper Volga, Moscow’s chief rival for the grand-princely title under the Mongols. Ivan III annexed it in 1485.'),
    ('NNO', None, None, None, 'Principality of Nizhny Novgorod', '1341', '1392',
     'The Principality of Suzdal-Nizhny Novgorod on the middle Volga. Moscow took it in 1392.'),
    ('RYA_I', None, None, None, 'Principality of Ryazan', '1129', '1521',
     'A Rus’ principality on the middle Oka, southeast of Moscow, on the steppe frontier, often at war with Moscow.'),
    ('RYA', None, 1000, E, 'Principality of Ryazan (under Moscow)', '1129', '1521',
     'From 1456 Ryazan was in effect governed by Moscow, which annexed it in 1521.'),
    ('RUS', None, 1000, E, 'Grand Principality of Moscow (Muscovy)', '1263', 'January 16, 1547',
     'A small principality given to Daniel, son of Alexander Nevsky, in 1263, which grew by collecting the Golden Horde’s tribute for it and by buying and conquering its neighbors. Ivan III (1462–1505) annexed Novgorod and Tver and stopped paying tribute to the Horde in 1480.'),
    ('VBU', None, None, None, 'Volga Bulgaria', '7th century', '1236',
     'A Muslim state of the Bulgars on the middle Volga and Kama rivers, rich from the fur trade. The Mongols destroyed it in 1236.'),
    ('OGZ', None, None, None, 'Oghuz and Pechenegs', '', '',
     'Turkic nomads of the steppe north of the Black Sea. The Pechenegs, who raided Kievan Rus’ and Byzantium, were crushed by Byzantium in 1091 and replaced by the Cumans.'),
    ('CUM', None, None, None, 'Cumans', '1060s', '1240',
     'Turkic nomads, also called the Kipchaks or Polovtsians, who dominated the steppe from the Danube to the Volga from the 1060s. The Mongols conquered them in 1237–41, and many fled to Hungary.'),
    ('GOH', None, None, None, 'Golden Horde', '1242', '1502',
     'The western khanate of the Mongol Empire, founded by Batu, which ruled the steppe from Sarai on the Volga and took tribute from the Rus’ principalities. Timur crushed it in 1395, and in the 15th century it broke up into the khanates of Kazan, Crimea, Astrakhan and the Great Horde.'),
    ('GHO', None, 1000, E, 'Great Horde', '1450s', '1502',
     'The remnant of the Golden Horde on the lower Volga, which lost its hold on Moscow after the standoff on the Ugra River in 1480. The Crimean Khanate destroyed it in 1502.'),
    ('KZN', None, 1000, E, 'Khanate of Kazan', '1438', '1552',
     'A Tatar khanate on the middle Volga founded by a khan of the Golden Horde. Ivan IV of Russia conquered it in 1552.'),
    ('AST', None, 1000, E, 'Khanate of Astrakhan', '1466', '1556',
     'A Tatar khanate at the mouth of the Volga, which Russia conquered in 1556.'),
    ('NOG', None, 1000, E, 'Nogai Horde', '1440s', '1634',
     'A nomadic confederation on the steppe between the Volga and the Ural River, a successor of the Golden Horde.'),
    ('QAS', None, 1000, E, 'Qasim Khanate', '1452', '1681',
     'A small Tatar khanate on the Oka, set up by Moscow for a Tatar prince in its service.'),
    ('CRI_I', None, 1000, E, 'Crimean Khanate', '1441', '1783',
     'A Tatar khanate in Crimea and on the steppe north of it, founded by Hacı Giray.'),
    ('CRI', None, 1000, E, 'Crimean Khanate (Ottoman vassal)', '1441', '1783',
     'The khan accepted Ottoman overlordship after the Ottomans took the Genoese towns on the coast in 1475.'),
]
