"""Descriptions for 1900-2026 (same format as descriptions.py). These come first in the list,
so where a country's older entry has no year bounds, the newer, year-bounded entry wins."""

D20 = [
    # ---------- western Europe ----------
    ('FRA', 'French State', None, None, 'Vichy France (French State)', 'July 10, 1940', 'August 1944',
     'The regime Marshal Pétain set up at Vichy after France’s defeat by Germany in June 1940. The armistice left it the south of the country; it collaborated with Germany, which occupied the south too in November 1942.'),
    ('FRA', None, 1901, 1939, 'French Third Republic', 'September 4, 1870', 'July 10, 1940',
     'France’s longest-lasting republic, proclaimed after Napoleon III’s defeat by Prussia. It won back Alsace-Lorraine in the First World War and fell with the German invasion of 1940.'),
    ('FRA', None, 1945, 1958, 'Liberated France and the Fourth Republic', 'August 1944', 'October 4, 1958',
     'After the liberation of 1944, General de Gaulle’s provisional government restored the republic. A new constitution created the Fourth Republic in 1946; it fell in the crisis over the war in Algeria in 1958.'),
    ('FRA', None, 1959, None, 'French Fifth Republic', 'October 4, 1958', '',
     'The present French republic, with a strong presidency. De Gaulle founded it in 1958 when the Fourth Republic collapsed over the war in Algeria, which became independent in 1962.'),
    ('GBR', None, 1923, None, 'United Kingdom', 'December 6, 1922', '',
     'The United Kingdom of Great Britain and Northern Ireland. It took this form in 1922, when most of Ireland left the union as the Irish Free State after the Irish War of Independence.'),
    ('IRL', 'Irish Free State', None, None, 'Irish Free State', 'December 6, 1922', 'December 29, 1937',
     'A self-governing dominion in the British Commonwealth covering 26 of Ireland’s 32 counties. It was created by the Anglo-Irish Treaty of 1921, which ended the Irish War of Independence.'),
    ('IRL', None, 1923, None, 'Ireland', 'December 29, 1937', '',
     'The Irish state under its constitution of 1937, which named it Éire (Ireland). It stayed neutral in the Second World War and declared itself a republic, leaving the Commonwealth, in 1949.'),
    ('ESP', None, 1900, 1930, 'Kingdom of Spain', '1479', 'April 14, 1931',
     'Spain under the restored Bourbon monarchy (from 1874). Defeat by the United States in 1898 cost it its last major colonies; from 1923 General Primo de Rivera ruled as dictator under King Alfonso XIII.'),
    ('ESP', None, 1931, 1938, 'Second Spanish Republic', 'April 14, 1931', 'April 1, 1939',
     'Spain became a republic when King Alfonso XIII left in 1931. A military uprising in July 1936 began the Civil War, which Franco’s Nationalists won in 1939. The map does not show the war’s front lines.'),
    ('ESP', None, 1939, 1975, 'Francoist Spain', 'April 1, 1939', 'November 20, 1975',
     'The dictatorship of General Francisco Franco, who won the Spanish Civil War of 1936-39. Spain stayed out of the Second World War; after Franco’s death in 1975 it returned to monarchy and democracy.'),
    ('ESP', None, 1976, None, 'Kingdom of Spain', 'November 22, 1975', '',
     'Spain’s parliamentary monarchy under King Juan Carlos I and then Felipe VI. The transition from Franco’s dictatorship led to the democratic constitution of 1978.'),
    ('POR', None, 1911, 1925, 'First Portuguese Republic', 'October 5, 1910', 'May 28, 1926',
     'A revolution in Lisbon overthrew the monarchy in 1910. The republic was unstable, with dozens of governments, and ended in a military coup in 1926.'),
    ('POR', None, 1926, 1973, 'Military dictatorship and Estado Novo', 'May 28, 1926', 'April 25, 1974',
     'The authoritarian regime that followed the coup of 1926, built by António de Oliveira Salazar. It kept Portugal neutral in the Second World War and fought colonial wars in Africa until the Carnation Revolution of 1974.'),
    ('POR', None, 1974, None, 'Portuguese Republic', 'April 25, 1974', '',
     'Portugal’s democracy, founded after the Carnation Revolution of April 1974 ended the dictatorship. Its African colonies became independent in 1974-75.'),
    ('NOR', None, 1906, None, 'Kingdom of Norway', 'June 7, 1905', '',
     'Norway ended its union with Sweden in 1905 and chose a Danish prince as King Haakon VII. Germany occupied it from 1940 to 1945.'),
    ('ITA', None, 1946, None, 'Italian Republic', 'June 2, 1946', '',
     'Italy became a republic by referendum in June 1946, after the fall of Mussolini’s Fascist regime and the Second World War.'),
    ('ISL', 'Iceland', 1944, None, 'Republic of Iceland', 'June 17, 1944', '',
     'Iceland ended its union with Denmark and became a republic in 1944, while American forces were stationed there. It joined NATO in 1949.'),
    ('ISL', None, None, None, 'Kingdom of Iceland', 'December 1, 1918', 'June 17, 1944',
     'Iceland became a sovereign kingdom sharing Denmark’s king under the Act of Union of 1918. After Germany occupied Denmark and Britain occupied Iceland in 1940, it declared itself a republic in 1944.'),
    ('MLT', None, 1964, None, 'Malta', 'September 21, 1964', '',
     'Britain’s colony of Malta, a naval base since 1800, became independent in 1964 and a republic in 1974.'),
    ('VAT', None, None, None, 'Vatican City', 'February 11, 1929', '',
     'The papal city-state inside Rome, created by the Lateran Treaty of 1929 between the Holy See and Mussolini’s Italy. It settled the dispute left by Italy’s capture of Rome in 1870.'),
    ('DAN', None, 1920, 1939, 'Free City of Danzig', 'November 15, 1920', 'September 1, 1939',
     'A self-governing city-state under League of Nations protection, created by the Treaty of Versailles to give Poland access to the sea. Its people were mostly German; Nazi Germany annexed it when it invaded Poland in 1939.'),
    ('SAA_L', None, None, None, 'Territory of the Saar Basin', 'January 10, 1920', 'March 1, 1935',
     'The Treaty of Versailles put the Saar under League of Nations rule for 15 years and gave its coal mines to France. In a 1935 plebiscite over 90% voted to rejoin Germany.'),
    ('SAA', None, None, None, 'Saar Protectorate', '1947', 'December 31, 1956',
     'France separated the Saar from its occupation zone in 1946-47 and ran it as a protectorate with its own government, tied to France economically. Voters rejected a European status in 1955, and it joined West Germany in 1957.'),
    ('MEM', None, None, None, 'Memel Territory', 'January 10, 1920', 'January 1923',
     'The Treaty of Versailles detached the Memel (Klaipėda) region from Germany and placed it under the Allies, with a French administration. Lithuania seized it in a staged revolt in January 1923.'),
    ('FIU', None, None, None, 'Free State of Fiume', 'December 30, 1920', 'February 22, 1924',
     'A city-state set up by the Treaty of Rapallo between Italy and Yugoslavia, after the poet Gabriele D’Annunzio had seized Fiume in 1919-20. Italy annexed it in 1924.'),
    ('TRI', None, None, None, 'Free Territory of Trieste', 'September 15, 1947', 'October 26, 1954',
     'A city-state created by the peace treaty with Italy in 1947, meant to be neutral under the UN. It never got its own government; in 1954 Italy took Zone A around Trieste and Yugoslavia Zone B.'),

    # ---------- Germany and Austria ----------
    ('GER', None, 1919, 1932, 'Weimar Republic (German Reich)', 'November 9, 1918', 'January 30, 1933',
     'Germany’s first democracy, proclaimed when the empire collapsed at the end of the First World War. The Treaty of Versailles (1919) took Alsace-Lorraine, most of Posen and West Prussia, and its colonies.'),
    ('GER', None, 1933, 1945, 'Nazi Germany', 'January 30, 1933', 'May 8, 1945',
     'Hitler’s dictatorship, from his appointment as chancellor in 1933 to Germany’s surrender in May 1945. It annexed Austria and the Sudetenland in 1938 and started the Second World War by invading Poland in 1939.'),
    ('GER', None, 1990, None, 'Germany (Federal Republic)', 'October 3, 1990', '',
     'Reunited Germany. East Germany joined the Federal Republic on October 3, 1990, after the fall of the Berlin Wall and a treaty with the four wartime Allies.'),
    ('FRG', None, None, None, 'West Germany (Federal Republic of Germany)', 'May 23, 1949', 'October 3, 1990',
     'The democratic state founded in 1949 in the American, British and French occupation zones, with its capital at Bonn. It regained full sovereignty in 1955 and absorbed East Germany in 1990.'),
    ('GDR', None, None, None, 'East Germany (German Democratic Republic)', 'October 7, 1949', 'October 3, 1990',
     'The communist state founded in 1949 in the Soviet occupation zone. It built the Berlin Wall in 1961; after the wall fell in 1989 it held free elections and joined West Germany in 1990.'),
    ('WBE', None, None, None, 'West Berlin', '1949', 'October 3, 1990',
     'The American, British and French sectors of Berlin, an enclave inside East Germany. It was tied closely to West Germany but stayed formally under Allied occupation; the Berlin Wall surrounded it from 1961 to 1989.'),
    ('GER_US', None, None, None, 'American occupation zone of Germany', 'June 5, 1945', 'May 23, 1949',
     'After Germany’s surrender the four Allies divided it into zones. The American zone covered Bavaria, Hesse, the north of today’s Baden-Württemberg, and Bremen; it became part of West Germany in 1949.'),
    ('GER_UK', None, None, None, 'British occupation zone of Germany', 'June 5, 1945', 'May 23, 1949',
     'The British zone covered north-west Germany, including the Ruhr, Hamburg and Lower Saxony. It became part of West Germany in 1949.'),
    ('GER_FR', None, None, None, 'French occupation zone of Germany', 'June 5, 1945', 'May 23, 1949',
     'France’s zone was carved out of the American and British zones in 1945: the Palatinate, southern Baden, Württemberg-Hohenzollern and, until 1947, the Saar.'),
    ('GER_SU', None, None, None, 'Soviet occupation zone of Germany', 'June 5, 1945', 'October 7, 1949',
     'The Soviet zone covered eastern Germany up to the Oder and Neisse rivers and surrounded Berlin, itself divided into four sectors. It became East Germany in 1949.'),
    ('AUT', None, 1919, 1944, 'Republic of Austria (First Republic)', 'November 12, 1918', 'March 13, 1938',
     'The German-speaking core of the Habsburg empire, which became a small republic when the empire broke up in 1918. The Treaty of Saint-Germain (1919) forbade union with Germany; Hitler annexed it in 1938.'),
    ('AUT', None, 1945, None, 'Republic of Austria', 'April 27, 1945', '',
     'Austria was restored as a separate state in 1945 but occupied by the four Allies until the State Treaty of 1955, which made it independent and neutral. It joined the European Union in 1995.'),
    ('AUT_ANX', None, None, None, 'Austria annexed by Germany (Anschluss)', 'March 13, 1938', 'April 27, 1945',
     'German troops entered Austria in March 1938 and Hitler declared it part of Germany. The Allies declared the annexation void in 1943, and Austria was restored in 1945.'),
    ('AUT_US', None, None, None, 'American occupation zone of Austria', 'July 1945', 'October 1955',
     'Salzburg and Upper Austria south of the Danube. The four Allies occupied Austria from 1945 until the State Treaty of 1955 restored its independence.'),
    ('AUT_UK', None, None, None, 'British occupation zone of Austria', 'July 1945', 'October 1955',
     'Carinthia, Styria and East Tyrol. The four Allies occupied Austria from 1945 until the State Treaty of 1955 restored its independence.'),
    ('AUT_FR', None, None, None, 'French occupation zone of Austria', 'July 1945', 'October 1955',
     'Tyrol and Vorarlberg. The four Allies occupied Austria from 1945 until the State Treaty of 1955 restored its independence.'),
    ('AUT_SU', None, None, None, 'Soviet occupation zone of Austria', 'April 1945', 'October 1955',
     'Lower Austria, Burgenland and Upper Austria north of the Danube. The Soviet Union withdrew under the State Treaty of 1955, which made Austria neutral.'),

    # ---------- Second World War: occupations, annexations and client states ----------
    ('O_GER_FRA', None, 1914, 1918, 'German-occupied northern France', 'August 1914', 'November 1918',
     'The industrial north-east of France, held by Germany behind the Western Front for most of the First World War.'),
    ('O_GER_FRA', None, 1940, 1944, 'German-occupied France', 'June 22, 1940', 'August 1944',
     'Under the armistice of June 1940 Germany occupied the north and west of France, including Paris and the Atlantic coast. It occupied the south too in November 1942; the Allies liberated most of France in the summer of 1944.'),
    ('O_ITA_FRA', None, None, None, 'Italian-occupied France', 'June 1940', 'September 1943',
     'Italy held a strip around Menton from 1940 and, from November 1942, south-eastern France and Corsica, until its surrender in September 1943.'),
    ('A_GER_FRA', None, None, None, 'Alsace-Moselle annexed by Germany', 'June 1940', '1944',
     'Germany annexed Alsace and the Moselle department in all but name in 1940, expelled many French people and conscripted local men into its army. The region returned to France in 1944-45.'),
    ('A_ITA_FRA', None, None, None, 'Menton area annexed by Italy', 'June 1940', 'September 1943',
     'Italy took a strip of the French Riviera around Menton in its brief attack of June 1940 and treated it as annexed.'),
    ('BNF', None, None, None, 'German-occupied Belgium and northern France', 'May 1940', 'September 1944',
     'After the invasion of May 1940, Germany ruled Belgium and the two northernmost French departments together, under a military administration based in Brussels.'),
    ('O_GER_BEL', None, 1914, 1918, 'German-occupied Belgium', 'August 1914', 'November 1918',
     'Germany invaded neutral Belgium in August 1914 and occupied almost all of it until the armistice; only a strip behind the Yser River stayed free.'),
    ('O_GER_BEL', None, 1940, 1944, 'German-occupied Belgium', 'May 1940', 'September 1944',
     'Germany invaded Belgium in May 1940 and ruled it with northern France under a military administration until the Allies liberated it in September 1944.'),
    ('A_GER_BEL', None, None, None, 'Eupen-Malmedy annexed by Germany', 'May 1940', 'September 1944',
     'The German-speaking districts Belgium gained after the First World War, which Germany annexed in 1940.'),
    ('O_GER_LUX', None, 1914, 1918, 'German-occupied Luxembourg', 'August 2, 1914', 'November 1918',
     'Germany occupied neutral Luxembourg at the start of the First World War, while letting the grand duchess’s government carry on.'),
    ('O_GER_LUX', None, 1940, 1944, 'German-occupied Luxembourg', 'May 10, 1940', 'September 1944',
     'Germany invaded Luxembourg in May 1940, annexed it in all but name in 1942 and conscripted its young men. Grand Duchess Charlotte led a government in exile in London.'),
    ('A_GER_LUX', None, None, None, 'Luxembourg annexed by Germany', 'May 10, 1940', 'September 1944',
     'Germany invaded Luxembourg in May 1940, annexed it in all but name in 1942 and conscripted its young men. Grand Duchess Charlotte led a government in exile in London.'),
    ('O_GER_NLD', None, None, None, 'German-occupied Netherlands', 'May 15, 1940', 'May 5, 1945',
     'Germany invaded the neutral Netherlands in May 1940 and ruled it through a Reich Commissioner, Arthur Seyss-Inquart. About three quarters of Dutch Jews were murdered.'),
    ('O_GER_DEN', None, None, None, 'German-occupied Denmark', 'April 9, 1940', 'May 5, 1945',
     'Germany occupied Denmark in April 1940 but let its government carry on until August 1943, when it took direct control.'),
    ('O_GER_NOR', None, None, None, 'German-occupied Norway', 'April 9, 1940', 'May 8, 1945',
     'Germany invaded Norway in April 1940; the king and government fled to London after two months of fighting. Germany ruled through a Reich Commissioner and Vidkun Quisling’s puppet government.'),
    ('O_GER_GBR', None, None, None, 'German-occupied Channel Islands', 'June 30, 1940', 'May 9, 1945',
     'Germany occupied Jersey, Guernsey, Alderney and Sark in 1940, the only part of the British Isles it took.'),
    ('O_GBR_DEN', None, None, None, 'British-occupied Faroe Islands', 'April 1940', 'September 1945',
     'Britain occupied the Danish Faroe Islands in April 1940, after Germany occupied Denmark, to keep them out of German hands.'),
    ('O_GBR_ISL', None, None, None, 'British-occupied Iceland', 'May 10, 1940', 'July 1941',
     'Britain invaded neutral Iceland in May 1940, after Germany occupied Denmark, to keep the island from Germany. The Icelandic government protested but cooperated.'),
    ('O_USA_ISL', None, None, None, 'American-occupied Iceland', 'July 7, 1941', '1946',
     'The United States took over Iceland’s defense from Britain in July 1941, by agreement with the Icelandic government, and kept forces there until 1946.'),
    ('GGV', None, None, None, 'General Government', 'October 26, 1939', 'January 1945',
     'The part of occupied Poland that Germany did not annex, run by a German governor from Kraków. It was the center of the Holocaust, with the death camps of Treblinka, Sobibor and Belzec.'),
    ('O_GER_POL_I', None, None, None, 'German-occupied Poland', 'September 1939', '1944',
     'Parts of prewar Poland occupied by Germany. The Białystok district, taken from the Soviet Union in 1941, was attached to East Prussia.'),
    ('A_GER_POL_I', None, None, None, 'Western Poland annexed by Germany', 'October 1939', '1945',
     'Western Poland, including Poznań, Łódź, Katowice and Pomerania, which Germany annexed in 1939 and tried to Germanize by expelling Poles. It returned to Poland in 1945.'),
    ('A_GER_DAN', None, None, None, 'Danzig annexed by Germany', 'September 1, 1939', 'March 1945',
     'Nazi Germany annexed the Free City of Danzig on the first day of its invasion of Poland. After the war it became the Polish city of Gdańsk.'),
    ('A_GER_CSK', None, None, None, 'Sudetenland annexed by Germany', 'October 1, 1938', 'May 1945',
     'The German-speaking border regions of Czechoslovakia, which Britain and France let Hitler annex under the Munich Agreement of 1938. They returned to Czechoslovakia in 1945, and most Germans were expelled.'),
    ('A_HUN_CSK', None, None, None, 'Southern Slovakia and Carpathian Ruthenia annexed by Hungary', 'November 1938', '1945',
     'Hungary took southern Slovakia in the First Vienna Award of 1938 and Carpathian Ruthenia in March 1939. After the war Carpathian Ruthenia went to the Soviet Union.'),
    ('BOH', None, None, None, 'Protectorate of Bohemia and Moravia', 'March 16, 1939', 'May 8, 1945',
     'The Czech lands, occupied by Germany in March 1939 in breach of the Munich Agreement and ruled as a German protectorate until the end of the war.'),
    ('SVK_W', None, None, None, 'Slovak Republic (1939-45)', 'March 14, 1939', 'April 4, 1945',
     'A client state of Nazi Germany, declared under German pressure when Hitler broke up what was left of Czechoslovakia in March 1939. It was led by the priest Jozef Tiso.'),
    ('A_GER_LTU', None, None, None, 'Memel annexed by Germany', 'March 23, 1939', 'January 1945',
     'Germany forced Lithuania to hand back the Memel Territory in March 1939. It became part of Soviet Lithuania after the war.'),
    ('A_HUN_ROM', None, None, None, 'Northern Transylvania annexed by Hungary', 'August 30, 1940', '1944',
     'Germany and Italy awarded northern Transylvania to Hungary in the Second Vienna Award of 1940. It returned to Romania after the war.'),
    ('A_HUN_YUG', None, None, None, 'Northern Yugoslavia annexed by Hungary', 'April 1941', '1944',
     'Hungary annexed the Bačka, Baranja, Međimurje and Prekmurje regions when the Axis invaded Yugoslavia in 1941; its troops killed thousands of Serbs and Jews in Novi Sad in 1942.'),
    ('O_HUN_YUG', None, None, None, 'Hungarian-occupied Yugoslavia', 'April 1941', '1944',
     'Hungary occupied Yugoslavia’s northern border regions in 1941, alongside the German invasion.'),
    ('A_ITA_YUG', None, None, None, 'Slovenia and Dalmatia annexed by Italy', 'April 1941', 'September 1943',
     'Italy annexed the Ljubljana region and much of the Dalmatian coast when the Axis partitioned Yugoslavia in 1941. Germany took over when Italy surrendered in 1943.'),
    ('O_ITA_YUG', None, None, None, 'Italian-occupied Yugoslavia', 'April 1941', 'September 1943',
     'Italy occupied the Dalmatian coast, southern Slovenia and Montenegro in 1941, until its surrender in 1943.'),
    ('O_GER_YUG', None, None, None, 'German-occupied Yugoslavia', 'April 1941', '1944',
     'Germany invaded Yugoslavia in April 1941 and partitioned it with its allies. The Red Army and Tito’s partisans drove the Germans out in 1944-45.'),
    ('A_BUL_I_YUG', None, None, None, 'Macedonia annexed by Bulgaria', 'April 1941', 'September 1944',
     'Bulgaria, Germany’s ally, took most of Vardar Macedonia and part of southern Serbia in 1941, and held them until it changed sides in 1944.'),
    ('O_BUL_I_YUG', None, None, None, 'Bulgarian-occupied Yugoslavia', 'April 1941', 'September 1944',
     'Bulgaria occupied most of Vardar Macedonia and part of southern Serbia in 1941.'),
    ('NDH', None, None, None, 'Independent State of Croatia', 'April 10, 1941', 'May 1945',
     'A puppet state created by Germany and Italy when they partitioned Yugoslavia in 1941, ruled by the fascist Ustaše, who carried out mass killings of Serbs, Jews and Roma. It collapsed at the end of the war.'),
    ('SRB_O', None, None, None, 'German-occupied Serbia', 'April 22, 1941', 'October 20, 1944',
     'The German military administration of Serbia after the invasion of Yugoslavia in 1941, with a Serbian collaborationist government under it. The Red Army and Yugoslav partisans took Belgrade in October 1944.'),
    ('O_ITA_MNE', None, None, None, 'Italian-occupied Montenegro', 'April 1941', 'September 1943',
     'Italy occupied Montenegro in 1941 and governed it as a governorate after a revolt that July. Germany took over when Italy surrendered in 1943.'),
    ('O_GER_MNE', None, None, None, 'German-occupied Montenegro', 'September 1943', 'December 1944',
     'German forces took over Montenegro from their Italian ally after Italy’s surrender in 1943, and withdrew in December 1944.'),
    ('O_GER_GRE', None, None, None, 'Axis-occupied Greece', 'April 1941', 'October 1944',
     'Germany, Italy and Bulgaria occupied Greece in April-May 1941. Germany kept Athens, Thessaloniki, most of Crete and key islands, and took over Italy’s zone in 1943; a famine killed some 300,000 people.'),
    ('O_ITA_GRE', None, None, None, 'Italian-occupied Greece', 'April 1941', 'September 1943',
     'Italy held the largest zone of occupied Greece, most of the mainland and the Ionian islands, until its surrender in 1943. Cliopatria’s outline, used here, is approximate.'),
    ('A_BUL_I_GRE', None, None, None, 'Eastern Macedonia and Thrace annexed by Bulgaria', 'April 1941', 'September 1944',
     'Bulgaria occupied and annexed eastern Greek Macedonia and western Thrace in 1941, deporting their Jews and many Greeks.'),
    ('O_BUL_I_GRE', None, None, None, 'Bulgarian-occupied Greece', 'April 1941', 'September 1944',
     'Bulgaria occupied eastern Greek Macedonia and western Thrace in 1941.'),
    ('O_ITA_ALB', None, 1914, 1920, 'Italian-occupied Albania', '1914', 'September 1920',
     'Italy occupied the port of Vlorë in 1914 and much of southern Albania during the First World War. It withdrew after a local uprising in 1920.'),
    ('O_ITA_ALB', None, 1939, 1943, 'Albania under Italian rule', 'April 12, 1939', 'September 8, 1943',
     'Italy invaded Albania in April 1939, drove out King Zog and joined the country to the Italian crown. After the Axis defeat of Yugoslavia it added Kosovo in 1941.'),
    ('O_GER_ALB', None, None, None, 'German-occupied Albania', 'September 1943', 'November 1944',
     'German forces occupied Albania after Italy’s surrender in 1943, until the communist partisans took power in 1944.'),
    ('O_GER_ITA', None, None, None, 'German-occupied Italy', 'September 1943', 'May 1945',
     'When Italy surrendered to the Allies in September 1943, German forces occupied the north and center and fought the Allies up the peninsula until May 1945.'),
    ('RSI', None, None, None, 'Italian Social Republic', 'September 23, 1943', 'April 25, 1945',
     'Mussolini’s puppet state in German-occupied northern Italy, set up after German paratroopers freed him in 1943. It collapsed in April 1945, when partisans shot Mussolini.'),
    ('A_GER_ITA', None, None, None, 'Italian Alps and Adriatic coast annexed by Germany', 'September 1943', 'May 1945',
     'After Italy’s surrender Germany took direct control of the Alpine provinces around Bolzano and the Adriatic coast around Trieste, planning to annex them.'),
    ('O_ITA_MON', None, None, None, 'Italian-occupied Monaco', 'November 1942', 'September 1943',
     'Italian troops occupied Monaco in November 1942, when the Axis took over southern France.'),
    ('O_GER_MON', None, None, None, 'German-occupied Monaco', 'September 1943', 'September 1944',
     'German troops replaced the Italians in Monaco after Italy’s surrender in 1943.'),
    ('O_GER_DOD', None, None, None, 'German-occupied Dodecanese', 'September 1943', 'May 1945',
     'German forces seized the Italian Dodecanese from their former ally after Italy’s surrender in 1943, and held them until the end of the war.'),
    ('O_GER_HUN', None, None, None, 'German-occupied Hungary', 'March 19, 1944', 'April 1945',
     'Germany occupied its ally Hungary in March 1944 to stop it leaving the war. Hungarian authorities then deported some 437,000 Jews to Auschwitz.'),
    ('OST', None, None, None, 'Reichskommissariat Ostland', 'July 1941', '1944',
     'The German civil administration of the Baltic states and western Belarus after the invasion of the Soviet Union in 1941. Most of the area’s Jews were murdered.'),
    ('RKU', None, None, None, 'Reichskommissariat Ukraine', 'September 1, 1941', '1944',
     'The German civil administration of central Ukraine after the invasion of the Soviet Union, ruled harshly by Erich Koch. The Red Army drove the Germans out in 1943-44.'),
    ('O_GER_RUS', None, 1914, 1918, 'German-occupied western Russia (Ober Ost)', '1915', 'November 1918',
     'Germany conquered Lithuania, Courland and western Belarus in 1915 and ran them as a military state, Ober Ost. After the Treaty of Brest-Litovsk (1918) it occupied much more.'),
    ('O_GER_RUS', None, 1941, 1944, 'German-occupied Soviet Union', 'June 22, 1941', '1944',
     'Soviet lands Germany conquered from June 1941 and left under military rule, beyond its two civil administrations (Ostland and Ukraine). The occupation was one of the most murderous in history. Cliopatria’s outline of the front, used here, is approximate.'),
    ('O_ROM_RUS', None, None, None, 'Romanian-occupied Transnistria', 'August 1941', 'March 1944',
     'Romania, Germany’s ally, occupied the land between the Dniester and Bug rivers, including Odessa, as the "Transnistria Governorate", where it deported and killed many Jews and Roma.'),
    ('O_FIN_I_RUS', None, None, None, 'Finnish-occupied East Karelia', 'July 1941', 'June 1944',
     'Finland, fighting alongside Germany in the Continuation War, occupied Soviet East Karelia beyond its prewar border.'),
    ('O_RUS_EST', None, None, None, 'Soviet-occupied Estonia', 'June 17, 1940', 'August 6, 1940',
     'Soviet troops occupied Estonia in June 1940 under the secret protocol of the Molotov-Ribbentrop pact, and staged elections before annexing it in August.'),
    ('O_RUS_LVA', None, None, None, 'Soviet-occupied Latvia', 'June 17, 1940', 'August 5, 1940',
     'Soviet troops occupied Latvia in June 1940 under the secret protocol of the Molotov-Ribbentrop pact, and staged elections before annexing it in August.'),
    ('O_RUS_LTU', None, None, None, 'Soviet-occupied Lithuania', 'June 15, 1940', 'August 3, 1940',
     'Soviet troops occupied Lithuania in June 1940 under the secret protocol of the Molotov-Ribbentrop pact, and staged elections before annexing it in August.'),

    # ---------- First World War occupations and the aftermath ----------
    ('O_GER_POL', None, None, None, 'German-occupied Russian Poland', 'August 1915', 'November 1916',
     'Germany took the Russian part of Poland in 1915 and ruled it from Warsaw as a General Government.'),
    ('O_AUT_POL', None, None, None, 'Austro-Hungarian-occupied Russian Poland', 'August 1915', 'November 1916',
     'Austria-Hungary ruled the southern part of Russian Poland from Lublin after taking it in 1915.'),
    ('POL_R', None, None, None, 'Regency Kingdom of Poland', 'November 5, 1916', 'November 1918',
     'A Polish kingdom proclaimed by Germany and Austria-Hungary in the Russian lands they had conquered, to win Polish support. It never had a king, and handed power to Józef Piłsudski in November 1918.'),
    ('O_GER_UKR', None, None, None, 'German-occupied Ukraine', 'February 1918', 'November 1918',
     'Germany and Austria-Hungary occupied Ukraine after the Treaty of Brest-Litovsk in 1918 and installed Hetman Pavlo Skoropadsky’s government.'),
    ('O_AUT_UKR', None, None, None, 'Austro-Hungarian-occupied Ukraine', 'February 1918', 'November 1918',
     'Austria-Hungary occupied south-western Ukraine, including Odessa, in 1918.'),
    ('O_GER_BLR', None, None, None, 'German-occupied Belarus', 'February 1918', 'December 1918',
     'Germany occupied most of Belarus in its offensive of February 1918; the Belarusian People’s Republic was proclaimed under its occupation.'),
    ('O_GER_EST', None, None, None, 'German-occupied Estonia', 'February 1918', 'November 1918',
     'German troops occupied Estonia in February 1918, a day after it declared independence, and stayed until the armistice in November.'),
    ('O_GER_LVA', None, None, None, 'German-occupied Latvia', '1915', 'November 1918',
     'Germany held Courland from 1915 and the rest of Latvia from 1917-18, until the armistice.'),
    ('O_GER_LTU', None, None, None, 'German-occupied Lithuania', '1915', 'November 1918',
     'Germany occupied Lithuania in 1915. Lithuania declared independence under the occupation in February 1918.'),
    ('O_AUT_SRB_I', None, None, None, 'Austro-Hungarian-occupied Serbia', 'November 1915', 'November 1918',
     'Austria-Hungary, Germany and Bulgaria overran Serbia in late 1915; its army retreated across Albania to Corfu. Austria-Hungary ran most of the country as a military government.'),
    ('O_BUL_I_SRB_I', None, None, None, 'Bulgarian-occupied Serbia', 'October 1915', 'September 1918',
     'Bulgaria occupied eastern Serbia and Vardar Macedonia after joining the Central Powers in 1915.'),
    ('O_AUT_MNE', None, None, None, 'Austro-Hungarian-occupied Montenegro', 'January 1916', 'November 1918',
     'Austria-Hungary occupied Montenegro in January 1916; King Nicholas went into exile.'),
    ('O_AUT_ALB', None, None, None, 'Austro-Hungarian-occupied Albania', '1916', 'November 1918',
     'Austria-Hungary occupied northern and central Albania in 1916, during the First World War.'),
    ('KOR', None, None, None, 'Autonomous Province of Korçë', 'December 10, 1916', '1920',
     'A self-governing Albanian province around Korçë, set up under French military protection on the Macedonian front. It was handed back to Albania in 1920.'),
    ('O_GER_ROM', None, None, None, 'Occupied Romania', 'December 1916', 'November 1918',
     'The Central Powers overran southern Romania, including Bucharest, in late 1916 after Romania joined the Allies. Germany ran the occupation; Romania signed a harsh peace in 1918.'),
    ('O_AUT_ROM', None, None, None, 'Austro-Hungarian-occupied Romania', 'December 1916', 'November 1918',
     'Austria-Hungary shared in the occupation of southern Romania, including Bucharest, from late 1916.'),
    ('O_BUL_I_ROM', None, None, None, 'Bulgarian-occupied Dobruja', 'September 1916', 'November 1918',
     'Bulgaria and its allies took the Dobruja region from Romania in 1916.'),
    ('O_AUT_ITA', None, None, None, 'Austro-Hungarian-occupied Venetia', 'November 1917', 'November 1918',
     'After the Italian defeat at Caporetto in 1917, Austria-Hungary and Germany occupied the Veneto east of the Piave River for a year.'),
    ('O_GRE_OTT', None, None, None, 'Greek-occupied Smyrna', 'May 15, 1919', 'September 9, 1922',
     'Greece landed troops at Smyrna (İzmir) in 1919 with Allied backing, advanced deep into Anatolia and was defeated by the Turkish nationalists in 1922.'),
    ('O_FRA_OTT', None, None, None, 'French-occupied Cilicia', '1919', 'October 1921',
     'France occupied Cilicia in southern Anatolia after the First World War and withdrew after fighting the Turkish nationalists.'),
    ('O_ITA_OTT', None, None, None, 'Italian-occupied Antalya', '1919', '1921',
     'Italy occupied the Antalya region of southern Anatolia after the First World War and withdrew in 1921.'),

    # ---------- central and eastern Europe ----------
    ('POL_I', None, 1918, 1944, 'Second Polish Republic', 'November 11, 1918', 'September 1939',
     'Poland regained independence at the end of the First World War, after 123 years of partition. Its eastern border was fixed by the war with Soviet Russia (1919-21).'),
    ('POL_I', None, 1945, 1989, "Communist Poland (People's Republic)", '1945', 'December 1989',
     'Poland was restored under Soviet control in 1945 and moved west: it lost its eastern lands to the Soviet Union and gained German lands up to the Oder and Neisse rivers.'),
    ('POL_I', None, 1990, None, 'Republic of Poland', 'December 29, 1989', '',
     'Democratic Poland, after the Solidarity movement won the elections of 1989. It joined NATO in 1999 and the European Union in 2004.'),
    ('CSK', None, 1918, 1944, 'Czechoslovakia (First Republic)', 'October 28, 1918', 'October 1938',
     'A democratic republic of Czechs and Slovaks formed from Habsburg lands in 1918 and led by Tomáš Masaryk. The Munich Agreement of 1938 forced it to give the Sudetenland to Germany.'),
    ('CSK', None, 1945, 1989, 'Czechoslovakia (restored, then communist)', 'May 1945', 'December 1989',
     'Czechoslovakia was restored in 1945, minus Carpathian Ruthenia, which went to the Soviet Union. The communists seized power in 1948; a Soviet-led invasion ended the Prague Spring of 1968.'),
    ('CSK', None, 1990, 1992, 'Czech and Slovak Federative Republic', 'November 1989', 'December 31, 1992',
     'Czechoslovakia after the Velvet Revolution of 1989. It split peacefully into the Czech Republic and Slovakia at the end of 1992.'),
    ('CZE', None, None, None, 'Czech Republic (Czechia)', 'January 1, 1993', '',
     'The western part of Czechoslovakia, independent since the peaceful split of 1993. It joined NATO in 1999 and the European Union in 2004.'),
    ('SVK', None, None, None, 'Slovak Republic', 'January 1, 1993', '',
     'Slovakia became independent when Czechoslovakia split peacefully at the end of 1992. It joined NATO and the European Union in 2004.'),
    ('HUN', None, 1918, 1919, 'Hungary after the Habsburgs', 'November 16, 1918', 'March 1, 1920',
     'Hungary left its union with Austria in 1918. A short-lived communist regime under Béla Kun (March-August 1919) fought Romania and Czechoslovakia; Romanian troops took Budapest in August 1919.'),
    ('HUN', None, 1920, 1945, 'Kingdom of Hungary', 'March 1, 1920', 'February 1, 1946',
     'A kingdom without a king, ruled by Regent Miklós Horthy. The Treaty of Trianon (1920) left it less than a third of its prewar land; it regained parts with German help in 1938-41 and lost them again at the end of the war.'),
    ('HUN', None, 1946, 1989, 'Communist Hungary', 'February 1, 1946', 'October 23, 1989',
     'Hungary became a republic in 1946 and a Soviet-style people’s republic from 1949. Soviet troops crushed the revolution of 1956.'),
    ('HUN', None, 1990, None, 'Republic of Hungary', 'October 23, 1989', '',
     'Democratic Hungary, proclaimed on the anniversary of the 1956 revolution. It joined NATO in 1999 and the European Union in 2004.'),
    ('BIH_A', None, None, None, 'Bosnia and Herzegovina, annexed by Austria-Hungary', 'October 6, 1908', 'October 29, 1918',
     'Austria-Hungary annexed Bosnia and Herzegovina, which it had occupied since 1878, in 1908, provoking the Bosnian crisis. A Bosnian Serb killed Archduke Franz Ferdinand in Sarajevo in 1914.'),
    ('BUL_I', None, 1908, 1946, 'Tsardom of Bulgaria', 'October 5, 1908', 'September 15, 1946',
     'Bulgaria declared full independence from the Ottoman Empire in 1908 and its prince took the title tsar. It fought on the losing side in both world wars; a referendum under Soviet occupation abolished the monarchy in 1946.'),
    ('BUL_I', None, 1947, 1990, "People's Republic of Bulgaria", 'September 15, 1946', 'November 15, 1990',
     'Communist Bulgaria, one of the Soviet Union’s closest allies. The Communist Party gave up its monopoly on power in 1989-90.'),
    ('BUL_I', None, 1991, None, 'Republic of Bulgaria', 'November 15, 1990', '',
     'Democratic Bulgaria. It joined NATO in 2004 and the European Union in 2007.'),
    ('ROM', None, 1948, 1989, 'Communist Romania', 'December 30, 1947', 'December 22, 1989',
     'Romania became a people’s republic when the communists forced King Michael to abdicate in 1947. Nicolae Ceaușescu ruled from 1965 until the revolution of December 1989.'),
    ('ROM', None, 1990, None, 'Romania', 'December 1989', '',
     'Democratic Romania, after the revolution of December 1989. It joined NATO in 2004 and the European Union in 2007.'),
    ('GRE', None, 1924, 1935, 'Second Hellenic Republic', 'March 25, 1924', 'November 3, 1935',
     'Greece abolished its monarchy in 1924, after the disastrous war with Turkey of 1919-22 and the exchange of populations that followed. The monarchy returned in 1935.'),
    ('GRE', None, 1936, 1972, 'Kingdom of Greece', 'November 3, 1935', 'June 1, 1973',
     'The restored Greek monarchy. It went through the Metaxas dictatorship, Axis occupation (1941-44), a civil war (1946-49) and, from 1967, a military junta, which abolished the monarchy in 1973.'),
    ('GRE', None, 1973, None, 'Hellenic Republic', 'June 1, 1973', '',
     'Greece has been a republic since the military junta abolished the monarchy in 1973; democracy returned in 1974, after the junta fell over the crisis in Cyprus.'),
    ('DOD', None, None, None, 'Italian Dodecanese (Italian Islands of the Aegean)', 'May 1912', 'February 10, 1947',
     'Italy took the Dodecanese islands from the Ottoman Empire in the Italo-Turkish War of 1912 and kept them under the Treaty of Lausanne (1923). They passed to Greece in 1947.'),
    ('MNE', 'Kingdom of Montenegro', None, None, 'Kingdom of Montenegro', 'August 28, 1910', 'November 26, 1918',
     'Prince Nicholas proclaimed himself king in 1910. Austria-Hungary occupied Montenegro in 1916, and in 1918 an assembly deposed him and joined the new Yugoslav state.'),
    ('MNE', None, 2006, None, 'Montenegro', 'June 3, 2006', '',
     'Montenegro left its union with Serbia after a referendum in May 2006. It joined NATO in 2017.'),
    ('MNE', None, 1911, 1918, 'Kingdom of Montenegro', 'August 28, 1910', 'November 26, 1918',
     'Prince Nicholas proclaimed himself king in 1910. Austria-Hungary occupied Montenegro in 1916, and in 1918 an assembly deposed him and joined the new Yugoslav state.'),
    ('SRB_I', None, 2006, None, 'Republic of Serbia', 'June 5, 2006', '',
     'Serbia became a separate state again when Montenegro voted to leave their union in 2006. Kosovo declared independence from it in 2008, which Serbia does not accept.'),
    ('YUG', 'Kingdom of Serbs, Croats and Slovenes', None, None, 'Kingdom of Serbs, Croats and Slovenes', 'December 1, 1918', 'October 3, 1929',
     'The South Slav state formed at the end of the First World War, when Serbia and Montenegro joined the Habsburg empire’s Slovene, Croat and Serb lands under the Serbian king. It was renamed Yugoslavia in 1929.'),
    ('YUG', 'Serbia and Montenegro', None, None, 'Serbia and Montenegro', 'February 4, 2003', 'June 3, 2006',
     'The loose union that replaced the Federal Republic of Yugoslavia in 2003. Montenegro voted for independence in 2006.'),
    ('YUG', None, 1919, 1944, 'Kingdom of Yugoslavia', 'December 1, 1918', 'April 17, 1941',
     'The South Slav kingdom, named Yugoslavia in 1929, when King Alexander made himself dictator. The Axis powers invaded and partitioned it in April 1941.'),
    ('YUG', None, 1945, 1991, 'Socialist Yugoslavia', 'November 29, 1945', 'June 25, 1991',
     'Tito’s partisans, who led the resistance to the Axis occupation, founded a communist federation of six republics in 1945. It broke with Stalin in 1948 and broke apart in 1991-92.'),
    ('YUG', None, 2003, None, 'Serbia and Montenegro', 'February 4, 2003', 'June 3, 2006',
     'The loose union that replaced the Federal Republic of Yugoslavia in 2003. Montenegro voted for independence in 2006.'),
    ('YUG', None, 1992, 2002, 'Federal Republic of Yugoslavia', 'April 27, 1992', 'February 4, 2003',
     'The union of Serbia and Montenegro left after the other republics broke away in 1991-92. NATO bombed it in 1999 over Kosovo, which then came under UN administration.'),
    ('HRV', None, None, None, 'Republic of Croatia', 'June 25, 1991', '',
     'Croatia declared independence from Yugoslavia in 1991 and fought a war with Serb rebels and the Yugoslav army until 1995. It joined the European Union in 2013.'),
    ('SVN', None, None, None, 'Republic of Slovenia', 'June 25, 1991', '',
     'Slovenia left Yugoslavia in 1991 after a ten-day war. It joined NATO and the European Union in 2004.'),
    ('BIH', None, None, None, 'Bosnia and Herzegovina', 'March 3, 1992', '',
     'Bosnia and Herzegovina declared independence in 1992, which led to a war among its Bosniak, Serb and Croat communities until the Dayton Agreement of 1995. It is divided into two largely self-governing entities.'),
    ('MKD', None, None, None, 'North Macedonia', 'September 8, 1991', '',
     'The former Yugoslav republic of Macedonia became independent in 1991. A dispute with Greece over its name was settled in 2019, when it became North Macedonia.'),
    ('KOS', None, None, None, 'Republic of Kosovo', 'February 17, 2008', '',
     'Kosovo, a mostly Albanian province of Serbia, came under UN administration after the war of 1998-99. It declared independence in 2008; about half the world’s countries recognize it, but Serbia does not.'),
    ('ALB', None, None, 1943, 'Albania', 'November 28, 1912', 'April 12, 1939',
     'Albania declared independence from the Ottoman Empire in 1912, during the First Balkan War. It became a principality, then a republic (1925) and, under Zog I, a kingdom (1928).'),
    ('ALB', None, 1944, 1990, 'Communist Albania', 'November 29, 1944', 'April 29, 1991',
     'Enver Hoxha’s communist partisans took power as the Germans withdrew in 1944. His regime broke with Yugoslavia, the Soviet Union and China in turn, and became one of the most isolated states in the world.'),
    ('ALB', None, 1991, None, 'Republic of Albania', 'April 29, 1991', '',
     'Albania ended one-party rule in 1990-91. It joined NATO in 2009.'),
    ('TRA', None, None, None, 'Trieste Zone A', 'June 1945', 'October 26, 1954',
     'The city of Trieste and its surroundings, run by British and American military government from 1945 until it passed to Italy in 1954.'),
    ('TRB', None, None, None, 'Trieste Zone B', 'June 1945', 'October 26, 1954',
     'The north-west of Istria, run by the Yugoslav army from 1945 and handed to Yugoslavia in 1954.'),

    # ---------- the Baltic, Russia, Ukraine and the Caucasus ----------
    ('EST', None, 1918, 1990, 'Republic of Estonia', 'February 24, 1918', 'June 1940',
     'Estonia declared independence in 1918 and won it in a war against Soviet Russia (1918-20). The Soviet Union occupied it in June 1940 under its pact with Nazi Germany.'),
    ('EST', None, 1991, None, 'Republic of Estonia', 'August 20, 1991', '',
     'Estonia restored its independence in 1991 as the Soviet Union collapsed. It joined NATO and the European Union in 2004.'),
    ('LVA', None, 1918, 1990, 'Republic of Latvia', 'November 18, 1918', 'June 1940',
     'Latvia declared independence in 1918 and won it in wars against Soviet Russia and German forces (1918-20). The Soviet Union occupied it in June 1940.'),
    ('LVA', None, 1991, None, 'Republic of Latvia', 'August 21, 1991', '',
     'Latvia restored its independence in 1991 as the Soviet Union collapsed. It joined NATO and the European Union in 2004.'),
    ('LTU', None, 1918, 1989, 'Republic of Lithuania', 'February 16, 1918', 'June 1940',
     'Lithuania declared independence in 1918. Poland seized its historic capital, Vilnius, in 1920, so Kaunas served as capital; the Soviet Union occupied the country in June 1940.'),
    ('LTU', None, 1990, None, 'Republic of Lithuania', 'March 11, 1990', '',
     'Lithuania was the first Soviet republic to declare independence, in March 1990; it was widely recognized in 1991. It joined NATO and the European Union in 2004.'),
    ('EST_SSR', None, None, None, 'Estonian Soviet republic (annexed)', 'August 6, 1940', 'August 20, 1991',
     'The Soviet Union annexed Estonia in 1940, and again after driving out the Germans in 1944. The United States and most Western countries never recognized the annexation, so the map shows it crosshatched.'),
    ('LVA_SSR', None, None, None, 'Latvian Soviet republic (annexed)', 'August 5, 1940', 'August 21, 1991',
     'The Soviet Union annexed Latvia in 1940, and again after driving out the Germans in 1944. The United States and most Western countries never recognized the annexation, so the map shows it crosshatched.'),
    ('LTU_SSR', None, None, None, 'Lithuanian Soviet republic (annexed)', 'August 3, 1940', 'March 11, 1990',
     'The Soviet Union annexed Lithuania in 1940, and again after driving out the Germans in 1944. The United States and most Western countries never recognized the annexation, so the map shows it crosshatched.'),
    ('RUS', None, 1917, 1917, 'Russian Republic', 'March 1917', 'November 7, 1917',
     'Russia under the Provisional Government, after the February Revolution overthrew the tsar in 1917. The Bolsheviks seized power in October (November by the Western calendar).'),
    ('RUS', None, 1918, 1922, 'Soviet Russia (RSFSR)', 'November 7, 1917', 'December 30, 1922',
     'The Bolshevik state proclaimed after the October Revolution. It made peace with Germany at Brest-Litovsk in 1918, giving up the western borderlands, and won the civil war of 1918-21.'),
    ('RUS', None, 1923, 1991, 'Soviet Union', 'December 30, 1922', 'December 26, 1991',
     'A communist federation of Soviet republics ruled from Moscow, formed in 1922. It took eastern Poland, the Baltic states and Bessarabia in 1939-40, bore the brunt of the war against Germany, and dissolved in 1991.'),
    ('RUS', None, 1992, None, 'Russian Federation', 'December 25, 1991', '',
     'Russia became independent when the Soviet Union dissolved in 1991. It annexed Crimea in 2014 and launched a full-scale invasion of Ukraine in 2022.'),
    ('WHT', None, None, None, 'Government of South Russia', 'April 1920', 'November 1920',
     'The last White government of the Russian Civil War, led by General Wrangel in Crimea and the lands north of it. It was evacuated to Istanbul in November 1920.'),
    ('MRNC', None, None, None, 'Mountain Republic of the Northern Caucasus', 'May 11, 1918', '1919',
     'A state proclaimed by the peoples of the North Caucasus during the Russian Civil War. The White armies overran it in 1919.'),
    ('FIN_I', None, None, None, 'Republic of Finland', 'December 6, 1917', '',
     'Finland declared independence from Russia after the October Revolution and survived a civil war in 1918. It lost part of Karelia to the Soviet Union in the wars of 1939-44 but kept its independence.'),
    ('UKR', None, 1917, 1921, 'Ukrainian People’s Republic', 'January 22, 1918', '1921',
     'Ukraine declared independence from Russia in January 1918. Under German occupation that spring a conservative Hetmanate replaced the republic, which returned in late 1918 but lost the war with Soviet Russia.'),
    ('UKR', None, 1991, None, 'Ukraine', 'August 24, 1991', '',
     'Ukraine declared independence as the Soviet Union collapsed in 1991. Russia annexed Crimea in 2014, backed separatists in the Donbas, and launched a full-scale invasion in February 2022.'),
    ('UKR_S', None, None, None, 'Soviet Ukraine', 'March 10, 1919', 'December 30, 1922',
     'The Ukrainian Soviet republic, set up by the Bolsheviks during the civil war as a nominally separate state. It became a founding member of the Soviet Union in 1922.'),
    ('UKR_O', None, 2014, 2021, 'Crimea, occupied by Russia', 'February 27, 2014', '',
     'Russian troops seized Crimea in February 2014, and Russia annexed it in March after a referendum held under occupation. The UN General Assembly and most countries do not recognize the annexation.'),
    ('UKR_O', None, 2022, None, 'Russian-occupied Ukraine', 'February 24, 2022', '',
     'The parts of Ukraine held by Russia: Crimea and part of the Donbas since 2014, and much of the south and east since the full-scale invasion of 2022. Russia claims to have annexed four regions; the UN General Assembly rejected this. The line is DeepState’s, as of July 1.'),
    ('DLR', None, None, None, 'Donetsk and Luhansk "people’s republics"', 'April 2014', 'September 30, 2022',
     'Separatist statelets in Ukraine’s Donbas, set up in 2014 with Russian backing and held with the help of Russian troops. Russia recognized them in February 2022, days before its full-scale invasion, and claimed to annex them that September.'),
    ('BLR', None, 1918, 1919, 'Belarusian People’s Republic', 'March 25, 1918', '1919',
     'Belarusian nationalists proclaimed a republic under German occupation in 1918. It had no army and lost out to Soviet Belarus.'),
    ('BLR', None, 1991, None, 'Republic of Belarus', 'August 25, 1991', '',
     'Belarus became independent when the Soviet Union collapsed in 1991. Alexander Lukashenko has ruled it since 1994, in close alliance with Russia.'),
    ('BLR_S', None, None, None, 'Soviet Belarus', 'January 1, 1919', 'December 30, 1922',
     'The Byelorussian Soviet republic, a nominally separate state during the civil war, which became a founding member of the Soviet Union.'),
    ('MDA', None, None, None, 'Republic of Moldova', 'August 27, 1991', '',
     'The former Moldavian Soviet republic, mostly the old Bessarabia, became independent in 1991. Russian-backed separatists hold Transnistria, east of the Dniester.'),
    ('TRN', None, None, None, 'Transnistria', 'September 2, 1990', '',
     'A strip of Moldova east of the Dniester, with a largely Russian-speaking population, which broke away in 1990 and won a short war in 1992 with the help of Russian troops, who remain. No UN member recognizes it.'),
    ('GEO', None, 1918, 1921, 'Democratic Republic of Georgia', 'May 26, 1918', 'March 1921',
     'Georgia declared independence when the Transcaucasian federation broke up in 1918. The Red Army invaded in 1921.'),
    ('GEO', None, 1922, None, 'Georgia', 'April 9, 1991', '',
     'Georgia declared independence from the Soviet Union in 1991. It lost control of Abkhazia and South Ossetia in wars in the early 1990s, and fought Russia over them in 2008.'),
    ('GEO_S', None, None, None, 'Soviet Georgia', 'February 1921', 'December 30, 1922',
     'The Georgian Soviet republic set up after the Red Army’s invasion of 1921. It joined the Transcaucasian federation and then, in 1922, the Soviet Union.'),
    ('ABK', None, None, None, 'Abkhazia', '1993', '',
     'A region on Georgia’s Black Sea coast that broke away in the war of 1992-93, when most of its Georgian population fled. Russia recognized it as independent in 2008 and keeps troops there; Georgia and most countries regard it as occupied.'),
    ('SOS', None, None, None, 'South Ossetia', '1992', '',
     'A region in northern Georgia whose Ossetian leaders broke away in 1991-92. After the Russian-Georgian war of 2008 Russia recognized it and stationed troops there; Georgia and most countries regard it as occupied.'),
    ('ARM', None, 1918, 1921, 'First Republic of Armenia', 'May 28, 1918', 'December 2, 1920',
     'Armenia declared independence as the Transcaucasian federation broke up in 1918. Squeezed between Turkey and Soviet Russia, it became a Soviet republic in 1920.'),
    ('ARM', None, 1922, None, 'Republic of Armenia', 'September 21, 1991', '',
     'Armenia became independent as the Soviet Union collapsed. It backed the Armenians of Nagorno-Karabakh in their war with Azerbaijan (1988-94) and lost that region in 2020-23.'),
    ('ARM_S', None, None, None, 'Soviet Armenia', 'December 1920', 'December 30, 1922',
     'The Armenian Soviet republic established after the Red Army entered in late 1920.'),
    ('AZE', None, 1918, 1920, 'Azerbaijan Democratic Republic', 'May 28, 1918', 'April 28, 1920',
     'The first democratic republic in the Muslim world, declared in 1918. The Red Army took Baku in April 1920.'),
    ('AZE', None, 1921, None, 'Republic of Azerbaijan', 'October 18, 1991', '',
     'Azerbaijan became independent as the Soviet Union collapsed. It lost Nagorno-Karabakh and the districts around it in a war with Armenian forces (1988-94), retook most in 2020 and the rest in 2023.'),
    ('AZE_S', None, None, None, 'Soviet Azerbaijan', 'April 28, 1920', 'December 30, 1922',
     'The Azerbaijani Soviet republic, set up when the Red Army took Baku in 1920.'),
    ('TSF', None, None, None, 'Transcaucasian Soviet Federation', 'March 12, 1922', '1936',
     'A federation of Soviet Georgia, Armenia and Azerbaijan, which joined the Soviet Union as one republic in 1922.'),
    ('ART', None, None, None, 'Artsakh (Nagorno-Karabakh)', 'January 6, 1992', 'January 1, 2024',
     'An Armenian-populated region of Azerbaijan that broke away in the war of 1988-94, when Armenian forces also took the districts around it. Azerbaijan retook the districts in 2020 and the region itself in September 2023; nearly all its Armenians fled.'),
    ('KAZ', None, None, None, 'Kazakhstan', 'December 16, 1991', '',
     'The former Kazakh Soviet republic, independent since 1991. Only its far west lies within this map.'),

    # ---------- the Mediterranean and the Middle East ----------
    ('TUR', None, None, None, 'Republic of Turkey', 'October 29, 1923', '',
     'The state founded by Mustafa Kemal (Atatürk) in the Ottoman Empire’s Anatolian heartland, after the Turkish War of Independence (1919-22). The Treaty of Lausanne (1923) fixed its borders; since 2022 its English name is Türkiye.'),
    ('CYP_B', None, None, None, 'British Cyprus', 'November 5, 1914', 'August 16, 1960',
     'Britain annexed Cyprus, which it had run under Ottoman sovereignty since 1878, when the Ottoman Empire entered the First World War against it. It became a Crown colony in 1925 and independent in 1960.'),
    ('CYP_I', None, None, None, 'Republic of Cyprus', 'August 16, 1960', '',
     'Cyprus became independent from Britain in 1960 under a power-sharing constitution between Greek and Turkish Cypriots. After a coup backed by Greece’s junta, Turkey invaded in 1974, and the island has been divided since.'),
    ('NCY', None, None, None, 'Northern Cyprus', 'July 20, 1974', '',
     'The north of Cyprus, held by Turkish troops since the invasion of July-August 1974. A Turkish Cypriot state was declared there in 1983; only Turkey recognizes it.'),
    ('MOR_F', None, None, None, 'French protectorate of Morocco', 'March 30, 1912', 'March 2, 1956',
     'France made most of Morocco a protectorate under the Treaty of Fez in 1912, leaving the sultan in place. Morocco regained independence in 1956.'),
    ('MOR_S', None, None, None, 'Spanish protectorate of Morocco', 'November 27, 1912', 'April 7, 1956',
     'Spain ran northern Morocco, around Tetuan and the Rif mountains, as a protectorate from 1912. The Rif War of 1921-26 was fought there.'),
    ('MOR', None, 1956, None, 'Kingdom of Morocco', 'March 2, 1956', '',
     'Morocco regained independence from France and Spain in 1956 and became a kingdom under Mohammed V in 1957.'),
    ('TNG', None, None, None, 'Tangier International Zone', '1925', '1956',
     'The port of Tangier, run jointly by the European powers under a convention of 1923. Spain occupied it during the Second World War; it joined independent Morocco in 1956.'),
    ('RIF', None, None, None, 'Republic of the Rif', 'September 18, 1921', 'May 27, 1926',
     'A state set up by the Berber leader Abd el-Krim after he defeated a Spanish army at Annual in 1921. France and Spain crushed it in 1926.'),
    ('TUN_I', None, None, None, 'Republic of Tunisia', 'March 20, 1956', '',
     'Tunisia regained independence from France in 1956 and became a republic under Habib Bourguiba in 1957.'),
    ('ALG_I', None, None, None, 'Algeria', 'July 5, 1962', '',
     'Algeria won independence from France in 1962 after an eight-year war. Before that, northern Algeria was governed as part of France.'),
    ('SYR_M', None, None, None, 'French mandate for Syria', '1920', '1946',
     'France took Syria from the Ottoman Empire after the First World War and ruled it under a League of Nations mandate, at first as several separate states. It became independent in 1946.'),
    ('SYR', None, None, None, 'Syria', 'April 17, 1946', '',
     'Syria became independent when the last French troops left in 1946. It merged with Egypt as the United Arab Republic (1958-61), came under Baath party rule in 1963 and fell into civil war in 2011; Bashar al-Assad was overthrown in 2024.'),
    ('LEB_M', None, None, None, 'Lebanon under French mandate', 'September 1, 1920', 'November 22, 1943',
     'France created Greater Lebanon in 1920 from Ottoman lands it held under a League of Nations mandate. It became independent in 1943. Most of it lies just south of this map.'),
    ('LEB', None, None, None, 'Lebanon', 'November 22, 1943', '',
     'Lebanon became independent from France in 1943. Most of it lies just south of this map.'),
    ('IRQ_M', None, None, None, 'British mandate of Iraq', '1920', 'October 3, 1932',
     'Britain took Mesopotamia from the Ottoman Empire in the First World War and ruled it under a League of Nations mandate, with a king, Faisal I, from 1921.'),
    ('IRQ', None, None, None, 'Iraq', 'October 3, 1932', '',
     'Iraq became independent in 1932; a revolution overthrew the monarchy in 1958. Only the north of the country lies within this map.'),
    ('PER', None, 1926, None, 'Iran', '1925', '',
     'Reza Khan overthrew the Qajar dynasty in 1925 and founded the Pahlavi monarchy; Persia was renamed Iran in 1935. The revolution of 1979 made it an Islamic republic.'),
]
