"""Short descriptions of each country period shown on the map: title, when it existed,
and how it began. Written from well-documented history, with Wikidata dates as a check.

Each entry: (unit, name on the map, first map year, last map year) -> (title, from, to, text).
Year bounds are optional (None) and only needed when one name covers different states.
Dates: "Month D, YYYY" when well established, otherwise "YYYY"; "" when unknown or ongoing.
"""

D = [
    ('ALG', 'Regency of Algiers', None, None, 'Regency of Algiers', '1516', 'July 5, 1830',
     'A self-governing Ottoman province on the Barbary Coast, ruled by deys chosen by its garrison. The corsair brothers Barbarossa took Algiers in 1516 and placed it under the Ottoman sultan a few years later.'),
    ('ALG', 'Algiers', None, None, 'Beylik of Constantine (last part of the Regency of Algiers)', '1830', '1837',
     'After France took Algiers in 1830, the eastern province of Constantine held out under its bey, Ahmed, until French troops captured the city in 1837.'),
    ('AND', None, None, None, 'Principality of Andorra', '1278', '',
     'A small principality in the Pyrenees ruled jointly by the Count of Foix (later the French head of state) and the Bishop of Urgell. The shared rule dates from agreements of 1278.'),
    ('ANH', 'Principality of Anhalt-Dessau', None, None, 'Principality of Anhalt-Dessau', '1603', '1807',
     'One of several small Anhalt states in central Germany, ruled by a branch of the House of Ascania. It was created when the Principality of Anhalt was divided among brothers in 1603.'),
    ('ANH', 'Duchy of Anhalt-Dessau', None, None, 'Duchy of Anhalt-Dessau', '1807', '1863',
     'The Anhalt-Dessau branch was raised to a duchy when it joined Napoleon’s Confederation of the Rhine in 1807. It absorbed Anhalt-Köthen in 1853 and Anhalt-Bernburg in 1863, forming the united Duchy of Anhalt.'),
    ('ANH', 'Duchy of Anhalt', None, None, 'Duchy of Anhalt', '1863', '1918',
     'A German duchy formed in 1863, when the other Anhalt lines had died out and all their lands came under the Duke of Anhalt-Dessau. It joined the German Empire in 1871.'),
    ('AUT', 'Habsburg Monarchy', None, None, 'Habsburg Monarchy', '1526', 'August 11, 1804',
     'The lands ruled by the Habsburg dynasty, including Austria, Bohemia, Hungary and Galicia. Its core took shape in 1526, when the Habsburgs inherited the crowns of Bohemia and Hungary.'),
    ('AUT', 'Austrian Empire', None, None, 'Austrian Empire', 'August 11, 1804', '1867',
     'The Habsburg lands united under one imperial title. Francis II proclaimed it in 1804 in answer to Napoleon’s crowning as Emperor of the French, two years before he gave up the Holy Roman crown.'),
    ('AUT', 'Austria-Hungary', None, None, 'Austria-Hungary', '1867', '1918',
     'A dual monarchy of the Austrian Empire and the Kingdom of Hungary under one emperor-king. It was created by the Compromise of 1867, after Austria’s defeat by Prussia in 1866 let Hungary win self-rule.'),
    ('AUT_OCC', None, None, None, 'Bosnia and Herzegovina under Austro-Hungarian rule', '1878', '1908',
     'Ottoman territory occupied and governed by Austria-Hungary. The Congress of Berlin allowed this in 1878, after a revolt against Ottoman rule and the Russo-Turkish War; Austria-Hungary annexed it outright in 1908.'),
    ('BAD', None, None, None, 'Baden (margraviate, electorate from 1803, grand duchy from 1806)', '1771', '1918',
     'A state in southwest Germany ruled by the House of Zähringen. Its two margraviates were reunited in 1771; as Napoleon’s ally Baden grew several times over, becoming an electorate in 1803 and a grand duchy in 1806.'),
    ('BAV', 'Bavaria', None, None, 'Electorate of Bavaria (Kingdom from 1806)', '1623', '1806',
     'A large state in southern Germany ruled by the Wittelsbach family. Its duke became a prince-elector in 1623; allied with Napoleon, Bavaria gained Tyrol and other lands and was made a kingdom on January 1, 1806.'),
    ('BAV', 'Kingdom of Bavaria', None, None, 'Kingdom of Bavaria', 'January 1, 1806', '1918',
     'Bavaria was raised from an electorate to a kingdom in 1806 as Napoleon’s ally, under the Peace of Pressburg. It kept its crown after 1815 and joined the German Empire in 1871 with special rights.'),
    ('BERG', 'Duchy of Berg', None, None, 'Duchy of Berg', '1380', '1806',
     'A duchy on the lower Rhine around Düsseldorf, held by the Wittelsbach rulers of Bavaria. It became a duchy in 1380; in 1806 Bavaria ceded it to Napoleon.'),
    ('BERG', None, None, None, 'Grand Duchy of Berg', 'March 15, 1806', '1813',
     'A Napoleonic state on the lower Rhine, first given to his brother-in-law Joachim Murat. It was formed in 1806 from the Duchy of Berg, given up by Bavaria, and Cleves, given up by Prussia; it collapsed after Napoleon’s defeat at Leipzig in 1813.'),
    ('BRE', None, None, None, 'Free City of Bremen', '1646', '',
     'A self-governing trading city on the Weser, recognized as a free city of the Holy Roman Empire in 1646. France annexed it from 1811 to 1813; it regained independence and joined the German Confederation in 1815.'),
    ('BRU', None, None, None, 'Duchy of Brunswick', '1815', '1918',
     'A north German state ruled by a branch of the Welf family, related to the kings of Hanover. Napoleon gave its lands to the Kingdom of Westphalia in 1807; restored in 1813, it became the Duchy of Brunswick.'),
    ('COS', None, None, None, 'Republic of Cospaia', '1440', '1826',
     'A tiny independent republic on the border of the Papal States and Tuscany. It arose by accident in 1440, when a strip of land was left out of a border treaty between the two; they divided it in 1826.'),
    ('DEN', 'Denmark–Norway', None, None, 'Denmark–Norway', '1537', 'January 14, 1814',
     'The joint kingdom of Denmark and Norway, which also held Iceland, the Faroes, Greenland and the duchies of Schleswig and Holstein. Norway was joined to Denmark in 1380 and made part of the Danish realm in 1537.'),
    ('DEN', 'Denmark', None, None, 'Kingdom of Denmark', 'January 14, 1814', '',
     'Denmark after the Treaty of Kiel of 1814, which gave Norway to Sweden because Denmark had sided with Napoleon. It kept Iceland, the Faroes and Greenland, and held Schleswig, Holstein and Lauenburg until the war of 1864.'),
    ('ESP', None, None, None, 'Kingdom of Spain', '1479', '',
     'The Spanish monarchy formed by the union of the crowns of Castile and Aragon in 1479. From 1808 to 1813 Napoleon’s brother Joseph held the throne while Spaniards and the British fought the French; the Bourbons returned in 1814.'),
    ('FRA', 'French Republic', 1800, 1804, 'French First Republic (the Consulate)', 'September 21, 1792', 'May 18, 1804',
     'France after the monarchy was abolished during the Revolution. From November 1799 Napoleon Bonaparte ruled it as First Consul, after his coup of 18 Brumaire; he proclaimed himself emperor in 1804.'),
    ('FRA', 'French Republic', 1848, 1852, 'French Second Republic', 'February 24, 1848', 'December 2, 1852',
     'Created by the February Revolution of 1848, which overthrew King Louis-Philippe. Its elected president, Louis-Napoleon Bonaparte, seized full power in a coup in 1851 and made himself emperor a year later.'),
    ('FRA', 'French Republic', 1870, 1900, 'French Third Republic', 'September 4, 1870', '1940',
     'Proclaimed in Paris on September 4, 1870, after Napoleon III was captured at Sedan in the war with Prussia. It gave up Alsace and part of Lorraine to Germany in 1871.'),
    ('FRA', 'French Republic (Empire)', None, None, 'First French Empire', 'May 18, 1804', '1815',
     'Napoleon Bonaparte proclaimed himself Emperor of the French in 1804. At its height in 1811 the empire stretched from Hamburg to Rome; it fell with his abdication in 1814 and, after the Hundred Days, in 1815.'),
    ('FRA', 'French Empire', None, None, 'First French Empire', 'May 18, 1804', '1815',
     'Napoleon Bonaparte proclaimed himself Emperor of the French in 1804. At its height in 1811 the empire stretched from Hamburg to Rome; it fell with his abdication in 1814 and, after the Hundred Days, in 1815.'),
    ('FRA', 'Kingdom of France', None, None, 'Kingdom of France (Restoration and July Monarchy)', 'April 1814', 'February 24, 1848',
     'The monarchy restored after Napoleon’s fall, first under the Bourbon kings Louis XVIII and Charles X. The July Revolution of 1830 replaced them with Louis-Philippe of the Orléans branch, who ruled until the revolution of 1848.'),
    ('FRA', 'Second French Empire', None, None, 'Second French Empire', 'December 2, 1852', 'September 4, 1870',
     'Louis-Napoleon Bonaparte, president of the Second Republic, made himself Emperor Napoleon III a year after his 1851 coup. France gained Nice and Savoy in 1860; the empire collapsed when he was captured at Sedan in 1870.'),
    ('GBR', 'Kingdom of Great Britain', None, None, 'Kingdom of Great Britain', 'May 1, 1707', 'January 1, 1801',
     'Formed by the union of England and Scotland under the Acts of Union of 1707. It merged with the Kingdom of Ireland on January 1, 1801.'),
    ('GBR', None, None, None, 'United Kingdom of Great Britain and Ireland', 'January 1, 1801', '1922',
     'Created by the Acts of Union of 1800, which joined Great Britain and Ireland under one parliament from January 1, 1801, after the Irish rebellion of 1798. It also held Gibraltar, Malta and Heligoland.'),
    ('GEN', 'Ligurian Republic', None, None, 'Ligurian Republic', 'June 14, 1797', 'June 4, 1805',
     'A French-backed republic that replaced the old Republic of Genoa in 1797, after Napoleon’s campaign in Italy. France annexed it in 1805.'),
    ('GEN', None, None, None, 'Republic of Genoa (restored)', 'April 1814', 'January 1815',
     'The old Republic of Genoa was briefly restored when the French left in April 1814. The Congress of Vienna gave it to the Kingdom of Sardinia, which took over in January 1815.'),
    ('GEO', None, None, None, 'Kingdom of Kartli-Kakheti', '1762', '1801',
     'An eastern Georgian kingdom formed in 1762, when Heraclius II united Kartli and Kakheti. It placed itself under Russian protection in 1783, and Russia annexed it in 1801.'),
    ('HAN', 'Hanover', 1800, 1810, 'Electorate of Hanover', '1692', '1806',
     'A north German state whose rulers had also been kings of Great Britain since 1714. It became an electorate in 1692; France occupied it in 1803, and it was divided among Prussia, Westphalia and France until 1813.'),
    ('HAN', None, None, None, 'Kingdom of Hanover', 'October 12, 1814', 'September 20, 1866',
     'The Electorate of Hanover, restored and raised to a kingdom at the Congress of Vienna in 1814. It shared its king with Britain until 1837; Prussia annexed it after Hanover sided with Austria in the war of 1866.'),
    ('HDA', 'Hesse-Darmstadt', 1800, 1806, 'Landgraviate of Hesse-Darmstadt', '1567', '1806',
     'A German state created in 1567, when Hesse was divided among the sons of Philip the Magnanimous. It was raised to the Grand Duchy of Hesse when it joined Napoleon’s Confederation of the Rhine in 1806.'),
    ('HDA', None, None, None, 'Grand Duchy of Hesse (Hesse-Darmstadt)', 'August 1806', '1918',
     'The former Landgraviate of Hesse-Darmstadt, raised to a grand duchy when it joined Napoleon’s Confederation of the Rhine in 1806. It gained Rhenish Hesse around Mainz in 1816.'),
    ('HKA', 'Hesse-Kassel', None, None, 'Landgraviate of Hesse-Kassel (Electorate of Hesse from 1803)', '1567', '1807',
     'A German state created in 1567, when Hesse was divided. Its ruler became a prince-elector in 1803; Napoleon abolished it in 1807 and gave its lands to the Kingdom of Westphalia, and it was restored in 1813.'),
    ('HKA', None, None, None, 'Electorate of Hesse (Hesse-Kassel)', '1803', '1866',
     'The former Landgraviate of Hesse-Kassel, whose ruler became a prince-elector in 1803. Restored in 1813 after Napoleonic rule, it kept the title of electorate until Prussia annexed it after the war of 1866.'),
    ('HOH', 'Hohenzollern-Hechingen', None, None, 'Principality of Hohenzollern-Hechingen', '1576', '1850',
     'A small principality in Swabia, ruled by a Catholic branch of the Hohenzollern family. It was created by a division of the family lands in 1576; its prince handed it to Prussia in 1850.'),
    ('HOH', None, None, None, 'Principality of Hohenzollern-Sigmaringen', '1576', '1850',
     'A small principality on the upper Danube, ruled by a Catholic branch of the Hohenzollern family. It was created by a division of the family lands in 1576; its prince handed it to Prussia in 1850.'),
    ('HRE', None, None, None, 'Holy Roman Empire', '962', 'August 6, 1806',
     'A loose union of hundreds of German and central European states under an elected emperor, by then always a Habsburg. It dated from Otto I’s crowning in 962; Francis II dissolved it in 1806 after Napoleon founded the Confederation of the Rhine.'),
    ('ION_S', None, None, None, 'Septinsular Republic', 'March 21, 1800', '1807',
     'The first modern self-governing Greek state, covering the seven Ionian Islands. Russia and the Ottoman Empire created it in 1800 after driving out the French, under Ottoman overlordship and Russian protection; France took the islands back in 1807.'),
    ('ION', None, None, None, 'United States of the Ionian Islands', 'November 5, 1815', 'May 28, 1864',
     'A British protectorate over the seven Ionian Islands, set up by the Treaty of Paris in 1815. Britain handed the islands to Greece in 1864.'),
    ('IRL', None, None, None, 'Kingdom of Ireland', '1542', 'January 1, 1801',
     'A kingdom under the English, later British, crown with its own parliament. Henry VIII created the title in 1542; the Acts of Union merged it with Great Britain in 1801.'),
    ('LIE', None, None, None, 'Principality of Liechtenstein', 'January 23, 1719', '',
     'A small principality on the upper Rhine. The emperor created it in 1719 by joining the lordships of Vaduz and Schellenberg; it became fully sovereign in 1806 as a member of the Confederation of the Rhine.'),
    ('LIP', None, None, None, 'Principality of Lippe', '1789', '1918',
     'A small state in northwest Germany. Its counts, who had ruled since the 1100s, became princes in 1789; it joined the Confederation of the Rhine in 1807 and later the German Empire.'),
    ('LUB', None, None, None, 'Free City of Lübeck', '1226', '1937',
     'A Baltic trading city and former leader of the Hanseatic League. It became a free imperial city in 1226; France annexed it from 1811 to 1813, and it was restored as a free city in 1815.'),
    ('LUC', 'Republic of Lucca', None, None, 'Republic of Lucca', '1160', 'June 23, 1805',
     'An old city republic in Tuscany, self-governing since the 1100s. In 1805 Napoleon turned it into the Principality of Lucca and Piombino for his sister Elisa.'),
    ('LUC', 'Principality of Lucca and Piombino', None, None, 'Principality of Lucca and Piombino', 'June 23, 1805', '1814',
     'A principality Napoleon created in 1805 for his sister Elisa Bonaparte by joining the Republic of Lucca and Piombino. It ended with his fall in 1814.'),
    ('LUC', None, None, None, 'Duchy of Lucca', '1815', 'October 5, 1847',
     'A small duchy created at the Congress of Vienna in 1815 for the Bourbon-Parma family, who had lost Parma. As planned in 1815, it was merged into Tuscany in 1847.'),
    ('LUX', None, None, None, 'Grand Duchy of Luxembourg', 'June 9, 1815', '',
     'Created at the Congress of Vienna in 1815 as a personal possession of the Dutch king and a member of the German Confederation. It lost its western half to Belgium in 1839; the union with the Dutch crown ended in 1890.'),
    ('MKS', 'Grand Duchy of Mecklenburg-Schwerin', None, None, 'Grand Duchy of Mecklenburg-Schwerin', '1815', '1918',
     'The Duchy of Mecklenburg-Schwerin, raised to a grand duchy at the Congress of Vienna in 1815. It joined the German Empire in 1871.'),
    ('MKS', None, None, None, 'Duchy of Mecklenburg-Schwerin', '1701', '1815',
     'A north German duchy on the Baltic, formed when Mecklenburg was divided in 1701. Its duke became a grand duke at the Congress of Vienna in 1815.'),
    ('MKST', 'Grand Duchy of Mecklenburg-Strelitz', None, None, 'Grand Duchy of Mecklenburg-Strelitz', '1815', '1918',
     'The Duchy of Mecklenburg-Strelitz, raised to a grand duchy at the Congress of Vienna in 1815. It joined the German Empire in 1871.'),
    ('MKST', None, None, None, 'Duchy of Mecklenburg-Strelitz', '1701', '1815',
     'A small north German duchy, formed when Mecklenburg was divided in 1701. Its duke became a grand duke at the Congress of Vienna in 1815.'),
    ('MNE', 'Prince-Bishopric of Montenegro', None, None, 'Prince-Bishopric of Montenegro', '1516', 'March 13, 1852',
     'A mountain state ruled by Orthodox bishops, from 1697 of the Petrović-Njegoš family, who held both church and state power. The office dates from 1516; Montenegro resisted Ottoman control and was self-ruling in practice.'),
    ('MNE', None, None, None, 'Principality of Montenegro', 'March 13, 1852', '1910',
     'Danilo Petrović-Njegoš turned the prince-bishopric into a secular principality in 1852. The Congress of Berlin recognized its independence in 1878 and nearly doubled its territory.'),
    ('MOL', None, None, None, 'Principality of Moldavia', '1359', 'January 24, 1859',
     'A Romanian principality between the Carpathians and the Dniester, under Ottoman overlordship but ruled by its own princes. Founded in the 1300s, it lost Bessarabia to Russia in 1812 and united with Wallachia in 1859.'),
    ('MOR', None, None, None, 'Sultanate of Morocco (Alawi dynasty)', '1666', '',
     'Morocco under the Alawi dynasty, which has ruled since Moulay Rashid took Fez in 1666. It stayed independent through the 1800s.'),
    ('NAP', 'Kingdom of the Two Sicilies', None, None, 'Kingdom of the Two Sicilies', 'December 1816', 'March 17, 1861',
     'The Bourbon kingdoms of Naples and Sicily, merged into one state in 1816 after the Congress of Vienna restored King Ferdinand. Garibaldi’s expedition of 1860 brought it down, and it became part of Italy.'),
    ('NAP', None, None, None, 'Kingdom of Naples', '1282', 'December 1816',
     'The kingdom of southern Italy, ruled by a branch of the Spanish Bourbons from 1734. Napoleon gave it to his brother Joseph in 1806 and to Joachim Murat in 1808; the Bourbons returned in 1815 and merged it with Sicily in 1816.'),
    ('NAS', 'Nassau-Weilburg', None, None, 'Principality of Nassau-Weilburg', '', '1806',
     'A small principality on the Lahn, ruled by a branch of the House of Nassau. In 1806 it merged with Nassau-Usingen to form the Duchy of Nassau.'),
    ('NAS', None, None, None, 'Duchy of Nassau', 'August 30, 1806', '1866',
     'A German duchy formed in 1806 when the Nassau-Usingen and Nassau-Weilburg lines joined their lands on entering the Confederation of the Rhine. Prussia annexed it after the war of 1866.'),
    ('NIT', 'Cisalpine Republic', None, None, 'Cisalpine Republic', 'June 29, 1797', 'January 26, 1802',
     'A French sister republic in northern Italy, centered on Milan, created by Napoleon in 1797 from Lombardy and neighboring lands. It was renamed the Italian Republic in 1802.'),
    ('NIT', 'Italian Republic', None, None, 'Italian Republic', 'January 26, 1802', 'March 17, 1805',
     'The renamed Cisalpine Republic, with Napoleon as its president. It became the Kingdom of Italy in 1805, with Napoleon as king.'),
    ('NIT', None, None, None, 'Kingdom of Italy (Napoleonic)', 'March 17, 1805', '1814',
     'A kingdom in northern Italy with Napoleon as king and his stepson Eugène de Beauharnais as viceroy. It was created from the Italian Republic in 1805, later gained Venetia and the Marches, and ended in 1814.'),
    ('NLD', 'Kingdom of Holland', None, None, 'Kingdom of Holland', 'June 5, 1806', 'July 9, 1810',
     'A kingdom Napoleon created in 1806 for his brother Louis. After Louis resisted French demands, Napoleon annexed it to France in 1810.'),
    ('NLD', 'Sovereign Principality of the United Netherlands', None, None, 'Sovereign Principality of the United Netherlands', 'December 1813', 'March 16, 1815',
     'The Dutch state restored after the French left in November 1813, with William of Orange as sovereign prince. It became the Kingdom of the Netherlands in 1815, joined with the former Austrian Netherlands.'),
    ('NLD', 'Kingdom of the Netherlands', None, None, 'Kingdom of the Netherlands', 'March 16, 1815', '',
     'William I proclaimed himself king in 1815, and the Congress of Vienna joined the northern and southern Netherlands (today’s Belgium) under him. Belgium broke away in 1830; the Netherlands accepted its independence in 1839.'),
    ('NLD', None, None, None, 'Batavian Republic', 'January 19, 1795', 'June 5, 1806',
     'A French sister republic that replaced the Dutch Republic in 1795, after French troops and Dutch Patriots drove out the stadtholder. Napoleon turned it into the Kingdom of Holland in 1806.'),
    ('OLD', None, None, None, 'Duchy of Oldenburg (grand duchy from 1815)', '1774', '1918',
     'A state in northwest Germany, raised from a county to a duchy in 1774. France annexed it from 1810 to 1813; its ruler was given the grand ducal title in 1815.'),
    ('OTT', None, None, None, 'Ottoman Empire', '1299', '1922',
     'A Turkish Muslim empire founded around 1299 by Osman I in northwest Anatolia. In 1800 it still held the Balkans, Anatolia and the Arab lands; during the century it lost most of its Balkan provinces.'),
    ('PAP', None, None, None, 'Papal States', '756', 'September 20, 1870',
     'Lands in central Italy ruled by the pope as a monarch, dating from the Donation of Pepin in 756. France annexed them from 1809 to 1814; Italy took most of them in 1860 and Rome in 1870.'),
    ('PAR', None, None, None, 'Duchy of Parma and Piacenza', '1545', '1859',
     'A duchy in northern Italy created by Pope Paul III for his son in 1545. It came under French control in 1802 and was annexed in 1808; restored in 1814 for Napoleon’s wife Marie Louise, it joined Sardinia in 1860.'),
    ('PER', None, None, None, 'Qajar Iran (Persia)', '1789', '1925',
     'Iran under the Qajar dynasty, founded by Agha Mohammad Khan, who united the country in the 1780s and 1790s. It lost Georgia and the eastern Caucasus to Russia in wars ending in 1813 and 1828.'),
    ('PIO', None, None, None, 'Principality of Piombino', '1399', '1805',
     'A small principality on the Tuscan coast, facing Elba, dating from 1399. France took it over in 1801, and in 1805 Napoleon joined it with Lucca for his sister Elisa.'),
    ('POR', None, None, None, 'Kingdom of Portugal', '1139', 'October 5, 1910',
     'One of Europe’s oldest kingdoms, independent since the 1100s. When France invaded in 1807, the royal family fled to Brazil and returned only in 1821; Brazil broke away in 1822.'),
    ('PRU', None, None, None, 'Kingdom of Prussia', 'January 18, 1701', '1918',
     'The kingdom of the Hohenzollern family, ruled from Berlin. Elector Frederick III of Brandenburg crowned himself king in 1701; Prussia lost half its lands to Napoleon in 1807, regained much in 1815, and led German unification.'),
    ('RAG', None, None, None, 'Republic of Ragusa (Dubrovnik)', '1358', 'January 31, 1808',
     'A merchant republic on the Adriatic coast, today’s Dubrovnik. It became self-governing in 1358, when Venice gave up control; France occupied it in 1806 and abolished it in 1808.'),
    ('RHC', None, None, None, 'Confederation of the Rhine', 'July 12, 1806', '1813',
     'A league of German states under Napoleon’s protection, founded in 1806 by 16 princes who left the Holy Roman Empire. It came to cover most of Germany outside Austria and Prussia and broke up after Napoleon’s defeat at Leipzig in 1813.'),
    ('RUS', None, None, None, 'Russian Empire', '1721', '1917',
     'Peter the Great proclaimed Russia an empire in 1721, after victory over Sweden in the Great Northern War. During the 1800s it gained Finland, Bessarabia, most of Poland and the Caucasus.'),
    ('SAL', None, None, None, 'Archbishopric of Salzburg (electorate from 1803)', '', '1805',
     'A state ruled by its archbishops until 1803, when it was secularized and given to the former Grand Duke of Tuscany as an electorate. Austria took it in 1805.'),
    ('SAR', None, 1800, 1813, 'Kingdom of Sardinia', '1720', '1861',
     'The kingdom of the House of Savoy: Piedmont, Savoy, Nice and the island of Sardinia. France took the mainland between 1798 and 1802, leaving the king only the island of Sardinia until 1814.'),
    ('SAR', None, None, None, 'Kingdom of Sardinia', '1720', '1861',
     'The kingdom of the House of Savoy, named after the island it received in 1720. It regained Piedmont, Savoy and Nice in 1814, gained Genoa in 1815, and led the unification of Italy, becoming the Kingdom of Italy in 1861.'),
    ('SAX', 'Saxony', None, None, 'Electorate of Saxony', '1356', 'December 20, 1806',
     'A major German state ruled by the Wettin family from Dresden. Its ruler was a prince-elector from 1356 and was made king in 1806 as Napoleon’s ally.'),
    ('SAX', None, None, None, 'Kingdom of Saxony', 'December 20, 1806', '1918',
     'Saxony became a kingdom under the Treaty of Posen in 1806, after joining Napoleon. Because it stayed loyal to him, the Congress of Vienna gave much of its territory to Prussia in 1815.'),
    ('SCH', None, None, None, 'Principality of Schaumburg-Lippe', '1647', '1918',
     'A tiny state in northwest Germany, created in 1647 when the County of Schaumburg was divided after its ruling line died out. Its count became a prince in 1807.'),
    ('SIC', 'Kingdom of Sicily', 1848, 1849, 'Kingdom of Sicily (revolution of 1848–49)', 'March 25, 1848', 'May 15, 1849',
     'A breakaway state set up by the Sicilian revolution of January 1848 against Bourbon rule from Naples. Neapolitan troops retook the island in 1849.'),
    ('SIC', None, None, None, 'Kingdom of Sicily', '1130', 'December 1816',
     'The island kingdom, ruled by the Bourbon king of Naples. When the French took Naples in 1806, the king ruled from Palermo under British protection until 1815; Sicily and Naples were merged into the Two Sicilies in 1816.'),
    ('SMR', None, None, None, 'Republic of San Marino', '301', '',
     'A small republic on Monte Titano, by tradition founded in 301. It kept its independence through the Napoleonic era and the unification of Italy.'),
    ('SUI', 'Helvetic Republic', None, None, 'Helvetic Republic', 'April 12, 1798', 'March 10, 1803',
     'A centralized French client republic that replaced the old Swiss Confederacy after the French invasion of 1798. Napoleon ended it in 1803 with the Act of Mediation.'),
    ('SUI', 'Swiss Confederation', None, None, 'Swiss Confederation (Act of Mediation)', 'March 10, 1803', '1815',
     'A confederation of 19 cantons restored by Napoleon’s Act of Mediation in 1803, under French influence. It ended with Napoleon’s fall; the Congress of Vienna recognized Swiss neutrality in 1815.'),
    ('SUI', None, None, None, 'Switzerland', 'August 7, 1815', '',
     'The Swiss Confederation as rebuilt in 1815 with 22 cantons, including Geneva, Valais and Neuchâtel. After a brief civil war in 1847, the constitution of 1848 turned it into a federal state.'),
    ('SWB', None, None, None, 'Principality of Schwarzburg-Rudolstadt', '1599', '1918',
     'A small state in Thuringia, formed in 1599 when the County of Schwarzburg was divided. Its count became a prince in 1710.'),
    ('SWE', None, None, None, 'Kingdom of Sweden', '', '',
     'The Swedish kingdom, which lost Finland to Russia in 1809. In 1810 it chose the French marshal Bernadotte as heir; he joined the coalition against Napoleon and in 1814 won Norway, which stayed in union with Sweden until 1905.'),
    ('TUS', 'Kingdom of Etruria', None, None, 'Kingdom of Etruria', '1801', 'December 10, 1807',
     'A kingdom Napoleon created from Tuscany in 1801 for the Bourbon heir of Parma, under a treaty with Spain. France annexed it in 1807.'),
    ('TUS', None, None, None, 'Grand Duchy of Tuscany', '1569', '1859',
     'Created in 1569, when the pope made Cosimo de’ Medici grand duke; the Habsburg-Lorraine family inherited it in 1737. Napoleon took it in 1801; restored in 1814, it joined Sardinia in 1860 after its grand duke fled in 1859.'),
    ('WAL', None, None, None, 'Principality of Wallachia', '1330', 'January 24, 1859',
     'A Romanian principality between the Carpathians and the Danube, under Ottoman overlordship but ruled by its own princes. It dates from the early 1300s and united with Moldavia in 1859.'),
    ('WALD', None, None, None, 'Principality of Waldeck (and Pyrmont)', '1712', '1918',
     'A small state in Hesse, ruled by its own counts since the 1100s. It became a principality in 1712; Prussia took over running it in 1868.'),
    ('ARE', None, None, None, 'Duchy of Arenberg-Meppen', '1803', '1810',
     'A small duchy in northwest Germany given to the Duke of Arenberg in 1803 to make up for his lands west of the Rhine, which France had taken. France annexed it in 1810.'),
    ('ASC', None, None, None, 'Principality of Aschaffenburg', '1803', '1810',
     'The remnant of the Archbishopric of Mainz east of the Rhine, left to its last elector, Karl von Dalberg, in 1803. In 1810 it became part of his Grand Duchy of Frankfurt.'),
    ('REG', None, None, None, 'Principality of Regensburg', '1803', '1810',
     'A small state around the city of Regensburg, created in 1803 for Karl von Dalberg, the last Elector of Mainz. It was handed to Bavaria in 1810.'),
    ('VAL', None, None, None, 'Republic of Valais', 'August 1802', 'November 1810',
     'A small republic in the upper Rhône valley, split off from the Helvetic Republic by Napoleon in 1802 to control the Simplon Pass road. France annexed it in 1810.'),
    ('WUR', None, None, None, 'Württemberg (duchy, electorate from 1803, kingdom from 1806)', '1495', '1918',
     'A state in southwest Germany. Its duke became a prince-elector in 1803 and, as Napoleon’s ally, a king on January 1, 1806, roughly doubling his lands; Württemberg joined the German Empire in 1871.'),
    ('ISE', None, None, None, 'Principality of Isenburg', '1806', '1815',
     'A small principality near Frankfurt, formed in 1806 for Prince Karl of Isenburg-Birstein when he joined Napoleon’s Confederation of the Rhine. After 1815 it was divided between Hesse-Darmstadt and Hesse-Kassel.'),
    ('NEU', None, None, None, 'Principality of Neuchâtel', '1806', '1814',
     'A principality that belonged to the King of Prussia. Prussia ceded it to Napoleon in 1806, who gave it to his marshal Berthier; after 1814 it returned to Prussia and also joined Switzerland as a canton.'),
    ('REU', None, None, None, 'Principality of Reuss (younger line)', '1806', '1918',
     'A small Thuringian state ruled by the younger line of the House of Reuss, whose counts became princes in 1806. The branches of the younger line were united in 1848.'),
    ('SXA', None, None, None, 'Duchy of Saxe-Altenburg', '1826', '1918',
     'One of the small Ernestine duchies in Thuringia, ruled by relatives of the Saxon royal house. The duchy in this form was created in 1826, when the Saxon duchies were rearranged; before that Altenburg belonged to Saxe-Gotha-Altenburg.'),
    ('SXW', None, None, None, 'Grand Duchy of Saxe-Weimar-Eisenach', '1741', '1918',
     'An Ernestine duchy in Thuringia formed in 1741 by uniting Saxe-Weimar and Saxe-Eisenach, with its capital at Weimar. It was raised to a grand duchy at the Congress of Vienna in 1815.'),
    ('WRZ', None, None, None, 'Grand Duchy of Würzburg', '1806', '1814',
     'A state created in 1805–06 for Ferdinand, former Grand Duke of Tuscany, from the old Prince-Bishopric of Würzburg. It went to Bavaria in 1814, when Ferdinand returned to Tuscany.'),
    ('LEY', None, None, None, 'Principality of Leyen', '1806', '1814',
     'A tiny principality in the Black Forest whose prince became sovereign in 1806 by joining the Confederation of the Rhine. It lost its independence after Napoleon’s fall, and Baden took it over in 1819.'),
    ('WAR', None, None, None, 'Duchy of Warsaw', 'July 1807', '1815',
     'A Polish state Napoleon created under the Treaties of Tilsit in 1807 from lands Prussia had taken in the partitions of Poland, with the King of Saxony as duke. Russia occupied it in 1813; the Congress of Vienna divided it in 1815.'),
    ('DAN', None, None, None, 'Free City of Danzig', 'September 9, 1807', 'January 2, 1814',
     'A city-state Napoleon created under the Treaties of Tilsit in 1807, taking Danzig from Prussia and keeping a French garrison there. It returned to Prussia after a long siege in 1813–14.'),
    ('WES', None, None, None, 'Kingdom of Westphalia', '1807', 'October 26, 1813',
     'A kingdom Napoleon created for his brother Jérôme. It was formed under the Treaties of Tilsit in 1807 from Hesse-Kassel, Brunswick and Prussian lands west of the Elbe, and collapsed after the Battle of Leipzig in 1813.'),
    ('BEN', None, None, None, 'Principality of Benevento', 'June 5, 1806', '1815',
     'A papal enclave inside the Kingdom of Naples that Napoleon seized and gave to his foreign minister Talleyrand in 1806. It went back to the pope in 1815.'),
    ('PON', None, None, None, 'Principality of Pontecorvo', 'June 5, 1806', '1815',
     'A small papal enclave in southern Italy that Napoleon made a principality for his marshal Bernadotte in 1806. After Bernadotte became heir to Sweden it passed to Murat’s son; it went back to the pope in 1815.'),
    ('FIN', None, None, None, 'Grand Duchy of Finland', 'March 29, 1809', 'December 6, 1917',
     'A self-governing part of the Russian Empire, with the tsar as grand duke. Russia conquered Finland from Sweden in 1808–09, and the Diet of Porvoo in 1809 confirmed Finland’s own laws and institutions.'),
    ('ELB', None, None, None, 'Principality of Elba', 'April 1814', 'February 26, 1815',
     'The island given to Napoleon as a small sovereign state by the Treaty of Fontainebleau after his abdication in 1814. He left it in February 1815 to return to France.'),
    ('HAM', None, None, None, 'Free City of Hamburg', '', '',
     'A self-governing port city on the Elbe and a leading Hanseatic trading center. France annexed it from 1811 to 1814; it was restored as a free city in 1815 and joined the German Confederation.'),
    ('MAS', None, None, None, 'Duchy of Massa and Carrara', '', '1829',
     'A small duchy on the Tuscan coast, known for its marble quarries. It was restored in 1814 to Maria Beatrice d’Este and passed to Modena when she died in 1829.'),
    ('MON', None, None, None, 'Principality of Monaco', '1297', '',
     'A small principality on the Mediterranean, ruled by the Grimaldi family since 1297. It was under Sardinian protection from 1815; in 1861 it sold Menton and Roquebrune to France in return for full independence.'),
    ('NOR', None, None, None, 'Kingdom of Norway (in union with Sweden)', 'May 17, 1814', '',
     'Norway declared independence and adopted its own constitution in May 1814, after Denmark ceded it to Sweden. After a short war it accepted union with Sweden under the Swedish king in November 1814, keeping its own government.'),
    ('HHO', None, None, None, 'Landgraviate of Hesse-Homburg', '1622', '1866',
     'A small landgraviate near Frankfurt, split from Hesse-Darmstadt in 1622. It was restored as a sovereign state in 1815 and passed to Hesse-Darmstadt in 1866, then to Prussia.'),
    ('KRA', None, None, None, 'Free City of Kraków', 'May 3, 1815', 'November 16, 1846',
     'A small city-state created at the Congress of Vienna in 1815 under the joint protection of Austria, Prussia and Russia. Austria annexed it in 1846 after a failed Polish uprising.'),
    ('MOD', None, None, None, 'Duchy of Modena and Reggio', '1452', '1859',
     'A duchy in northern Italy held by the Este family and, after 1814, by their Austrian Habsburg heirs. Napoleon took it in 1796; restored in 1814, it joined the Kingdom of Sardinia in 1860.'),
    ('POL', None, None, None, 'Kingdom of Poland (Congress Poland)', 'June 9, 1815', '1867',
     'A Polish kingdom created at the Congress of Vienna in 1815 from most of the Duchy of Warsaw, with the Russian tsar as king. It lost most of its self-rule after the uprisings of 1830–31 and 1863–64.'),
    ('FRK', None, None, None, 'Free City of Frankfurt', '1815', '1866',
     'Frankfurt, seat of the German Confederation’s assembly, restored as a free city by the Congress of Vienna in 1815. Prussia annexed it after the war of 1866.'),
    ('SXC', 'Saxe-Coburg', 1816, 1826, 'Duchy of Saxe-Coburg-Saalfeld', '', '1826',
     'An Ernestine duchy in Thuringia and Franconia. When the Saxon duchies were rearranged in 1826 it gave up Saalfeld and gained Gotha, becoming Saxe-Coburg and Gotha.'),
    ('SXC', None, None, None, 'Duchy of Saxe-Coburg and Gotha', '1826', '1918',
     'An Ernestine duchy formed in 1826, when the Saxon duchies were rearranged and Coburg gained Gotha. Its ruling family provided Belgium’s first king and Prince Albert, husband of Queen Victoria.'),
    ('SXM', None, None, None, 'Duchy of Saxe-Meiningen', '1681', '1918',
     'An Ernestine duchy in Thuringia, created in 1681 by a division of Saxe-Gotha. It gained Hildburghausen and Saalfeld when the Saxon duchies were rearranged in 1826.'),
    ('SXO', None, None, None, 'Saxe-Gotha-Altenburg and Saxe-Hildburghausen', '', '1826',
     'Two small Ernestine duchies in Thuringia. When the Saxe-Gotha-Altenburg line died out in 1825, the duchies were rearranged in 1826: Hildburghausen’s duke moved to Altenburg, and Gotha went to Coburg.'),
    ('GRE', 'Greece', None, None, 'Greece (before the kingdom)', 'February 3, 1830', 'May 7, 1832',
     'Greece won independence after the revolt against Ottoman rule that began in 1821; the London Protocol of February 1830 recognized it. Ioannis Kapodistrias governed it until his murder in 1831; the Great Powers made it a kingdom in 1832.'),
    ('GRE', None, None, None, 'Kingdom of Greece', 'May 7, 1832', '1924',
     'The Great Powers made Greece a kingdom in 1832 under a Bavarian prince, Otto. It gained the Ionian Islands in 1864 and Thessaly and Arta in 1881.'),
    ('BEL', None, None, None, 'Kingdom of Belgium', 'October 4, 1830', '',
     'Belgium declared independence from the United Kingdom of the Netherlands after the revolution of August 1830. The Great Powers recognized it in 1831 and chose Leopold of Saxe-Coburg as king; the Netherlands accepted it in 1839.'),
    ('TUN', None, None, None, 'Beylik of Tunis', '1705', 'May 12, 1881',
     'A self-governing Ottoman province ruled by the Husainid beys since 1705. France made it a protectorate in 1881.'),
    ('TUN_F', None, None, None, 'French protectorate of Tunisia', 'May 12, 1881', '1956',
     'France invaded Tunisia in 1881 and forced the bey to accept a protectorate under the Treaty of Bardo. The bey kept his throne while French officials ran the country.'),
    ('SRB', None, None, None, 'Principality of Serbia', '1815', '1882',
     'A Serbian state that grew out of the uprisings against Ottoman rule in 1804 and 1815. The sultan recognized its self-rule in 1830 and enlarged it in 1833; the Congress of Berlin made it fully independent in 1878.'),
    ('SRB_I', 'Kingdom of Serbia', None, None, 'Kingdom of Serbia', 'March 6, 1882', '1918',
     'Prince Milan Obrenović proclaimed Serbia a kingdom in 1882, four years after the Congress of Berlin recognized its independence and gave it Niš and Pirot.'),
    ('SRB_I', None, None, None, 'Principality of Serbia', '1815', '1882',
     'A Serbian state that grew out of the uprisings against Ottoman rule in 1804 and 1815. The sultan recognized its self-rule in 1830; the Congress of Berlin made it fully independent in 1878.'),
    ('MIL', None, None, None, 'Provisional Government of Milan', 'March 22, 1848', 'August 1848',
     'Formed after the Five Days of Milan in March 1848, when the city rose and drove out the Austrian army. Austria retook Milan in August 1848.'),
    ('ROM_V', None, None, None, 'United Principalities of Moldavia and Wallachia', 'January 24, 1859', 'March 14, 1881',
     'Moldavia and Wallachia joined when both elected the same prince, Alexandru Ioan Cuza, in 1859; the union took the name Romania in 1862. It was under Ottoman overlordship until 1878.'),
    ('ROM', 'Kingdom of Romania', None, None, 'Kingdom of Romania', 'March 14, 1881', '1947',
     'Romania was proclaimed a kingdom in 1881 with Carol I as king, three years after the Congress of Berlin recognized its independence.'),
    ('ROM', None, None, None, 'United Principalities of Romania', 'January 24, 1859', 'March 14, 1881',
     'The union of Moldavia and Wallachia formed in 1859, named Romania from 1862. The Congress of Berlin recognized its independence from the Ottomans in 1878, in return for giving southern Bessarabia to Russia.'),
    ('GAR', None, None, None, 'Garibaldi’s dictatorship in Sicily and Naples', 'May 14, 1860', 'November 1860',
     'Giuseppe Garibaldi declared himself dictator of Sicily in May 1860, after landing with his Thousand volunteers. He went on to take Naples and handed his conquests to King Victor Emmanuel II in November 1860.'),
    ('ITA', None, None, None, 'Kingdom of Italy', 'March 17, 1861', '1946',
     'Proclaimed in 1861, after the Kingdom of Sardinia united most of the peninsula through war and Garibaldi’s campaigns. It gained Venetia in 1866 and Rome in 1870.'),
    ('SHC', None, None, None, 'Schleswig-Holstein under joint Austrian and Prussian rule', 'October 30, 1864', '1866',
     'Denmark gave up the duchies of Schleswig, Holstein and Lauenburg to Austria and Prussia after losing the war of 1864. Their quarrel over the duchies led to the war of 1866, after which Prussia annexed them.'),
    ('GER', 'North German Confederation', None, None, 'North German Confederation', 'July 1, 1867', 'December 31, 1870',
     'A federal state of 22 German states north of the Main River, led by Prussia. Bismarck created it after Prussia defeated Austria in the war of 1866; it became the German Empire in 1871.'),
    ('GER', None, None, None, 'German Empire', 'January 18, 1871', '1918',
     'Proclaimed at Versailles on January 18, 1871, during the war with France, when the southern German states joined the North German Confederation. The King of Prussia became German Emperor, and Germany took Alsace-Lorraine.'),
    ('CYP', None, None, None, 'Cyprus under British administration', 'June 4, 1878', '1914',
     'The Ottoman Empire let Britain occupy and run Cyprus under a convention of 1878, in return for British support against Russia. The island stayed Ottoman in law until Britain annexed it in 1914.'),
    ('BUL', None, None, None, 'Principality of Bulgaria', 'July 13, 1878', 'October 5, 1908',
     'A self-governing principality under Ottoman overlordship, created by the Treaty of Berlin in 1878 after the Russo-Turkish War. It took over Eastern Rumelia in 1885 and declared full independence in 1908.'),
    ('ERU', None, None, None, 'Eastern Rumelia', 'July 13, 1878', 'September 18, 1885',
     'A self-governing Ottoman province south of the Balkan Mountains, created by the Treaty of Berlin in 1878 to keep Bulgaria smaller. A bloodless revolt joined it to Bulgaria in 1885.'),
    ('CRT', None, None, None, 'Cretan State', 'December 1898', '1913',
     'A self-governing state under Ottoman overlordship, set up by the Great Powers after the Cretan revolt of 1897–98, with Prince George of Greece as high commissioner. Crete joined Greece in 1913.'),
]


def lookup(unit, name, year):
    """Index of the description for this country, name and year (or -1)."""
    for i, (u, n, a, b, *_rest) in enumerate(D):
        if u == unit and (n is None or n == name) and (a is None or a <= year) and (b is None or year <= b):
            return i
    return -1
